### ISSUE TITLE
complex cron expression

### ISSUE THREAD

**Issue by elmurci** [agenda/agenda#100]
Hi,

I have tried to schedule a job with a complex cron expression with no luck.
Is there a way of executing something like this?

Execute task on just on 10-Oct-2014 every minute from 15 to 20 h.

Thanks

**Comment by arihantdaga** [comment]
I was also facing the same problem when using repeatEvery() on a newly created job. 

var newJob = agenda.create("my new Job",data);
newJob.repeatEvery("49 17 * * 1,2,3");
newJob.save();

It was causing the job to execute immidiatey after adding. after that it would run fine on the saved time. But for the first time, it was executing without being desired. 

So i changed something in the job.prototype.repeatEvery like this - 
added  " this.computeNextRunAt();";
this gave me desired behaviour.
am i doing anything wrong ?. 


```
Job.prototype.repeatEvery = function(interval, options) {
  options = options || {};
  this.attrs.repeatInterval = interval;
  this.computeNextRunAt();
  this.attrs.repeatTimezone = options.timezone ? options.timezone : null;
  return this;
};

```
