### ISSUE TITLE
Cron missing current month when repeating monthly

### ISSUE THREAD

**Issue by moll** [agenda/agenda#102]
A bug in Cron (https://github.com/ncb000gt/node-cron/issues/117) affects Agenda. Creating this issue here to let you know. In a nutshell, `0 0 15 * *`'s next occurrence is set to Nov 15, not Oct 15 as expected.

**Comment by OmgImAlexis** [comment]
Closing this as it's now 3 years old, hopefully by now the issue has been fixed upstream and shouldn't be affecting agenda anymore.
