### ISSUE TITLE
Pass callback regardless of function length for easier use with co

### ISSUE THREAD

**Issue by moll** [agenda/agenda#103]
Hey,

Agenda kind of breaks now when used with [co](https://github.com/visionmedia/co) — co wraps a generator and returns a function with a single `done` attribute, yet `Job.prototype.run` expects the handler to have a signature of 2 arguments. The result is that the async job is marked completed by Agenda having not even started.

Perhaps not be clever with `fn.length` (as it often breaks when being functional — currying etc.) and always pass a callback in. Those wanting to run they're background jobs _in the background_ can do so by calling `done` themselves.

**Comment by OmgImAlexis** [comment]
@agenda/maintainers can someone that uses co please check to see if this is still an issue.

**Comment by moll** [comment]
I presume it is because https://github.com/agenda/agenda/blob/050d7455633ba747da0a70d24a5eb06b8624c797/lib/job.js#L210 hints towards arity checking.

**Comment by OmgImAlexis** [comment]
Please update to `agenda@2.0.0` and let me know if this is still an issue since we now support Promises out of the box.
