### ISSUE TITLE
saveJob upsert, same name different interval

### ISSUE THREAD

**Issue by elmurci** [agenda/agenda#105]
Hi guys,

I'm trying to run a certain job every minute within a certain interval, for example, from 19:00 until 21:30, so I have to split it into two cron expressions:

```
Job A: * 19-21 14 10 14 - From 19:00 until 21:00
Job A: 0-30 21 14 10 14 - From 21:00 until 21:30
```

With the current saveJob upsert, the first expression creates a record in the db but the second one updates the record instead of creating a new one as they share the same name.

```
this._db.findAndModify({name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
```

Don't you think the following line when upserting a job should have further find parameters?

```
this._db.findAndModify({repeatInterval: props.repeatInterval, name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
```

or even 

```
this._db.findAndModify({data: props.data, repeatInterval: props.repeatInterval, name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
```

So you can execute the same job with a different interval and different passed data.

**Comment by ragulka** [comment]
I also stumbled upon this just now. I tried to schedule the same kind of jobs with 2 different datasets for 2 different intervals. My use case was to handle monthly and yearly subscriptions in the same job definition, only setting the billing cycle in the job data.

**Comment by hvarday** [comment]
Hi,
@ragulka 

Hope you might have found some solution or way-around to your issues, now in my case I want to work on a particular case where the job definition remains constant ```{ "name" : "reminder" }```, with different data-sets.

The issue with having different job names is that I would have to define job(s) on server start for them to run, which is not feasible. (as agenda doesn't store job definition AFAIK)

This would be code snippet
```
agenda.every("in 2 minutes", "reminder", data);
agenda.every("30 seconds", "reminder", data1);
```

**Comment by ragulka** [comment]
@hvarday in my case, I simply used 2 different job names for yearly and monthly subscriptions. However, with many many more different variations, it may not be feasible.

**Comment by hvarday** [comment]
Even I did the same (different job names), but that does have a small issue, the job definition is lost every time server restarts. Although I just have jobs scheduled approximately ```in 1 minute```, which has less chances of getting destroyed.

Thanks @ragulka

**Comment by sossargsyan** [comment]
Seems this is due to the job type of "single" that the `every` creates. Is it possible to make the job type option configurable much like as `concurrency` , `lockLimit`

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
