### ISSUE TITLE
setTimeout in jobProcessing

### ISSUE THREAD

**Issue by Uzlopak** [agenda/agenda#1080]
Hi, 

I rewrote agendajs in our product to adapt for our needs. I also transformed it to typescript. There was a curious issue in jobProcessing method. When I reference jobProcessing directly, it would not work properly, but if i would wrap it in an anonymous function it would work properly:

problem:
`setTimeout(this.jobProcessing, runIn);`

works:
`setTimeout(() => self.jobProcessing(), runIn);`

Any idea?

**Comment by vinioliveira** [comment]
@Uzlopak  the first implementation `setTimeout(this.jobProcessing, runIn);` it won't hold the context if you pass the function reference, on the other hand with an anonymous function the context will be held in the closure. 

a possible solution is bind the context to when passing the function as parameter. 

`setTimeout(this.jobProcessing.bind(self), runIn)`;

**Comment by Uzlopak** [comment]
@vinioliveira 

ah thank you :).
