### ISSUE TITLE
How to schedule a single job to run only once

### ISSUE THREAD

**Issue by MastroLindus** [agenda/agenda#1083]
My use case: migration script. I want to run it after I deploy a new version of my application, I want it to run immediately, only once (even in a multiserver environment), and if the server get restarted again/the code gets executed again, it shouldn't run anymore.

I cannot seem to find how to achieve this by looking at the documentation:
- schedule and "now"  run a job multiple times if the code gets re-executed (like after a server restart) and it doesn't work with multiple servers
- every creates a "single" job that is basically what I want, but it seems strange to have to use "every" for this use case (even if I could workaround it with every 1000years maybe? :P )

Is it possible to create a job of single type to run immediately?  If yes, I guess it should be clearly described how to do it in the documentation. If not, I think the feature should be added (also because it seems that internally the library already can do it, simply there's no API for it)

**Comment by Uzlopak** [comment]
if nextRunAt is set to null, the job will not run again.

**Comment by MastroLindus** [comment]
Should I create a job with "every" and then modify the nextRunAt field manually on the DB?
Can I create a job of type "single" like "every" does, without using "every" ?

The issue is still relevant as I think that even if it's already possible to achieve, there's no proper documentation on how to do it...

**Comment by leonardlin** [comment]
@MastroLindus if it's about db-schema updates, I would look into ORM that have schema updates built in.
But in case it's about generic post-deployment tasks etc.

I have done this the following way:
* each deployment has #build-num or #version-number etc.
* when you create a job you can set: task-name + parameter in data-section
* add the #build-num in the data-section
* On startup check if a job exists: agenda.find()
** the find parameter can include, task + build-num in the data section of the job
* If the job does not exist, create a job with build-num in the data section.
