### ISSUE TITLE
How to configure repeatable single job with initial delay?

### ISSUE THREAD

**Issue by yury-kozlov** [agenda/agenda#1092]
Is it possible to configure initial pre-delay for a job ?
I want to schedule a repeatable job of type single which should start at a specific time.
I know there's an option `skipImmediate`, but I rather need a custom start time.

Or it's simpler to just use: `setTimeout(() => agenda.every(foo, bar), preDelay)` ?

Thanks

**Comment by leonardlin** [comment]
Hi, according to these two posts you can do that

https://github.com/agenda/agenda/issues/758
https://stackoverflow.com/questions/46956527/agenda-js-how-to-schedule-an-event-starting-at-x-time-and-repeat-there-after-ev

works for me

**Comment by yury-kozlov** [comment]
@leonardlin thanks for the answer, but this doesn't help to schedule jobs of type 'single'.
The proposed solution uses "job.repeatEvery" api:
```
agenda.run(() => {
   var event = agenda.create('task', { hello: 'world' })
   event.schedule(new Date('2017-11-01')).repeatEvery('1 month'); 
   agenda.start();
})
```
The problem here is that "job.repeatEvery" is not the same as "agenda.every". Only the later defines a '**single**' type job (job.attrs.type = 'single'): https://github.com/agenda/agenda#everyinterval-name-data-options

**Comment by leonardlin** [comment]
@yury-kozlov 
there is an update.

so according to the doc: https://github.com/agenda/agenda#everyinterval-name-data-options

agenda.every(), takes options, which is passed to job.repeatEvery()

https://github.com/agenda/agenda#everyinterval-name-data-options
job.repeatEvery() has not a startDate (master branch)
