### ISSUE TITLE
How to avoid adding job that already exist

### ISSUE THREAD

**Issue by davidquintard** [agenda/agenda#1095]
Hi there,, my use case is:
Clients send many messages to client A .
I dont want to send an email 'you have received a new message' to client A each time.
I'd like to send a single mail at the end of the day : 'you have received new messages' .

I thought i could do :
1 - create dynamically job 'send new mail' to client A
2 - verify job 'send new mail' to client A exist
3 - if doesnt' exist:create job
4 - if exist: don't create job

At the end of the day, execute and remove job 'send new mail' to client A

Is it possible to do such a thing with agenda ?

Regards

**Comment by aleksey-chichagov** [comment]
You should look on unique function (https://github.com/agenda/agenda#uniqueproperties-options).
e.g.
```
await agenda.create('sendMail', {to:'client A', content: 'some text or etc.'})
.unique({'data.to': 'client A'}, { insertOnly: true })
.save()
```
