### ISSUE TITLE
ReferenceError: Agenda is not defined

### ISSUE THREAD

**Issue by estock** [agenda/agenda#11]
I know this is a total noob question, but how do I include this , I keep getting 

ReferenceError: Agenda is not defined

var agenda = new Agenda();

**Comment by maheshsetti** [comment]
Agenda not working as expected. some times taking too long time to excute..
agenda Version 0.6.28

my test case is:
myapp/agendatest.js

var Agenda     = require('agenda');
var agenda = new Agenda({ db: { address: '127.0.0.1:27017/agenda-example' }});

console.log("hello agenda!");
agenda.define('test', function(job)
{
  console.log('test');
});
agenda.every('3 seconds', 'test');
agenda.start();

help me!
