### ISSUE TITLE
What are the technical reasons of choosing mongo over redis for queue?

### ISSUE THREAD

**Issue by DemGiran** [agenda/agenda#1102]

**Comment by Asaf-S** [comment]
From my knowledge, Redis is not persistent by default, this means that its data get reset every restart/code-update or extra work defining the DB.
There are other libraries that support Redis that you can use - like Bull.

**Comment by simison** [comment]
Also, simplicity with services — if you are already running MongoDB for the application, you might want to use it for this purpose as well.
