### ISSUE TITLE
Is it possible to force run or recall a job

### ISSUE THREAD

**Issue by zoom2009** [agenda/agenda#1106]
Here my problem, I have schedule job was create using timestamp but server is down at that schedule time. My job won't run.

Is it possible, Can I recall that job ?

(sorry for my english)
thank you

**Comment by simllll** [comment]
The job should get picked up, when the server is running again. If the runNextAt date is in the past, the job should run immediately.

Otherwise I recommend you to isntall agendash (or agendash-v2) to see what is in your queue and manage (requeue,delete,..) it
