### ISSUE TITLE
[BUG] Can't schedule the same job twice to be run on different timezones

### ISSUE THREAD

**Issue by VinzGhyz** [agenda/agenda#1110]
I have a job defined to run at 7pm local time in two different places. Scheduling the job twice actually only executes the last one. Any idea how to fix this?

```
await agenda.every("0 19 * * *", "applications digest", { hub: "New York" }, { timezone: config.timezones['New York'] });
await agenda.every("0 19 * * *", "applications digest", { hub: "Brussels" }, { timezone: config.timezones['Brussels'] });
```

I've updated through npm so I'm running the latest version 2.3.0

**Comment by simllll** [comment]
with every agenda ensures that a job is only queued once!
What you could do instead is, to create just a regular recurring job:
```js
const agendaJob = agenda.create('application digest', {...});
	agendaJob.repeatAt('midnight');
	agendaJob.repeatEvery('24 hours');

```
but be awara that you should check if the agenad job has been created in the past already, you can do this by either setting `agendaJob.unique({name: 'applicaiton digest', 'data.hub': 'New York'});`
or by querying agendaJobs and check if the job exists already:
```js
	agenda.jobs({ name: 'applicaiton digest', 'data.hub': 'New York' }).then(async jobs => {
		if (!jobs || jobs.length === 0) {
			// create job
		}
	});

```
personally I would recommend the latter one.
