### ISSUE TITLE
Agenda doesn't seem to be honoring lock limits

### ISSUE THREAD

**Issue by GimpMaster** [agenda/agenda#1118]
I have 4 of the same Agenda node processes running on a single machine using pm2 for process management.

Each of the 4 job runners is expected to take tasks on the start of each hour and compute data for a long duration (multiple minutes). To make sure that no single process locks all the jobs on the start of the hour I set on the Agenda initilization a number of lock limits as seen below:

``` javascript
let agenda = new Agenda({
	db: {
		address: connectionString,
		options: { useUnifiedTopology: true },
		collection: 'agenda'
	},
	maxConcurrency: 1,
	defaultLockLimit: 1,
	defaultConcurrency: 1,
	lockLimit: 1
});
```

Watching the output logs from all 4 processes it seems as though one Agenda is locking all jobs and then working through them sequentially instead of each Agenda grabbing one job, processing, and then returning for the next job.

Any suggestions?

**Comment by GimpMaster** [comment]
Using v3.1.0

**Comment by GimpMaster** [comment]
Looking through the agenda code I believe the problem lives here:

``` javascript
  async function jobQueueFilling(name) {
    // Don't lock because of a limit we have set (lockLimit, etc)
    if (!shouldLock(name)) {
      debug('lock limit reached in queue filling for [%s]', name);
      return;
    }

    // Set the date of the next time we are going to run _processEvery function
    const now = new Date();
    self._nextScanAt = new Date(now.valueOf() + self._processEvery);

    // For this job name, find the next job to run and lock it!
    try {
      const job = await self._findAndLockNextJob(name, definitions[name]);
      // Still have the job?
      // 1. Add it to lock list
      // 2. Add count of locked jobs
      // 3. Queue the job to actually be run now that it is locked
      // 4. Recursively run this same method we are in to check for more available jobs of same type!
      if (job) {
        debug('[%s:%s] job locked while filling queue', name, job.attrs._id);
        self._lockedJobs.push(job);
        definitions[job.attrs.name].locked++;
        enqueueJobs(job);
        await jobQueueFilling(name);
        jobProcessing();
      }
    } catch (error) {
      debug('[%s] job lock failed while filling queue', name, error);
    }
  }

```

Specifically what I think is happening is Agenda calls processJobs on a setInterval(). For every single job definition it calls jobQueueFilling(name), let's say there are 10 definitions. 

Each time jobQueueFiling is called it tests to see if it should lock that job, on the first go you have Zero lock jobs and thus it passes the shouldLock() test. Then it fires off an await self.FindAndLockNextJob(). While Javascript is waiting for the "await" to return the process loop continues and it does this same await self.FindAndLockNextJob() call which will effectively lock ALL 10 jobs immediately by a single process.

Finally those 10 jobs will be returned but it is too late, a single process has already consumed all those jobs, going way above it's lock limit, and has starved the others.

Possible Suggestions:

1. When a job is returned from the self._findAndLockNextJob() it checks to see if the lockLimit has been surpased locally and if so it will return the lock on that job giving it the freedom to be consumed by another Agenda connection.

2. Another option might be to assume you will get the lock and make it so that subsuquent calls to jobQueueFilling and shouldLock will fail until you get the true answer back from findAndLockNextJob


Any thoughts?

**Comment by GimpMaster** [comment]
I forked the repo and fixed using suggestion #1 above. It seems to be working for me. Here is my pull request:

https://github.com/agenda/agenda/pull/1119

**Comment by lxiaoixi** [comment]
I also meet the same problem， I want to know how this problem is finally solved?  Can you tell me?  thanks a lot @GimpMaster @simllll

**Comment by simllll** [comment]
Hi @lxiaoixi . It is not fixed in the main branch,but in the forked @hokify/agenda version. https://www.npmjs.com/package/@hokify/agenda

**Comment by lxiaoixi** [comment]
> Hi @lxiaoixi . It is not fixed in the main branch,but in the forked @hokify/agenda version. https://www.npmjs.com/package/@hokify/agenda

Hi! Thanks a lot !  I will see next。 Can  I ask you another question?   I want to know The difference between maxConcurrency and lockLimit and defaultConcurrency and defaultLockLimit。 for example code:

I set maxConcurrency is 50 and lockLimit is 10,  I create 45 jobs at the same time ,  I use pm2  start 4 process on one machine, I expect every process execute 10 jobs, but I find the extra 5 jobs will never execute。So  how should I set the maxConcurrency and lockLimit,  is lockLimit * 4 = maxConcurrency ?

and how it will execute on two machines?  and  is maxConcurrency option for a db collection?  No matter how many machine have?


`
agenda2.maxConcurrency(50);
agenda2.lockLimit(10)

for(let i = 1; i <= 45; i++) {
    agenda2.define(`oneJob${i}`,  async job => {
        console.log(`oneJob${i}`, job.attrs.data.name,  job.attrs.projectId, new Date());
        await timieout()  // delay 5 seconds
        return Promise.resolve(true)
    });
}
    
(async function() {
    await agenda2.start();  // 开启任务队列

    for(let i = 1; i <= 45; i++) {
        const job = agenda2.create(`oneJob${i}`, { name: `xiaoxi-${i}`});
        job.attrs.projectId = i
        job.unique({ name: `oneJob${i}`, projectId: i})
        job.schedule(1607077004000)
        await job.save()
    }
    
})()

`

**Comment by GimpMaster** [comment]
My merge request was merged....I think this should fix the issue. Closing this.
