### ISSUE TITLE
Package Security - mongodb > bl

### ISSUE THREAD

**Issue by silverskysoft** [agenda/agenda#1121]
Hi,
We are seeing a new advisory on npm security: https://npmjs.com/advisories/1555
 Package         bl
 Dependency of   agenda
 Path            agenda > mongodb > bl

Can you please update mongodb package?

**Comment by simllll** [comment]
Should be fixed by https://github.com/agenda/agenda/commit/6d35cf948c4f63579afd6f3f5c58c75aa4456c69
