### ISSUE TITLE
Does Agenda support Mongo v4?

### ISSUE THREAD

**Issue by jjmschofield** [agenda/agenda#1127]
The documentation specifically references Mongo (v3), does this mean that v4 doesn't work / is not supported?

Of interest because 3.6 is EOL as of April next year:
![image](https://user-images.githubusercontent.com/2678487/95887728-1a18c680-0d78-11eb-85b0-7ed1ea5aff0b.png)

https://www.mongodb.com/support-policy

**Comment by Uzlopak** [comment]
The queries are working on v4.2

**Comment by simllll** [comment]
It works,
but I would recommend to pass in a created mongodb client instance (with new url parser and unified topology set to true).
e.g. 
```js
      client = new MongoClient(mongoCfg, {
        useNewUrlParser: true,
        useUnifiedTopology: true
      });

      await client.connect();

      agenda = new Agenda({mongo: client.db()});
```
