### ISSUE TITLE
Throw error for a non defined process

### ISSUE THREAD

**Issue by Fahme** [agenda/agenda#1136]
Agenda is one of my favorite tools that i primarily use it in most of my application, so thanks for your work on that !

An issue i found while using the tools is that when i define a new job : 

```AGENDA.define('job 1',  () => job1());```

then try to start and schedule a job but with a slight typo for the task name:  

```await AGENDA.schedule('in 1 seconds', 'jb 1'', { data });```

there's no error or indication which describes a no job defined with this name so i get stuck with typo and sometimes i don't know from where is the problem.

Would be ideal to do the following i believe :  

- Check for all defined tasks in ```schedule``` method
- If didn't find a task with the same name passed
- reject with an error that describes the issue.

**Comment by simllll** [comment]
I understand your problem, but this is not solveable by this approach. Imagine multiple agenda instances that process jobs, and another / or more front end servers that queue new jobs.
E.g. frontend server (api) calls `agenda.now('do a long running job')` .. but has no define() at all for this job.
but another server (backend server, worker), has a `agenda.define('do a long running job', ...) ` but not .now or anything like this, it just processes the jobs.
The code base could be totally split, but the main problem is, define() is never actually called in the frontend code.

Another way of coping with issues like this, is to wrap it ina  function.
e.g. make a `startMyJob1(,...)` function, this function has all avaialble "data" properties as function paramters (therefore you can also ensure the right data is passed in), and calls agenda.now() or agenda.schedue(...) with the correct job name. So you have the name of the job only defined at one place (well and at a 2nd place where you actually define the process)
