### ISSUE TITLE
         mongoose.connection.readyState 

### ISSUE THREAD

**Issue by Magambo254** [agenda/agenda#1145]
mongoose.connection.readyState displays 0 in the console.log and the postman app loads forever when trying to send requests

**Comment by Uzlopak** [comment]
Well thats awesome, but mongoose is not used by agenda

**Comment by Magambo254** [comment]
I am trying to send requests to the database. The connection between the app and the database is good, no error found but it still wont post requests, the postman app is loading forever. so I used mongoose.connection.readyState to check connection and it displays 0, so what might be the problem or rather what is the best way of handling this
