### ISSUE TITLE
Ajenda jobs getting scheduled twice. 

### ISSUE THREAD

**Issue by Karansidds** [agenda/agenda#1149]
I followed the Agenda JS setup from this repository but made a few changes of my own. Everything seemed to work fine until I discovered a bug. If I restart the server two times in a row then the same job would get scheduled twice instead of once. I don't want a recurring job, I just want to schedule a one time job by passing a specific date.

### Defining Jobs
`ajenda.js`

```
const agenda = new Agenda({
  db: {
    address: uri,
    collection: 'jobs',
    options: {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    },
  },
});

// Define membership job
agenda.define('endMembership', (job) => {
 // A job
});

// Define notifications job
agenda.define('sendNotification', async (job) => {
  // Another job
});

agenda.on('ready', async () => await agenda.start());

const graceful = () => {
  agenda.stop(() => process.exit(0));
};

process.on('SIGTERM', graceful);
process.on('SIGINT', graceful);

module.exports = agenda;
```

### Scheduling Jobs
`controllers.js`

```
const {
      membership_date,
      customer_id,
      customer_onesignal_id,
      name,
    } = req.body;
    try {
      (async () => {
        // Schedule membership end event
        const end_date = addMinutes(parseISO(membership_date), 5);
        await agenda.schedule(end_date, 'endMembership', {//Some data});

        const seventh_day = addMinutes(parseISO(membership_date), 5);
        await agenda.schedule(seventh_day, 'sendNotification', { //Some data});

        const fourteenth_day = addMinutes(parseISO(membership_date), 4);
        await agenda.schedule(fourteenth_day, 'sendNotification', {//Some data});
      })();

      res.status(200);
    } catch (err) {
      res.status(400);
    }
```

**Comment by Karansidds** [comment]
Could anyone respond to this issue?

**Comment by simllll** [comment]
Please re read the docs. Everytime you call schedule a new job will be queued. If you want it to be unique you can do so:
- by checking if one exists already (check .jobs())
- look for the unique property in the docs
- other methods to ensure that you only call the schedule method only once.

**Comment by simison** [comment]
@Karansidds please feel free to re-open if above doesn't solve it for you. :-)
