### ISSUE TITLE
Enable GitHub discussions

### ISSUE THREAD

**Issue by dandv** [agenda/agenda#1162]
Agenda has become eligible for GitHub Discussion.

Enabling that would let us keep all knowledge in one place (right now it's spread between GitHub and Slack).

Can a repo [admin enable GitHub Discussions](https://github.community/t/prompted-to-create-discussions-but-dont-have-access/150261) please?

**Comment by simison** [comment]
Enabled them 👍  https://github.com/agenda/agenda/discussions

Thanks for the prompt!
