### ISSUE TITLE
I cannot create multiple jobs

### ISSUE THREAD

**Issue by jackmatrix** [agenda/agenda#1168]
I am trying to create multiple job by using a loop but `agenda` only create one job. 

It's very curious . for e.g. 

```javascript
 for( i; i < 100; i++){
     await agenda.every('2 minutes','test',{data : "foobar"});
   }
```

This only save 1 job in my database. I don't know why.

Any idea ?

**Comment by leonardlin** [comment]
I think the message must be different.

See here:
`
agenda.now('lock job', { i: 1 }),
agenda.now('lock job', { i: 2 }),
agenda.now('lock job', { i: 3 })
`

just add `i` to your message.
