### ISSUE TITLE
Is there any plan for `agenda-graphql`?

### ISSUE THREAD

**Issue by tonyfromundefined** [agenda/agenda#1174]
Hello. First of all, we have introduced Agenda in-house and are using it well. Thanks for great project!

Nothing else, we have a need to create several features related to operation internally. (related to Agenda) I wondered if it would be better to use Agenda once wrapped in GraphQL. (I know that REST API is currently supported with `agenda-rest`.)

So, do you have any plans for `agenda-graphql`? If not, can I contribute?

**Comment by simison** [comment]
Hi! No plans currently.

Happy to open you a repository here under `agenda/agenda-graphql` if you would like to contribute, @tonyfromundefined !

Just let us know and hop on our Slack! :-) Write me your email and I'll invite you (my email visible at my profile)

**Comment by simison** [comment]
I'll close this for now, feel free to re-open if you'd like to jump working on it!

**Comment by tonyfromundefined** [comment]
Thank you! I will contact you by e-mail soon.
