### ISSUE TITLE
Update  default useUnifiedTopology option to mongoDb default

### ISSUE THREAD

**Issue by pappyJ** [agenda/agenda#1187]
Displays a warning message in the console if not explicitly declared which is not specified in the project documentation, I fixed it using. 

`agenda.database(DATABASE_LOCAL, 'backups', { useUnifiedTopology: true });` 

but i needed to locate where the code was written in the package to detect it . which might not be easy for all devs using the module

**Comment by leonardlin** [comment]
solved in PR #1200
