### ISSUE TITLE
Timezone option does not work in every()?

### ISSUE THREAD

**Issue by adprajwol** [agenda/agenda#1207]
Although the documentation mentions that this is possible,

```await agenda.every('40 17 * * *', 'do some job', { timezone: 'Europe/Paris'});````

the time zone is still being set to local time zone.

**Comment by leonardlin** [comment]
I can reproduce this, this might be related to the cron-package update

**Comment by leonardlin** [comment]
@adprajwol your problem is a wrong parameter
it should be:
`await agenda.every('40 17 * * *', 'do some job', null, { timezone: 'Europe/Paris'});`

**Comment by leonardlin** [comment]
the 3rd parameter is `data`, timezone goes in the 4th parameter
