### ISSUE TITLE
fail to connect to mongo [dbURI:27017]

### ISSUE THREAD

**Issue by jbrunners** [agenda/agenda#121]
My code:
_var Agenda = require('Agenda')
var dbURI = 'mongodb://login:password@cockney.0.mongolayer.com:10066,cockney.1.mongolayer.com:10066/runners-db'
var agenda = new Agenda({db: { address: 'dbURI'}})
agenda.define('scrap', function(job, done) {//})
agenda.every('10 minutes', 'scrap')
agenda.start()_

shoot this error
_Error: failed to connect to [dbURI:27017]_
at _Agenda/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/mongo_client.js:389_

Any idea why it does not consider my port ?

**Comment by nwkeeley** [comment]
Looks like you are using Compose.io as well?

Here is what I currently have implemented with a replica set and it connects just fine.

var Agenda = require('Agenda');

var agenda = new Agenda({db: { address: 'mongodb://username:password@c305.candidate.35.mongolayer.com:10308,c226.candidate.45.mongolayer.com:10232/database_name_here'}});

agenda.define('foo', function(job, done) {
  console.log('hello world');
  done();
});

agenda.every('1 second', 'foo');

agenda.start();

**Comment by michelem09** [comment]
I'm closing this, feel free to reopen if needed.
