### ISSUE TITLE
Agenda cannot be initialized with TypeScript

### ISSUE THREAD

**Issue by eiskalteschatten** [agenda/agenda#1218]
I am trying to integrate Agenda into a project that is built with TypeScript, but keep receiving the following error if I follow the documentation:

```
TypeError: agenda_1.default is not a constructor
```

My code looks like this:

```
import Agenda from 'agenda';

export const setupAgenda = (): void => {
  const agenda = new Agenda({
    db: {
      address: process.env.MONGO_URL,
    },
  });

  // Jobs will be defined here
};
```

That is literally all I am trying to do at this point. This function is imported by my `app.ts` file and is executed when the application starts. 

When I build the project, it builds without a problem. I get this error during runtime when the application starts.

I also noticed that there are no types for Agenda 4 available despite it making heavy use of TypeScript. Is that intentional?

I am using the following:

- "agenda": "^4.0.1"
- "typescript": "^4.1.3"

And my tsconfig.json looks like this:

```
{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "node",
    "pretty": true,
    "sourceMap": false,
    "target": "es2020",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowJs": true,
    "outDir": "./dist",
    "baseUrl": "./src",
    "lib": ["es2020.string", "esnext.asynciterable"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "dist"
  ]
}
```

Any ideas?

**Comment by eiskalteschatten** [comment]
I found the problem and it has nothing to do with Agenda itself... The problem was that I had all of my files in a folder in the root of my project (as defined in `tsconfig.json`) named `agenda` which then caused a conflict with the package in `node_modules`. I renamed the folder and it worked.

**Comment by boredland** [comment]
>  no types for Agenda 4
do you think this could do the trick?
https://github.com/agenda/agenda/pull/1243

**Comment by eiskalteschatten** [comment]
I'm sure it would since most of Agenda seems to be written in TypeScript. It would certainly help quite a bit.
