### ISSUE TITLE
How to add auto_reconnect option correctly? 

### ISSUE THREAD

**Issue by skotchio** [agenda/agenda#122]
Does agenda set `auto_reconnect` option by default or should I set it myself? If the second one, is the below approach correct?:

```
var agenda = new Agenda({
         db: { 
               address: 'localhost:27017/agenda-example?auto_reconnect=true'
         }, 
         {w: 1, native_parser: true}
});
```

**Comment by ilanbiala** [comment]
@skotchio any idea if it supports it?

**Comment by OmgImAlexis** [comment]
@agenda/maintainers

**Comment by simison** [comment]
Only place where I see `auto_reconnect` mentioned is here on [readme](https://github.com/agenda/agenda/blob/983d6b529430d05f1f74e421bac797fe56e89ec3/README.md#example-usage).

There might be some issues when loosing Mongo connection, though. See #338

**Comment by simison** [comment]
https://github.com/agenda/agenda/issues/338#issuecomment-244540300

Seems like it's on by default as per https://github.com/agenda/agenda/issues/338#issuecomment-244540300:
>Since Mongodb has the auto_reconnect option enabled by default, there is no need to throw an exception on connection loss.
