### ISSUE TITLE
Mongoskin DB and Agenda - No method findAndModify

### ISSUE THREAD

**Issue by venkatsep14** [agenda/agenda#124]
TypeError: Object #<SkinClass> has no method 'findAndModify'

db is the replicatset through mongoskin.
```
db = new Db(props.dbname, replSet, {
    w : 0
});
//tried the values 0 and 1 both for w.
var agenda = new Agenda({mongo: db});
```

Can someone please look into this issue..

**Comment by nwkeeley** [comment]
Not sure if this is a MongoSkin or Agenda issue but if you want to access your collection manually:

var Agenda = require('agenda');
var foo = new Agenda(agendaConfig);
foo._db.findAndModify({_id: jobID}, {}, {$set: {'whatever': 'to whatever'}}, {new: true}, function(err, result) {
    //do the magic.
});

**Comment by OmgImAlexis** [comment]
@agenda/maintainers

**Comment by OmgImAlexis** [comment]
Since this issue is over 2 years old and there's been no replies I'm closing this. If it's still an issue please let us know and someone will re-open it.
