### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by boredland** [agenda/agenda#1249]
to complete the typescript refactor, I'd need you to make a release that includes the declarations - so the deftyped pr can go through eventually:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51150

**Comment by boredland** [comment]
@leonardlin deftyped bot is bumping me very regularly about that. Can you please take care?

**Comment by leonardlin** [comment]
@boredland  thanks for pinging me, I ask the crew if we can make a release

**Comment by koresar** [comment]
@boredland I've just published v4.1 with `.d.ts` typings in it: https://unpkg.com/browse/agenda@4.1.0/dist/
Please test if it works. :)

I'll close this issue. Meanwhile, feel free to report any findings.

**Comment by boredland** [comment]
@koresar I indeed found some conflicts. I created a PR to fix them up: https://github.com/agenda/agenda/pull/1258/files
