### ISSUE TITLE
MongoSkin error when Scheduling > 50 jobs

### ISSUE THREAD

**Issue by nevf** [agenda/agenda#126]
MongoSkin raises an error:
`(node) warning: possible EventEmitter memory leak detected. 51 listeners added. Use emitter.setMaxListeners() to increase limit.`
when you schedule more than 50 jobs in one hit. From what I've read in the MongoSkin issues this is a known problem. It sets a hard limit of 50 listeners in `SkinClass` and I can't see any API for changing this. 

This is not an agenda issue per se. but seems like a design flaw in MongoSkin. I wanted to mention it here in case others run into the same problem.

I've just started using agenda in an app I'm developing, Clibu http://clibu.com and my thanks to the developer, it is great.

**Comment by Nijikokun** [comment]
This fixes the issue (before doing any actions on the agenda object):

```js
agenda._db._emitter._maxListeners = 0
```

**Comment by nevf** [comment]
I've refactored agenda to work directly with the MongoDB Native Driver V2. I personally can't see any benefit from using Mongoskin etc. with agenda and the added dependency for such a small use case isn't warranted. The V2 driver has full support for MongoDB V3. When time permits I'll do a fork etc. In the mean time I'm happy to provide the code.

**Comment by davidglbr** [comment]
thanks @Nijikokun!

**Comment by mathieumg** [comment]
@nevf Thanks! I would love that PR as well. :+1:

**Comment by nevf** [comment]
@mathieumg There is a download link at: https://github.com/rschmukler/agenda/issues/156#issuecomment-107918967

**Comment by mathieumg** [comment]
@nevf Yeah I saw that, thanks, but I'd rather wait for something merged to this project. :smile:

**Comment by droppedoncaprica** [comment]
I've been slacking pretty hard, I'm sorry guys (and gals)!

**Comment by davidglbr** [comment]
As of version 0.7.0 mongoskin  was switched to mongodb native.
Seems like the best fix for this issue is to upgrade your adenga version.

**Comment by nevf** [comment]
Liamdon did a fork ofmy code. See https://github.com/rschmukler/agenda/issues/156 Agenda has no need for Mongoskin.

**Comment by OmgImAlexis** [comment]
Closed in https://github.com/agenda/agenda/blob/b818de4d47a3182b95db327edb12f861738957b0/lib/agenda.js#L4
