### ISSUE TITLE
Types are incorrectly exported

### ISSUE THREAD

**Issue by RA80533** [agenda/agenda#1267]
```ts
import { Agenda } from "agenda";
```

```console
$ yarn run tsc
Could not find a declaration file for module 'agenda'. '/[…]/node_modules/agenda/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/agenda` if it exists or add a new declaration (.d.ts) file containing `declare module 'agenda';`ts(7016)
```

While [`agenda@4.1.0`]() is known to have problems relating to this (see #1265 and #1266), they still exist in the most recent commit on the `master` branch, adc22b8 (as of the time of posting).

Reverting the change made in 4024ad2 to package.json would solve the issue as it currently exists. The driving factor at play here is that the root index.js is considered the entry point of the module but is never part of the TypeScript compilation process; however, if it was processed by TypeScript, compilation would fail because it refers to files resulting from the compilation process.

### Solutions

1. Update the 'main' property in package.json to "./dist/index.js" and delete the root index.js file
2. Create a type declaration file for the root index.js file by hand and update the package.json 'types' property accordingly

/cc @simllll

**Comment by simllll** [comment]
Hi @RA80533 , i will quickly look into it, but I believe I had this issue already and I considered it here once already https://github.com/agenda/agenda/pull/1195/files
I'll check and will create a PR :)

**Comment by RA80533** [comment]
Yeah, it seemed like it was something considered looking back at https://github.com/agenda/agenda/pull/1193#discussion_r559038508. Thanks for the quick response.

**Comment by simllll** [comment]
yeah I think there is actually no problem with setting main to dist/index.js directly, as there is also a default export. I will test it quickly
