### ISSUE TITLE
"scheduled" job is triggered immediately

### ISSUE THREAD

**Issue by sulaysumaria** [agenda/agenda#1269]
I defined a job and scheduled it based on an API call, but the job is being triggered as soon as I make the API call.

```js
// As soon as server starts
agenda.define('logTime', logTime);

// In an API call
await agenda.schedule(moment().add({ minutes: 5 }).valueOf(), 'logTime', { foo: 'bar' });
```

Am I doing something wrong here?

[Edit]

Also is there any way to inform agenda not to run jobs which are scheduled now, but the date is of past? I noticed that if I do following, it is triggered immediately, I would like it not to trigger at all:

```js
await agenda.schedule(moment().subtract({ minutes: 5 }).valueOf(), 'logTime', { foo: 'bar' });
```

**Comment by simison** [comment]
Does it work if you return `toDate()` from Moment instead of valueOf?

For the latter question simply not registering the job in that case seems smart because you'd save effort of Agenda handling such job in first place.

**Comment by sulaysumaria** [comment]
@simison , Agreed.

As for my first comment, yes it works with `toDate()` but not with `valueOf()`
