### ISSUE TITLE
Missing typescript exports in v4.1.0

### ISSUE THREAD

**Issue by tsimbalar** [agenda/agenda#1270]
Hi, we are trying to upgrade an internal project from Agenda **v4.01** to **v4.1.0** .

This is causing some changes that we are probably ok with, but some are a bit blocking, so I wanted to loop back with you to report those.

1. _(Not blocking)_ we used to have imports like `import Agenda from 'agenda';` but they now need to be `import { Agenda } from 'agenda';`
2. _(Not blocking)_ we use to access the type definition for Agenda's configuration with `import Agenda from 'agenda';` and then `const config: Agenda.AgendaConfiguration = { /*...*/};` . Now it is `import { AgendaConfig } from 'agenda';` and `const config: AgendaConfig = { /*...*/};` 
3. _(Not blocking)_ we used to access the type `JobAttributesData` ... it is now no longer exposed , except through `import { JobAttributesData } from 'agenda/dist/job';` .... but I'm feeling uneasy about such an import. Should it be exported from the "root" `agenda` name ? For now we have copied the type declaration in our code 
4. We used to access the type `Job<T>` . It is now longer exposed, except through `import { Job } from 'agenda/dist/job';`  but this feels slightly wrong. Given that that type is already implicitly exported by `agenda.jobs` , would it make sense to have a proper export for that type in the root `agenda` export ? 
5. (Not blocking) In `@types/agenda` , `config.db.address` and `config.db.options` used to be optional ... but it looks like they are now mandatory. Is this on purpose ? 

Thanks for the library, and happy to help if I can somehow.

This might somewhat be related to https://github.com/agenda/agenda/issues/1266 and https://github.com/agenda/agenda/issues/1265

**Comment by thebestnom** [comment]
Also, `agenda.schedule` gets `string[]` for names instead of `string|string[]`

**Comment by koresar** [comment]
4.1.2 was just published. If any bugs found please submit bugs and PRs!
