### ISSUE TITLE
History.md has incorrect cron pattern

### ISSUE THREAD

**Issue by dockleryxk** [agenda/agenda#1271]
[The chart](https://github.com/agenda/agenda/blob/master/History.md#breaking) shows inconsistent information with what is documented on [harrisiirak/cron-parser](https://www.npmjs.com/package/cron-parser). The first slot is seconds, not minutes.

**Comment by koresar** [comment]
Would you please supply a bugfix PR?

**Comment by dockleryxk** [comment]
Sure, I'll make it now
