### ISSUE TITLE
Quicker patch release for types

### ISSUE THREAD

**Issue by thebestnom** [agenda/agenda#1280]
The types in agenda are new and fixed rapidly, I think that if there are fixes in types you should release a patch release immediately instead of waiting for bigger releases 

(Im currently some fixes to be released)

**Comment by RA80533** [comment]
In the meantime, install the package directly from the repository via `npm install git://github.com/agenda/agenda.git`.

**Comment by thebestnom** [comment]
@RA80533 sorry, I can't, Im in offline environment

**Comment by koresar** [comment]
4.1.2 was just released. Please report any bugs. And create PRs. :)
