### ISSUE TITLE
Misleading failure when nextRunAt is null in computeFromInterval

### ISSUE THREAD

**Issue by Aravill** [agenda/agenda#1286]
Hi

I'm having an issue with the `computeFromInterval` function in `compute-next-run-at.ts`. When the `nextRunAt` property passes the `endDate`, the function incorrectly marks the job as failed due to some (I believe) mistakes in the function logic and the job is saved into the database with a +1 fail count and a misleading fail reason.

This is my job instance:
```json
{ 
    "_id" : "60549f13e85acb3f7c284c30", 
    "name" : "test-task", 
    "type" : "single", 
    "data" : {
        "username":  "Philip"
    }, 
    "endDate" : "2021-03-25T14:59:00.000+0000", 
    "lastModifiedBy" : "agenda-mongodb", 
    "nextRunAt" : "2021-03-25T14:59:00.000+0000", 
    "priority" : 0, 
    "repeatInterval" : "* * * * *", 
    "repeatTimezone" : null, 
    "skipDays" : null, 
    "startDate" : "2021-03-25T13:40:00.000+0000", 
    "lockedAt" : "2021-03-25T14:58:59.733+0000", 
    "lastRunAt" : "2021-03-25T14:55:00.003+0000", 
    "failCount" : 33, 
    "failReason" : "failed to calculate nextRunAt due to invalid repeat interval", 
    "failedAt" : "2021-03-25T14:55:00.050+0000", 
    "lastFinishedAt" : "2021-03-25T14:55:00.055+0000"
}
```

After a little bit of digging, I figured out that you set the `nextRunAt` property to `null` if `nextDate` passes `endDate` `[line 86]`
```ts
      if (endDate) {
        const endDateDate: Date = moment
          .tz(moment(endDate).format("YYYY-MM-DD"), timezone!)
          .toDate();
        if (nextDate > endDateDate) {
          nextDate = null;
        }
      }

      this.attrs.nextRunAt = nextDate;
```
but right on the next line, you attempt `[line 96]`
```ts
      debug(
        "[%s:%s] nextRunAt set to [%s]",
        this.attrs.name,
        this.attrs._id,
        this.attrs.nextRunAt!.toISOString()
      );
```
which throws an error, because you are calling `toISOString()` on `null`. This causes the process to jump into the `catch` block, where you incorrectly log this `[line 104]`
```ts
      debug(
        "[%s:%s] failed nextRunAt based on interval [%s]",
        this.attrs.name,
        this.attrs._id,
        interval
      );
```
instead of just logging the actual error (it is a debug log after all, it should say exactly what went wrong), and then you attempt to calculate `nextRunAt` again, this time using `humanInterval`. `[line 120]`
```ts
        } else {
          this.attrs.nextRunAt = new Date(
            lastRun.getTime() + (humanInterval(interval) ?? 0)
          );
```
This results in `nextRunAt` being an `Invalid Date {}`. You're probably relying on this, but I believe it is incorrect to be using the `catch` block as pretty much a switch to decide which parser to use. Lastly, in the `finally` block, this whole ordeal is marked as a failure (even though it actually isn't, the job was correctly evaluated to never run again) and `fail` is called with a misleading message. `[line 133]`
```ts
    } finally {
      if (Number.isNaN(this.attrs.nextRunAt!.getTime())) {
        this.attrs.nextRunAt = undefined;
        debug(
          "[%s:%s] failed to calculate nextRunAt due to invalid repeat interval",
          this.attrs.name,
          this.attrs._id
        );
        this.fail(
          "failed to calculate nextRunAt due to invalid repeat interval"
        );
      }
    }
```
The repeat interval is actually valid.

Amusingly enough, incorrectly (IMO) jumping into the catch block actually *saves* the process, because if the catch block logic did not set `nextRunAt` to `Invalid Date`, the `if` clause in the `finally` block would simply cause a fatal error. `[line 134]`
```ts
if (Number.isNaN(this.attrs.nextRunAt!.getTime()))
```
Here `getTime()` is called, once again, on a potentially null property.

**Comment by koresar** [comment]
Mate, this is serious. How do we fix that? Would you crate a PR maybe?
