### ISSUE TITLE
Create queues after start

### ISSUE THREAD

**Issue by GuilhermeCunha** [agenda/agenda#1288]
Is there a way to create a new queue after calling agenda.start ()?

Being more specific, I have a message sending function on instagram, and I would like to create a specific queue for each user that will send, so that I can define a delay in sending messages and better control the sending.

**Comment by koresar** [comment]
This would be a great question in Discussions https://github.com/agenda/agenda/discussions

Quick answer is YES.
Answer: there are no queues in Agenda. Instead, there are "job names". Any new job can have any name it wants. Then any "processor" processes only the jobs of its names.
You don't need to create queues. Just make sure your job has a new name.
See here: https://github.com/agenda/agenda#createjobname-data
