### ISSUE TITLE
Impossible to use this library because of constructor issue

### ISSUE THREAD

**Issue by Mattesackboy** [agenda/agenda#1289]
I can't use this library because when I try to initialize a new instance of Agenda an error saying `Agenda is not a constructor` crashes the app.
Please if you can release a fix asap that would be great! I know that I can add at the end of `dist/index.d.ts`:
```javascript
export default Agenda
```
But in a prod env, this is not so great.
I've tried to `npm i --save git://github.com/agenda/agenda.git#master`, or any other commit, but the `dist` directory, the `index.js` file and other required files are missing on `node_modules/agenda` so I can't fix this problem by myself.
Please help!

@houxinli @RA80533 @simllll @ronenteva @thebestnom

**Comment by thebestnom** [comment]
Umm.. how am I connected 😂
Nevertheless, just use 
```ts
import {agendaInstance} from "agenda";
const agenda:AgendaInstanse = require("agenda");
```
or something like that, the newest agenda release is not 100%
It should work

**Comment by Mattesackboy** [comment]
hahaha sorry man but I saw you in some open issues so I tried to ping you.
By the way I don't use TS nor js modules but I've managed to use Agenda by
```javascript
const Agenda = require('agenda')
const agenda = new Agenda()
```
But doing like that we do not have any type suggestion (the agenda instance will be `any`)

**Comment by thebestnom** [comment]
Of course it will be any, anything in js is any 🤨

**Comment by thebestnom** [comment]
If you use webstorm you can add type suggestion by
```js
// type=AgendaInstanse
```
But I don't remember how to import type using that 😅

**Comment by Mattesackboy** [comment]
By using
```javascript
const { Agenda } = require('agenda')
```
I can see types because VSCode shows me that `Agenda` is a class.
But by using `const { Agenda } = require('agenda')` the app crashes with the `Agenda is not a constructor` error

**Comment by thebestnom** [comment]
Yes, that's a bug in agenda typings
https://stackoverflow.com/a/39694501
This looks like it should work

**Comment by RA80533** [comment]
It appears that the package hasn’t been published since it updated the type declarations. You have the right idea by installing from the master branch.

You’ll need to generate the build files. This is obviously not ideal in a production environment.

**Comment by sirbootoo** [comment]
Currently facing the same issue and I have tried everything here and the I am still getting **Agenda is not a constructor** message

**Comment by koresar** [comment]
Dear all.
Sorry for that.

 If anyone could submit a bug fix PR I'd be very grateful!
Also, please @ mention me. I promise to publish asap.

Also, a unit test would be awesome too.

Thanks!

**Comment by simllll** [comment]
@koresar i think the master is working,i guess only the npm release is missing.

**Comment by koresar** [comment]
@simison found your commit! This line is missing form the NPM https://github.com/agenda/agenda/commit/eabeea812de53fa7af49afed1ed3d4ed6612d230#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567R8

I'll try publishing now.

**Comment by koresar** [comment]
Published as 4.1.2
https://unpkg.com/browse/agenda@4.1.2/
Please test.
Closing this issue. Will reopen if you report that bug still persists.

**Comment by Mattesackboy** [comment]
@koresar Seems working! Thanks!!
The only one thing is that now we need to import `Agenda` by destructuring like this:
```javascript
const { Agenda } = require('agenda')
// and then...
new Agenda()
// or otherwise:
const Agenda = require('agenda').default
```
Instead of doing just:
```javascript
const Agenda = require('agenda')
```
But if this should be the right behavior, everything is perfectly working!

**Comment by RA80533** [comment]
Yes, this is the correct behavior. The new pattern allows module systems to focus on importing only what is necessary (compared to before where everything was imported). The ECMAScript module system (the `import`/`export` syntax), specifically, can take advantage of this natively. If you're still using the older CommonJS module system (e.g., you `require()` your modules), you'll have to use a module bundler such as Webpack or Rollup for this optimization.
