### ISSUE TITLE
Sometimes Jobs are running successfully but not executing the code.

### ISSUE THREAD

**Issue by aftab0292** [agenda/agenda#1303]
I am using the agenda for the last two years. it is an awesome library but recently I noticed weird behavior in running jobs at a scheduled time.

Sometimes scheduled jobs are running successfully but not executing the code and there is no track of any error.

I have also configured the error listeners and handled the retry job case. Below is my agenda configuration.

```js
// External Imports
const Agenda = require('agenda');
const moment = require('moment');

// Custom Imports
const logger = require('../utils/logger.js');

// Agenga Configuaration Options
const connectionOptions = {
    db: {
        address: process.env.AGENDA_DB,
        collection: process.env.AGENDA_COLLECTION,
    },
    useUnifiedTopology: true
};

// Initialize Agenda
const agenda = new Agenda(connectionOptions);

// Configured jobs
require('./audio_call')(agenda);
require('./chat')(agenda);

agenda.on('ready', async () => {
    logger.info(`Initializing agenda jobs`);
    await agenda.start();
})

agenda.on("start", (job) => {
    logger.debug(`Job ${job.attrs.name} starting`);
});
agenda.on("complete", (job) => {
    logger.debug(`Job ${job.attrs.name} finished`);
});
agenda.on("success", (job) => {
    logger.debug(`Job ${job.attrs.name} success`);
});
agenda.on("fail", (err, job) => {
    logger.debug(`@@@@@@@@@@@@@@@@@@@Job ${job.attrs.name} failed with error: ${err.message}`);
    job.attrs.nextRunAt = moment().add(10000, 'milliseconds').toDate(); // retry 10 seconds later
    job.save();
});

agenda.on("error", (err, job) => {
    logger.debug(`@@@@@@@@@@@@@@@@@@@Job ${job.attrs.name} failed with error: ${err.message}`);    
});

const stopAgendaJobs = async () => {
    logger.debug(`Stopping Agenda Jobs`)
    await agenda.stop();
};

process.on("SIGTERM", stopAgendaJobs);
process.on("SIGINT", stopAgendaJobs);

module.exports = agenda;
```

This is my scheduled job code

```js
exports.scheduleMissedCallEvent = async (callerDetails) => {
  logger.debug('scheduling missed call event')
  await agenda.schedule('1 minutes', 'missed_call', callerDetails)
}
```

This is the code that is not executing while the job run successfully(sometimes it run successfully).

```js
agenda.define('missed_call', async (job, done) => {
        try {
            console.log('Running Missed call job');
            const callerDetails = job.attrs.data;
            await db.Astrologers.update({
                is_live: '1'
            }, {
                where: {
                    id: callerDetails.astrologer_id
                }
            })
            await done();
        } catch (err) {
            console.error('err', err);
            await done(err);
        }
    });
```

Please help me with this issue. I am facing this issue in the production project for the last two months.

Is there anything I am doing wrong here?

**Comment by sandeepjangir** [comment]
I am also getting the similar issue, hope this will be fixed soon

**Comment by javonclarke** [comment]
One thing that seems a bit off to me is that you're calling `await done()` inside the promise.

**Comment by koresar** [comment]
You should use either `async` or `done`. See examples here: https://github.com/agenda/agenda#example-usage

Recommendation. Remove `done` argument, remove try-catch block, do not handle errors at all. Use `agenda.on("fail"` to log errors.

**Comment by sidonaldson** [comment]
I am getting this too. Running the demo code on node 15.8.0. If i drop the collection and start fresh it runs and I can see it log every 3s. I can start and stop it maybe two or three times until it starts but stops logging anything. Debugging it shows Agenda is ticking away. I wonder if this is due to my staging site and my localhost using the same DB? Would that cause the issue?

Code below

```
agenda.define('delete old users', async (job) => {
  await console.log('test', job.attrs._id);
});

(async function testJob() {
  await agenda.start();
  await agenda.every('3 seconds', 'delete old users');
})();
```

**Comment by koresar** [comment]
Wow! Great find! I'll close this ticket then. Feel free to ping me if this needs more attention.
