### ISSUE TITLE
 [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.

### ISSUE THREAD

**Issue by t7ls9h** [agenda/agenda#1327]
I am using the latest version.

**Comment by TeamWolfyta** [comment]
Getting this too, Doesn't bother me but the annoying persistent message in console is really ticking me off -,-

**Comment by t7ls9h** [comment]
The Warning message will not show if this project is cloned from github and rebuilt but always show when being install from package manager such as NPM or Yarn. I think you should rebuild your project and republish in yarn and npm.

**Comment by koresar** [comment]
Thanks for the reporting.

You can help removing the warning.

* MongoDB deprecated findOneAndUpdate in favour of [findAndModify](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/).
* findAndModify was introduced in v3.2, Agenda supports v3.4 and higher.
* You can create a PR which **properly** substitutes findOneAndUpdate with findAndModify. Ping me, I'll be happy to review and merge. 

Does that sound like someone can action?

**Comment by koresar** [comment]
The above mentioned #1338 was a wrong fix. It should have replaced findOneAndUpdate usage with findAndModify.
However, it went a different path which now we know was wrong.
Waiting for a new PR form someone. Please.

**Comment by engelgabriel** [comment]
![image](https://user-images.githubusercontent.com/1000217/128571950-b300d8ce-365c-4d85-b0f0-adf3b954709f.png)

**Comment by asportnoy** [comment]
+1, still getting deprecation error after updating. Please fix.

**Comment by koresar** [comment]
@asportnoy could you please help us fixing it?

**Comment by harisvsulaiman** [comment]
@koresar the `findonenadupdate` method doesn't seem to be deprecated in mongo driver 4.1.0 docs.

**Comment by koresar** [comment]
Sounds like I was wrong.
Somehow the proposed PR broke one important unit test.
I spend good a few hours trying to fix it. I couldn't. Sorry, don't have any time on that little issue.
I really hope someone can show the right way, taking into account that my way is surely wrong one.

**Comment by harisvsulaiman** [comment]
@koresar I fixed the test. 
The job was being executed in that test but the test was looking for it to be executed twice. I don't know why it worked before.

I will link the commit here
https://github.com/agenda/agenda/commit/77051dcddb8ef2791d4476780b10eac8ba695d2f#diff-3d864fcfcae7cc47fa275a1fac955f5a2e5f44538c11c65ea1342fbdd1717ed1R920

I would love to hear your thoughts

**Comment by koresar** [comment]
Oh. Right. I'm on the same page with you now. We stop Agenda after the first job execution. But expect it to run twice.
Kinda WOW :)
I looked at this code for hours and couldn't get what's wrong.
Thanks!

**Comment by harisvsulaiman** [comment]
You are not alone. I looked at it for hours too.
 I expected the test to be not faulty since it worked before.

I ran the tests in debug mode to see that was being executive.

**Comment by harisvsulaiman** [comment]
You are not alone. I looked at it for some time too. I expected the test to be not faulty.

Is there something I missed @simison @OmgImAlexis ?

**Comment by koresar** [comment]
@harisvsulaiman I think we should release v4.2.1 with this fix. It's the best time now, before SemVer major.

**Comment by harisvsulaiman** [comment]
@koresar I merged the support for mongo driver 4.0 already.

**Comment by koresar** [comment]
Published as v4.2.1.
Thanks all!
Sorry we kept you waiting.

**Comment by rkreienbuehl** [comment]
I waited for this to be merged, so that we can update the dependencies in our library. Sadly with v4.2.1 als the MongoDB Driver was updated to v4.1, which causes problems with other dependencies.

**Comment by harisvsulaiman** [comment]
@rkreienbuehl Can you elaborate on the issues you faced? 
The versions of mongodb , nodejs , agenda ad other packages that depend on mongodb driver might be helpful.
