### ISSUE TITLE
Adding new job definitions does add them to the collection

### ISSUE THREAD

**Issue by felipesabino** [agenda/agenda#134]
I recently added a new job and realised it was never executed, when I checked the collection in the database I realised that is wasn't there either.

I had my project running with the following job definition

```
agenda.every('23 hours', ['job_A'])
```

and then changed to 

```
agenda.every('23 hours', ['job_A', 'job_B'])
```

which caused `job_B` never to be executed or even be listed among the jobs that needed to run.

**Comment by nwkeeley** [comment]
@felipesabino did you create a task definition for job_B?

This simple example functions as it sounds like you expect

var Agenda = require('Agenda');
var agenda = new Agenda({db: { address: 'localhost:27017/agenda'}});

agenda.define('job_A', function(job, done) {
  console.log('job_A');
  done();
});
agenda.define('job_B', function(job, done) {
  console.log('job_B');
  done();
});

agenda.every('2 seconds', ['job_A', 'job_B']);

agenda.start();

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
