### ISSUE TITLE
Yearly task gets scheduled for February

### ISSUE THREAD

**Issue by ragulka** [agenda/agenda#135]
When I schedule a task using

``` javascript
agenda.every( '0 3 1 1 *', 'doSomethingEvery1stJanuary' );
```

Then the nextRunAt in DB will be something like `2015-02-01 01:00:00.848Z` - which does not make sense. I do NOT want ti to run on the first of February - not even the first time I schedule it. How can I change or workaround this?

**Comment by pursual** [comment]
Is it because JS months are 0 based?

**Comment by OmgImAlexis** [comment]
@pursual that's most likely the issue here. @ragulka if you're still having this issue please let us know and we'll reopen this for you.

**Comment by EvilAlexei** [comment]
@OmgImAlexis I'm still have this issue :)
