### ISSUE TITLE
Incompatibility with TypeScript and mongodb@4.0.0 (driver)

### ISSUE THREAD

**Issue by marvinroger** [agenda/agenda#1355]
Hi,

Thanks for this great lib!

We just migrated our codebase to the mongodb driver v4, and are facing a TypeScript issue with the agenda typings.

mongodb@4.0.0 now ships its own TypeScript types, so it overrides the `@types/mongodb` that agenda depends on, and unfortunately, these typings are incompatible:

```txt
node_modules/agenda/dist/agenda/cancel.d.ts:2:10 - error TS2305: Module '"mongodb"' has no exported member 'FilterQuery'.

2 import { FilterQuery } from "mongodb";
           ~~~~~~~~~~~

node_modules/agenda/dist/agenda/jobs.d.ts:1:10 - error TS2305: Module '"mongodb"' has no exported member 'FilterQuery'.

1 import { FilterQuery } from "mongodb";
           ~~~~~~~~~~~

node_modules/agenda/dist/job/index.d.ts:25:19 - error TS2724: '"/workspace/node_modules/mongodb/mongodb"' has no exported member named 'ObjectID'. Did you mean 'ObjectId'?

25     _id?: mongodb.ObjectID;
                     ~~~~~~~~
```

I *think* that shipping agenda with `@types/mongodb` in dependencies instead of devDependencies would fix the issue, but I am not sure.

**Comment by Asaf-S** [comment]
To my understanding, the issue is larger than the Typescript types.
Agenda is currently incompatible with MongoDB's Node driver in its v4 version, which has breaking changes comparing to v3.
In addition, Agenda's usage of the MongoDB's Node driver in its v3 version produces the following deprecation warning:

```js
(node:7740) [MONGODB DRIVER] DeprecationWarning: collection.findOneAndUpdate option [returnOriginal] is deprecated and will be removed in a later version.
    at emitProcessWarning (proj\node_modules\mongodb\lib\utils.js:547:15)
    at proj\node_modules\mongodb\lib\utils.js:601:9
    at Array.forEach (<anonymous>)
    at Collection.deprecated [as findOneAndUpdate] (proj\node_modules\mongodb\lib\utils.js:594:30)
    at Agenda.module.exports [as _findAndLockNextJob] (proj\node_modules\agenda\lib\agenda\find-and-lock-next-job.js:66:43)
    at jobQueueFilling (proj\node_modules\agenda\lib\utils\process-jobs.js:166:30)
    at Agenda.module.exports (proj\node_modules\agenda\lib\utils\process-jobs.js:32:9)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by harisvsulaiman** [comment]
@marvinroger @Asaf-S There is an ongoing effort to update agenda to use the latest mongo driver and its typings 
see https://github.com/agenda/agenda/pull/1358
