### ISSUE TITLE
Should throw error on schedule of wrong job name 

### ISSUE THREAD

**Issue by gagan-bansal** [agenda/agenda#1356]
If I schedule a job that has not been defined, agenda should throw an error/reject. 
It will be very much helpful.
Or this feature may be there and I am not aware. Please clarify.

**Comment by dereekb** [comment]
There are setups that are distributed, where one Node instance or server is only responsible for queuing things, and another instance/server is for performing tasks. The former doesn't need to have have those jobs defined so it doesn't know which jobs are valid or not.

If you want to avoid scheduling jobs that have not been defined, create an enum/constants that you use to track the names of jobs:

```
export enum AppTask {

  AGENDA_JOB_NAME_A = 'my.job.name',

}

...

// Then use
agenda.schedule(new Date(), AppTask.AGENDA_JOB_NAME_A, ...

```

It is up to you to make sure jobs have valid names or not before they are scheduled.

Alternatively, it does look like Agenda does keep track of all the definitions on this variable:

https://github.com/agenda/agenda/blob/7e78b71b79ae6c6d874e9180954b8b84248e9848/lib/agenda/index.ts#L78

You could look into checking that a job is defined on that object, but I'd use constants or enums first.

**Comment by gagan-bansal** [comment]
@dereekb Thank you for clarification. That solves my issue.
