### ISSUE TITLE
Unique job running multiple times

### ISSUE THREAD

**Issue by VincentdeWit94** [agenda/agenda#1359]
Hi all,

Recently we have been using the agenda package to run all our jobs. Since we require the uniqueness of a job, we have implemented both the unique index on the database and the unique option in agenda when creating a job.

In our code, we have a job that sends a user a certain message when their balance is low. We have set some unique parameters, to make sure that it should not be send the message more than once a day.

Unfortunately, it DOES send multiple times, whenever the job is triggered to be created. It seems that, according to the code (https://github.com/agenda/agenda/blob/5bb293df564d42080acc73416a197eac58e6a2b4/lib/agenda/save-job.ts#L135), when setting the unique parameter, the job will be re-scheduled EVERY time it is triggered with the same unique parameters (because it will do an upsert on the job, instead of ignoring the creation and update). This results in the job being executed multiple times.

Is this intended to work like that? Or did we just found a bug?

Thanks!

**Comment by modernlabrat** [comment]
Why do you need agenda for this? You should just check the balance of the user whenever they use the credits. Say I put $25 credits on your app and buy something - check if it is now under the low amount- if so, check if we have sent out an email today already (basically store two values) - lowBalanceSent as a boolean and lowBalanceDateSent as a Date

If not, send an email

**Comment by koresar** [comment]
I think this is a misunderstanding of how the "unique" works.

From the docs of the "unique" feature:

> Ensure that only one instance of this job exists with the specified properties

It does not give any guaranty on how many times the job is executed.
