### ISSUE TITLE
job with repeatAt always marked as failed

### ISSUE THREAD

**Issue by kbiits** [agenda/agenda#1397]
I'm trying to make a job that run on every tuesday at 19:00, but agenda always detect it as invalid format so the job fails

This is what I do
```javascript
const job = agenda.create('send reminder');
job.schedule('tuesday at 19:00')
job.repeatAt('tuesday at 19:00')
job.save()
```

If I remove job.schedule, the job will run immediately, so I add that, job only processed once at the first time, after that the job was marked as failed due to invalid format of repeatAt

**Comment by simllll** [comment]
You might use this syntax isntead:
```
job.repeatEvery('tuesday at 19:00', {
				timezone: 'Europe/Vienna'
			});
```

e.g. like this:
` 
const weeklyReport = agenda.create('send email report', {to: 'example@example.com'});
await weeklyReport.repeatEvery('1 week').save();
`

you can also try @hokify/agenda which gives you better error messages in case the interval is somehow not parseable.
