### ISSUE TITLE
Graceful Shutdown Doesn't wait for running jobs to complete

### ISSUE THREAD

**Issue by nathan-hellinga** [agenda/agenda#1405]
Using the suggested `agenda.stop()` function to handle graceful shutdowns only seems to do half of what I would expect it to do. Currently it will immediately close out the queue and abort & unlock any running processes. I think this should be changed to allow running jobs to complete (within some limit) instead of aborting them while not starting any new jobs. I think this could utilize the existing "done" property that is passed to job definitions.

This would better support a lot of use cases for agenda especially in a kubernetes or similar environment where handling terminate signals properly is pretty important.  Maybe adding a separate function to handle shutdowns in this way instead of aborting is another option.

My simple use case for this involves running a periodic job that queries the db and sends emails to users matching the query. If the kubernetes pod the job is running on is terminated midway through then some users will not receive the email.

**Comment by nedyalkov** [comment]
The PR https://github.com/agenda/agenda/pull/760 seems to suggest an implementation, but I'm not sure why it wasn't accepted.
