### ISSUE TITLE
runs right at start when defining for 12 hours

### ISSUE THREAD

**Issue by pkdev08** [agenda/agenda#1446]
When running this code, I want the first run to be 12 hours from now and then 12 hours from then and so on, but as soon as I define this, the // Stuff to do gets ran once right away, and then the next one is in 12 hours. Is there any way to make it start 12 hours from now without sending anything at start?

agenda.define(id, async () => {
         // Stuff to do
          });

 await agenda.every('12 hours', id);

**Comment by rat17sri** [comment]
Use { skipImmediate: true } after id

**Comment by pkdev08** [comment]
Tried that but it still sends after a few seconds.

agenda.define(id, async () => {
      // Stuff to do
          });

      await agenda.every('12 hours', id, { skipImmediate: true });

**Comment by rat17sri** [comment]
You will have to pass the data as well before using the options.

 await agenda.every('12 hours', id, data, { skipImmediate: true });

**Comment by pkdev08** [comment]
I was able to make it work, but with my application restarts, if it misses the nextRunAt, then it just never refreshes again and runs. Is there some way to run an init when it launches to re-sync the nextRunAt time if the application is down when the run should be happening

**Comment by rat17sri** [comment]
When I was implementing the agenda, I found that when I restart the server the agenda jobs did not start automatically. I had to restart all the jobs manually. If this is what you are looking for then I can help.

**Comment by pkdev08** [comment]
How would I do that? What if I have a lots of jobs? There's got to be a way to init all the jobs when you restart the application

**Comment by rat17sri** [comment]
```
async function startingPreviousJobs() {
    const jobs = await agenda.jobs();
    jobs.map(async (job) => {
        const jobData = job.attrs;
        await defineAgenda(jobData.name);
    });
};

async function defineAgenda(agendaName) {
    await agenda.define(agendaName, (job, done) => {
        let data = job.attrs.data;
        // to whatever required
        done();
    });
}
```

**Comment by rat17sri** [comment]
You can run this code on server start. So it will find all the jobs from DB and re-define and run them.

**Comment by pkdev08** [comment]
I appreciate it. I will try this and let you know how it goes.

**Comment by pkdev08** [comment]
> ```
> async function startingPreviousJobs() {
>     const jobs = await agenda.jobs();
>     jobs.map(async (job) => {
>         const jobData = job.attrs;
>         await defineAgenda(jobData.name);
>     });
> };
> 
> async function defineAgenda(agendaName) {
>     await agenda.define(agendaName, (job, done) => {
>         let data = job.attrs.data;
>         // to whatever required
>         done();
>     });
> }
> ```

Issue with this is, what if I have tasks that do different things? in the // do whatever required, it could be any different things.

**Comment by derrickpaul-work** [comment]
Yeah, it's a bit tricky to define multiple handler functions. I added a 'handlerName' attribute in the data while defining and used that to call different functions. Sample code:

`
async function startingPreviousJobs() {
    const jobs = await agenda.jobs();
    jobs.map(async (job) => {
        const jobData = job.attrs;
        await defineAgenda(jobData.name);
    });
};

async function defineAgenda(agendaName) {
    await agenda.define(agendaName, (job, done) => {
        let data = job.attrs.data;
        if(data.handlerName === 'firstTask')
           await callFunctionForFirstTask(job);
        else if(data.handlerName === 'secondTask')
           await callFunctionForSecondTask(job);
        done();
    });
}`

**Comment by pkdev08** [comment]
I understand, the library has no other way though to just pick up on previous tasks when restarting? This has to done this way?

**Comment by pkdev08** [comment]
> Yeah, it's a bit tricky to define multiple handler functions. I added a 'handlerName' attribute in the data while defining and used that to call different functions. Sample code:
> 
> ```
> async function startingPreviousJobs() {
>     const jobs = await agenda.jobs();
>     jobs.map(async (job) => {
>         const jobData = job.attrs;
>         await defineAgenda(jobData.name);
>     });
> };
> 
> async function defineAgenda(agendaName) {
>     await agenda.define(agendaName, (job, done) => {
>         let data = job.attrs.data;
>         if(data.handlerName === 'firstTask')
>            await callFunctionForFirstTask(job);
>         else if(data.handlerName === 'secondTask')
>            await callFunctionForSecondTask(job);
>         done();
>     });
> }
> ```

Can you show me an example of how you defined the handler names?
