### ISSUE TITLE
When the .schedule function receives a big payload, to be executed "now", job won't get executed

### ISSUE THREAD

**Issue by MySolSo** [agenda/agenda#1458]
### Reproduction code:

```
const data = {...} // payload with +30Kb size (size might be system dependent)
await agenda.schedule("now", "custom handler", data);
```

### Expected behavior:
Job to be executed even with +100Mb payload sizes.

### Actual behavior:
Job does not get executed at all.

### Workaround:
```
     const job = await agenda.create(name, data);
     job.run()
```

**Comment by harisvsulaiman** [comment]
is there any particular reason why you are sending 30Kb + payload?
