### ISSUE TITLE
Recurring job execute without defined delay

### ISSUE THREAD

**Issue by noamtz** [agenda/agenda#146]
I define a recurring job to execute every 2 seconds but I've noticed that in some point the job executed without 2 seconds delay.

```
agenda.define('printAnalyticsReport', function(job) {
    console.log('[printAnalyticsReport] ['+(new Date()).getTime()+']');
});
agenda.every('2 second', 'printAnalyticsReport');
agenda.start();
```

output:
    [job name] [timestamp]
    [printAnalyticsReport] [1422968332802]
    [printAnalyticsReport] [1422968334806]
    [printAnalyticsReport] [1422968336808]
    [printAnalyticsReport] [1422968336809]   <---- HERE
    [printAnalyticsReport] [1422968338811]

**Comment by felipe-pereira** [comment]
I also observed this problem (v0.6.26 on ubuntu).

**Comment by OmgImAlexis** [comment]
@noamtz quite a bit has changed in the last 2 years, is this still an issue? Is so please let me know and I'll reopen this for you.
