### ISSUE TITLE
If my server or screen are offline/terminated when a job is scheduled the job does not finish

### ISSUE THREAD

**Issue by MagesticChicen** [agenda/agenda#1468]
Say I scheduled a task for 2 hours from now, if the screen running agenda (not mongo) is terminated or the server is offline when the task is supposed to be executed - the task will never finish.

I expected agenda to finish the task the next time it came back online but this never occurred
Any solutions to this?

**Comment by MagesticChicen** [comment]
Found another git issue that has solutions to this

**Comment by jigneshk5** [comment]
can you please share the solution of this
