### ISSUE TITLE
QUESTION: Cancelling a scheduled job

### ISSUE THREAD

**Issue by MagesticChicen** [agenda/agenda#1478]
I want to know how to cancel a specific job that has been scheduled, but only one specific job not all of the jobs with that name.
For example, if I schedule two identical jobs for two separate emails to be sent to two different people im not sure how I would cancel only one of them and how I would identify the specific job I want to be cancelled

Do I have to go into the collection and delete one myself? Or is there a built in function for this using agenda (ideally). 
From what I've seen in the documentation it looks like you can only cancel all jobs with a specific name not just one specific scheduled job 
Thanks!

**Comment by syedkhairi** [comment]
You can use the `cancel` [function](https://github.com/agenda/agenda#cancelmongodb-native-query) `cancel(mongodb-native query)` then query your data attributes:

For example, this will look for a job containing the ID I included in the job’s data attributes, then cancel it;
`let deletedJob = await agenda.cancel({"data._id": mongo.ObjectId(res.task.id) })`

Similar if you’d like to disable a job, for example:
`let disableJob = await agenda.disable({"data._id": mongo.ObjectId(res.task.id) });`

Hope this answers your question.

**Comment by MagesticChicen** [comment]
Yes, I had already found a solution but this is appreciated
