### ISSUE TITLE
No options in .schedule? 

### ISSUE THREAD

**Issue by pralinek** [agenda/agenda#1505]
I would like to schedule a single job at given date / it shouldn't run instantly only once. I would like to add timezone to it but it's impossible. 
-repeatEvery has options but this function is for repeating jobs. 
is there solution for this ?

**Comment by pralinek** [comment]
There will have to be additional logic to have api for this like 9pm will
have to 09:00 / I know that's the way but really?
This should be fixed .schedule means always skip immediately and use
additional options moreover time zones and dates should be able to input an
array.
This way Agenda would be useful as notification scheduler which is not
right now.

**Comment by gangal86** [comment]
> I would like to schedule a single job at given date / it shouldn't run instantly only once. I would like to add timezone to it but it's impossible. -repeatEvery has options but this function is for repeating jobs. is there solution for this ?

```
agenda.define('some long running job', async job => {
	console.log('job is running... ')
	await agenda.cancel({ name: 'some long running job' })
});

(async function () {
	await agenda.start()
	
	await agenda.schedule('Sun Jan 08 2023 12:07:00 GMT+0200', 'some long running job') // set your timezone with job start date, for example GMT+0200

})()
```
