### ISSUE TITLE
Running jobs after restarting node

### ISSUE THREAD

**Issue by miguelvillaresb** [agenda/agenda#1516]
Hi

First of all thanks for the library. I was testing the agenda schedule and I created a few jobs. After restarting node, I have many jobs in mongo but agenda is not running them. Indeed, in the saved jobs on mongo there is no reference to the handler so it seems there is no way to recover all jobs automatically... this is right?

**Comment by bradleysimard** [comment]
thanks @jimbuck, that's a great workaround.
