### ISSUE TITLE
mistake in samle project structure documentation

### ISSUE THREAD

**Issue by zoellner** [agenda/agenda#153]
in the readme.md file:
In the snippet for `lib/controllers/user-controller.js`, the last require is wrong. It should include agenda.js, not worker.js

```
var app = express(),
    User = require('../models/user-model'),
    agenda = require('../worker.js');
```

should be

```
var app = express(),
    User = require('../models/user-model'),
    agenda = require('../agenda.js');
```

**Comment by karan** [comment]
`worker.js` is the same as `agenda.js` in this case - the former simply `require`s the latter.

**Comment by OmgImAlexis** [comment]
@karan is correct on this.
