### ISSUE TITLE
Jobs not running definition.fn is not a function

### ISSUE THREAD

**Issue by xts-bit** [agenda/agenda#1545]
Jobs are not running can anyone please help me with the problem is coming for both agenda and @hokify/agenda package in my Nodejs project i am using mongo atlas using the latest version of the package i can only see this fail reason in my DB "definition.fn is not a function" 

```
import {Agenda} from '@hokify/agenda';
import { MongoDBConnection } from './db.js';
const connection = await MongoDBConnection();
const agenda = new Agenda({ mongo: connection });

const ScheduleUserExpiration = async (DateTime, email) => {
    // DateTime is a Time like const DateTime = new Date() + 1 day etc...
    const expirationTime = await GetTime(DateTime);

    const jobNameTemplate = 'ScheduleUserExpiration-{email}';

    const jobName = jobNameTemplate.replace('{email}', email);
    agenda.define(jobName, { concurrency: 1 }, async (job) => {
        await NotifeeUser(email);
    });

    const jobOptions = {
        maxAttempts: 3,
        backoff: '1s',
    };

    (async function () {
        await agenda.start();
        await agenda.schedule(expirationTime, jobName, jobOptions);
    })();
};
```

**Comment by xts-bit** [comment]
@harisvsulaiman Do you have any idea related to this issue a lot of people are having this problem... When i restart my server the job don't run but The jobs are stored in the DB but they are not being rescheduled once I restart the server, my mongoDB has the data.

**Comment by simllll** [comment]
Don't use dynamic job names. This is not supported and doesn't make sense either.

Use the data prop to pass in values to your function.

Instead of the job name: ScheduleUserExpiration-{email} use just `ScheduleUserExpiration` and pass in the email as attribute. Then only define one method that processes your job (exact same name: ScheduleUserExpiration) data gets the email from the data attribute and does what it should do.

**Comment by xts-bit** [comment]
@simllll Can you please clarify "When i restart my server the job doesn't run but The jobs are stored in the DB but they are not being rescheduled once I restart the server, my mongoDB has the data."  🙏

**Comment by simllll** [comment]
See https://github.com/hokify/agenda/issues/26#issuecomment-1146161378

**Comment by xts-bit** [comment]
@simllll Do you mean like this right?
 

```
agenda.define('ScheduleUserExpiration', { concurrency: 1 }, async (job) => {
    const userEmail = job.attrs.data.email;
    await NotifeeUser(userEmai);
});

(async function () {
    await agenda.start();
})();

const ScheduleUserExpiration = async (DateTime, email) => {
    
    const expirationTime = await GetTime(DateTime);

    const jobData = {
        email: email
    };

    const jobOptions = {
        // Retry the job up to 3 times if it fails.
        maxAttempts: 3,
        // Backoff the job for 1 second after each failure.
        backoff: '1s',
    };

    await agenda.schedule(expirationTime, 'ScheduleUserExpiration', jobData, jobOptions);
};

```

**Comment by xts-bit** [comment]
@simllll Hi, What is the dif between the normal agenda and the agenda by Hokify? Which should I use for the best performance? Also now will my code will work even will the server restart? 

Thanks!

**Comment by simllll** [comment]
There is no difference anymore, as agenda now uses the code base of hokify agenda. Initially it was a fork and rewrite in typescript, I couldn't find time to make a proper release of the original agenda repo though. Will do this one day ;-)

Regarding your question, yes, this should just continue processing your jobs after a restart.

**Comment by xts-bit** [comment]
@simllll But it didn't work, and give me a fail reason that "definition.fn is not a function" please help, Thanks!

**Comment by simllll** [comment]
Simple because it's not a function ;-) 

change 2nd and 3rd paramter:
WRONG:
`agenda.define('ScheduleUserExpiration', { concurrency: 1 }, async (job) => { ... });`
CORRECT:
`agenda.define('ScheduleUserExpiration', async (job) => { ... }, { concurrency: 1 });`

**Comment by xts-bit** [comment]
Like this right? 
```
agenda.define('ScheduleUserExpiration', async (job) => {
     const userEmail = job.attrs.data.email;
    await NotifeeUser(userEmai);
}, { concurrency: 1 });
```

**Comment by xts-bit** [comment]
What's wrong with this code? Now in my MongoDB atlas, it shows, 

```
id
64c91013d343r2c1a746
name
"ScheduleUserExpiration"

data
Object
priority
0
shouldSaveResult
false
type
"normal"
nextRunAt
2023-08-02T03:42:24.876+00:00
lastModifiedBy
null
```
```
agenda.define('ScheduleUserExpiration', async job => {
         const userEmail = job.attrs.data.email;
         await NotifeeUser(userEmail);
	},
	{ priority: 'high', concurrency: 10 }
);
(async function () {
    await agenda.start();
})();
```

**Comment by xts-bit** [comment]
@simllll Also one thing i noticed after refreshing my Mongodb atlas, closing it and pushing some code to the server i found that it fails the job with this error "definition.fn is not a function"

**Comment by simllll** [comment]
With the code snippets only I cannot tell what's wrong. 

- ensure you use @hokify/agenda
- ensure the jobs are defined before calling agenda.start

Or provide a minimal script to reproduce the issue, but I would recommend checking the docs first and check if you have done everything that is mentioned there.

**Comment by xts-bit** [comment]
@simllll My bad i think i didn't used @hokify/agenda but instead use agenda as you said "There is no difference anymore"

**Comment by simllll** [comment]
> @simllll My bad i think i didn't used @hokify/agenda but instead use agenda as you said "There is no difference anymore"

Yeah the 2nd part of the sentence is quite important here: 

> I couldn't find time to make a proper release of the original agenda repo though.

anyways, luckily it works now?

**Comment by xts-bit** [comment]
@simllll The issue has not been fixed yet :(  Still getting that same problem as I mentioned above,

The jobs don't even run but after refreshing mongodb atlas for 2mins, it shows some value in lockedAt..

**Comment by xts-bit** [comment]
@simllll I think maybe its something wrong with the agenda connection because after i refresh the atlas for 2 min and waited another 5-8 mins and check my atlas I found that the jobs runs,

But What's the problem? Like this jobs won't run at the right time instead they will delay...

agenda.js:
```
import { MongoDBConnection } from './db.js';
import {Agenda} from '@hokify/agenda';
const connection = await MongoDBConnection();
const agenda = new Agenda({ mongo: connection });
```
db.js
```
import mongoose from 'mongoose';
import dotenv from 'dotenv';
dotenv.config();

mongoose.set('strictQuery', false);

export const MongoDBConnection = async () => {
    try {
        await mongoose.connect('mymongourl')
        console.log('Connected to database');
        return mongoose.connection;
    } catch (err) {
        console.log('Error connecting to database: ' + err);
    }
};

```

**Comment by xts-bit** [comment]
@simllll Any idea about this?

**Comment by gregg-cbs** [comment]
The reasons for this error is because of the way you will be calling define. Either because Agenda swapped the function parameters around between version 5 and 6 or because you have them the wrong way around.

Here is the explainer:
```ts
// V5 param order
queue.define(name, options, ()=> {})

// V6 param order
queue.define(name, ()=> {}, options)

^ You can see in V6 they swapped options and callback around. So you need to update your define callback param order
```
