### ISSUE TITLE
Close all connections on disconnect

### ISSUE THREAD

**Issue by luismesas** [agenda/agenda#165]
Is there any way to close mongo connections for doing a smooth close instead on a process.exit(0)?

**Comment by igorissen** [comment]
@joeframbach Still no answer since 2 April 2015 .. Is there a way to close properly all connections to MongoDB ?

**Comment by joeframbach** [comment]
From the [nodejs documentation on process.exit](https://nodejs.org/api/process.html#process_event_exit):

> Listener functions must only perform synchronous operations. The Node.js process will exit immediately after calling the 'exit' event listeners causing any additional work still queued in the event loop to be abandoned.

The synchronous example code,

```javascript
process.on('exit', (code) => {
  console.log(`About to exit with code: ${code}`);
});
```

will output correctly when `process.exit(0)` is executed, however, this asynchronous code will not work:

```javascript
process.on('exit', (code) => {
  setTimeout(() => {
    console.log('This will not run');
  }, 0);
});
```

The method to close active mongodb connections is asynchronous. Taken from the agenda readme:

```javascript
function graceful() {
  agenda.stop(function() {
    process.exit(0);
  });
}

process.on('SIGTERM', graceful);
process.on('SIGINT' , graceful);
```

`stop(cb)` needs to do run a mongo query to make sure all running jobs are accounted for. This can not be done synchronously.

(cc @rschmukler to comment or close)

**Comment by igorissen** [comment]
Ok so `agenda.stop(cb)` should properly close all mongo connections after running a last mongo query ? As a user of agenda we only need to call `agenda.stop(cb)` when one of this happen

```js
process.on('SIGTERM', graceful);
process.on('SIGINT' , graceful);
process.on('uncaughtException', graceful);
```

Right ?

**Comment by joeframbach** [comment]
In the original issue, the text is "doing a smooth close instead on a process.exit(0)" but was it supposed to be "doing a smooth close instead **of** a process.exit(0)?" The meaning is a bit different.

The first case, "Can I intercept process.exit(0) and gracefully close connections before exiting?", the answer is no.

The second case, "Can I react to SIGTERM, SIGINT, and uncaughtException, by gracefully closing connections then calling process.exit(0)?", the answer is yes as described above.

**Comment by airbinder** [comment]
On the original question, whether can you close mongo connection. If you look at the test case, it accept mongo connection (`var MongoClient = require('mongodb').MongoClient;`) and later you can `mongo.close()` manually.

I guess this is the only option for now.

Also you can access mongo connection from agenda using '_mdb'.
So, maybe something like:
```js
function gracefulExit(done) {
  return agenda.stop(() => agenda._mdb.close(done));
}
process.on('SIGKILL', gracefulExit((error) => {
  console.log(error);
  process.exit(error);
});
```

Disclaimer, I tried the code above, and it does not work. I just put this here so someone can correct me.

The exact error I got using code above is `MongoError: topology was destroyed`

**Comment by marcusjwhelan** [comment]
How do you cancel all the agenda jobs on close? The reason being is we change job information often and canceling them all every time a crash happens and recreating them is much easier. After I updated node the graceful shutdown I had to cancel jobs no longer works.

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
