### ISSUE TITLE
Missed repeat with Cron

### ISSUE THREAD

**Issue by RaphaelRheault** [agenda/agenda#168]
In my application, the user can schedule a task to be run at a set cron format interval.

When I use it to create a task that will run every minute (\* \* \* \* *), it creates the object correclty, but it didn't run at the nextRunAt time (which is a few seconds after the job was created). The same thing happens when creating a task with any CRON value when it's created a short time before it's planned execution (0 \* \* \* \* when it's already 59). I guess it's because that job didn't get in the process list in time to be executed.

I don't really mind that the task hasn't been run at that point, but the main problem is that the job is never executed again after the missed nextRunAt. It doesn't seem to be a lock problem as seen in other issues and restarting the server doesn't rerun the task, probably because I use CRON format (#157).

Sample of a missed job in mongo:

```
{ "_id" : ObjectId("552bff9ae8c4b69b19378569"), "name" : "schedule 552bff9adb1cc748207cc155", "type" : "single", "priority" : 0, "nextRunAt" : ISODate("2015-04-13T17:41:00.941Z"), "repeatInterval" : "* * * * *", "lastModifiedBy" : null }
```

Extract of the code I use:

```
var AgendaObject = {};
AgendaObject.agenda = new Agenda({
    db: { address: config.db, collection: 'scheduledJobs'},
    processEvery: '5 minutes'
});

AgendaObject.agenda.start();

AgendaObject.add = function(schedule){
    AgendaObject.agenda.define('schedule '+schedule._id, function(job, done) {
        var data = job.attrs.data;
        console.log('Running '+ data.task.name +' at ' + new Date());
        done();
    });

    AgendaObject.agenda.every(schedule.cron, 'schedule'+schedule._id, {task:schedule.task});
};
```

Temporary fix I used:
Changing the processEvery at 10 seconds usually makes it work, but I think that querying the DB every 10s is a bit overkill.

**Comment by qwemaze** [comment]
+1
Same problem.
The job is never executed.
```json
{
    "_id" : ObjectId("57a88908603d114213628655"),
    "name" : "test",
    "type" : "single",
    "data" : null,
    "priority" : 0,
    "nextRunAt" : ISODate("2016-08-08T13:39:10.501Z"),
    "repeatInterval" : "*/5 * * * * *",
    "repeatTimezone" : null,
    "lastModifiedBy" : null
}
```

**Comment by simison** [comment]
Follow ups: https://github.com/agenda/agenda/issues/410
