### ISSUE TITLE
every("anything smaller than processEvery") causes concurrent runs of the same job

### ISSUE THREAD

**Issue by Climax777** [agenda/agenda#169]
When running a job with processEvery set to 5 seconds, and a job running every second, the same job gets run almost instantly. And this happens faster than every 5s ie. more than once a second.

It seems like some race condition maybe.

**Comment by Climax777** [comment]
I get that processEvery should be smaller than the minimum repeat rate, but the behaviour should be a repeat equal to processEvery

**Comment by droppedoncaprica** [comment]
Maybe I'm missing something, why not use `setInterval()`?  I've always seen this library as one that runs jobs in the future, not one that guarantee's that jobs will run on time every few seconds. 

As a side note, there does seem to be issues when creating recurring jobs with super-short intervals.  If you want to take a stab at fixing it, I'd welcome a PR.
