### ISSUE TITLE
Is there any event generated before job is inserted into DB 

### ISSUE THREAD

**Issue by RitaAgarwala** [agenda/agenda#171]
I need to escape certain characters ( $, .) from my message so that mongodb insertion is successful. Currently I am calling this escaping method, before scheduling my jobs. Now as I am doing scheduling at multiple places, so I need to call my method to escape those characters explicitly just before scheduling.

It would have been nice, if there could have been a way to write my escaping method at single place only.

something like ,
```
agenda.on('save', function(job) {
 //do whatever we want before saving to DB
// like escaping special character
}
);
```

instead of
escape-special-character
`agenda.schedule(interval, jobname, data)`

**Comment by simison** [comment]
Closing as stale support ticket.

>Is there any event generated before job is inserted into DB

Nope. :-)
