### ISSUE TITLE
Agenda Tasks not executing.

### ISSUE THREAD

**Issue by JohnRodney** [agenda/agenda#179]
We have a node server that run's importers for a large front end website.  For a while agenda appeared to be working properly, but as we dug into small data inconsistencies in the front end I've noticed that agenda is not behaving as we expected or as was described.  

I have a agenda described like so: 
`agenda.every('* 3 * * *', 'nightly importers');`

Which should run at 3am every morning well on June 18th I have this in my log entries

» 18 Jun 2015 03:00:00.706  2015-06-18 08:00:00.418260+00:00 app worker.1  - - Job nightly importers starting Context

» 18 Jun 2015 06:57:20.279  2015-06-18 11:57:19.988103+00:00 app worker.1  - - Job nightly importers finished successfully Context

» 18 Jun 2015 06:57:20.298  2015-06-18 11:57:20.006626+00:00 app worker.1  - - Job nightly importers starting Context

» 18 Jun 2015 11:18:49.036  2015-06-18 16:18:48.743186+00:00 app worker.1  - - Job nightly importers finished successfully Context

» 18 Jun 2015 11:18:49.043  2015-06-18 16:18:48.750937+00:00 app worker.1  - - Job nightly importers starting Context

It appears to have ran 3 times in a row. Starting again as soon as it finished.  That last task never finished and now my mongo DB entry looks like this.

```
{
        "_id" : ObjectId("556b2393e87780ce46aba30c"),
        "name" : "nightly importers",
        "type" : "single",
        "data" : null,
        "priority" : 0,
        "nextRunAt" : ISODate("2015-06-23T08:00:00.012Z"),
        "repeatInterval" : "* 3 * * *",
        "lastModifiedBy" : null,
        "lockedAt" : ISODate("2015-06-23T15:30:20.311Z"),
        "lastRunAt" : ISODate("2015-06-18T16:18:48.745Z"),
        "lastFinishedAt" : ISODate("2015-06-01T14:07:35.405Z")
}
```

So the data shows it ran on the 18th that is consistent to my log entries, it says it last finished on June 1st? This is not consistent with log entries, and it appears to be Qued up for tonight, but that was the case last night and nothing ran.

My only guess would be that it locked up on that last execution on the 18th and now doesn't run at 3am because it still thinks its running?  But why would it even run 3 times in a row on the 18th?

Can anyone shed some light on this bug?

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
