### ISSUE TITLE
Is it possible to limit the job running in worker process only

### ISSUE THREAD

**Issue by aduyng** [agenda/agenda#186]
In your sample project structure, we can interact with agenda both in server.js and worker.js. There is a potential problem with this approach. If jobs are executed by server.js process, it could cause this process to be busy and thus impact the responsiveness of the web server. Is it possible to only allow agenda to execute jobs in worker process only?

**Comment by wegorich** [comment]
I did something like that for now
```
var jobTypes = config.jobTypes ? config.jobTypes.split(',') : process.env.JOB_TYPES ? process.env.JOB_TYPES.split(',') : [];

jobTypes.forEach(function(type) {
    require('../components/jobs/' + type)(agenda);
});

if(jobTypes.length) {
    logger.info(jobTypes.length);
    logger.info('agenda starts');
    //agenda.start();
}
```

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
