### ISSUE TITLE
How to run agenda as client?

### ISSUE THREAD

**Issue by vijaybarnwal** [agenda/agenda#190]
Hi,

I have two files in which one is used as a client and other is for saving jobs in db which is listed below:

Agenda Client side code which is used for creating/saving jobs into mongodb:
```js
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
agenda.purge(function () {
    console.log("pr");
});
var job = agenda.create('delete old users', {'test': 'test'});
job.repeatEvery('10 seconds');
job.save();
```

Agenda running on serverside with agenda-ui:
```js
var express = require('express');
var Agenda = require('agenda');
var agendaUI = require('agenda-ui');
var app = express();
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
console.log('here inside interval');
app.use('/agenda-ui', agendaUI(agenda, {poll: 1000}));
agenda.jobs({}, function(err, jobs) {
    console.log(jobs);
});
agenda.start();
app.listen(3022);
```
Actually I want to start agenda as independent from creating or defining job where its connecting with db and run the jobs stored inside mongodb.

But after running above piece of code I am not able to run jobs as repeated mode or as scheduler.

Please help.

Thanks,
Vijay

**Comment by nwkeeley** [comment]
No where in the above code do I see that you have defined a task definition for 'delete old users'

**Comment by OmgImAlexis** [comment]
Since this has had no reply in over a year I'm closing it. If this is still an issue please let us know so it can be reopened.
