### ISSUE TITLE
Stop a running job

### ISSUE THREAD

**Issue by pedroandreletra** [agenda/agenda#196]
Hi,

I need to stop a running job. I mean really stopping it, not just removing it from the database (like with remove or cancel).

Long story short, my job is to update things in my database and I need to stop it before deleting those things.

There is a way so I can stop my running jobs? I already tried remove, cancel, and stop+cancel, but my worker keeps running. Do you think that you'll implement this feature soon?

Thanks in advance.

**Comment by wesley-harding** [comment]
Agenda is really just for scheduling and queuing events.  If you need to be able to stop a job part way through, you'll need to implement that in your own code.

**Comment by OmgImAlexis** [comment]
Closing for now as this is over a year old. If you still need help with this please comment and someone can reopen it for you.

**Comment by adityak368** [comment]
It would be great if there was a functionality to stop running jobs and not remove it from database

**Comment by OmgImAlexis** [comment]
@adityak368 if you'd like that as a feature please open a new issue and/or a PR with the changes.

**Comment by derwaldgeist** [comment]
I want to support this feature request. Especially if you have long-running and expensive AI jobs, I'd like to have a proper way to stop a running job without interfering with Agenda's internal job management.

EDIT: Oh, it seems as if cancel() has now been implemented.
