### ISSUE TITLE
Blocker :: One Agenda instance does not pickup/execute jobs added by another instance.

### ISSUE THREAD

**Issue by manusis** [agenda/agenda#198]
We are facing issues while running Agenda as the standalone batch job processor.  We are adding jobs through one agenda instance while trying to retrieve and execute it through other another agenda instance. The second agenda instance does not seem to pick up and execute the jobs.
Both instances connect to the same database. Am I missing something?
### Application A (Version1): Adding jobs through application

``` javascript
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
var Job = agenda.create('greet the world',{time: '30 seconds'});
Job.repeatEvery('20 seconds');
Job.save(function(err){
    if(err) throw err;
    console.log("job saved successfully");
});
```
### Application A (Version2): Adding jobs through application

``` javascript
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
agenda.define('greettheworld',{test: "test",test2:"test2"}, function(job, done) {
    console.log(job.attrs, 'hello world!');
    done();
});
agenda.every('10 seconds', 'greettheworld');
```
### Application B:  Using Agenda in batch job to process jobs. We are expecting this code to pick up and execute jobs

``` javascript
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
agenda.jobs({}, function(err, jobs) {
    console.log(jobs);
});
agenda.on('start', function(job) {
    console.log("Job %s starting", job.attrs.name);
});
agenda.start();
```

**Comment by Climax777** [comment]
Do you have a definition of the `test job`?

**Comment by nwkeeley** [comment]
1. Can you verify the job is in fact written by application A
2. Do you have a task definition for 'test job' in application B

**Comment by manusis** [comment]
Updated the comment. Tried two different versions of Application A. One with definition and one without definition. 

Expecting the start event to trigger in Application B.

**Comment by nwkeeley** [comment]
So this seems to work for me... App1 creates the jobs.... App2 processes the jobs.

App1:
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
var Job = agenda.create('greet the world', {time: '30 seconds'});
Job.repeatEvery('5 seconds');
Job.save(function(err){
    if(err) throw err;
    console.log("job saved successfully");
});

App2:
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});
agenda.define('greet the world', function(job, done) {
  console.log(job.attrs);
  done();
});
agenda.start();

**Comment by manusis** [comment]
Thanks nwkeeley.  Does it mean that App2 need to know and explicitly define all the jobs saved in the database (could be thousands of them)?

I thought Agenda would be fetching jobs periodically and fetch only the ones that are scheduled in next 1 min or so?

**Comment by nwkeeley** [comment]
Well App2 needs to have a task definition for the job type "greet the world"... because it needs to know what to do when that job comes up. If you think about it why would an agenda instance pull a job that it doesn't have a task definition for.... it won't know what to do with it once it processes it.

**Comment by nwkeeley** [comment]
I think you are confusing each job requiring a unique task definition.... unless you really do have thousands of job types.

Example:
```javascript
var Agenda = require('agenda');
var agenda = new Agenda({db: {address: 'localhost:27017/cronjobs'}});

agenda.create('say hello', {name: 'fred'}).repeatEvery('5 seconds').save();
agenda.create('say hello', {name: 'sam'}).repeatEvery('5 seconds').save();
agenda.create('say hello', {name: 'bill'}).repeatEvery('5 seconds').save();
agenda.create('say hello', {name: 'joe'}).repeatEvery('5 seconds').save();

agenda.define('say hello', function(job, done) {
  // sayHello(job.attrs.data.name);
  console.log(job.attrs.data.name)
  done();
});


agenda.start();
```

**Comment by manusis** [comment]
Thanks nwkeeley,

Sorry for the long delay in replying. Your explanation does make sense. We will tweak our approach accordingly. I have a follow up question. I will try to explain the scenario first.

When ever user submits a task for execution e.g. a CSV import, we would like to create a job for that particular import id so that it gets processed by the job processor asynchronously. As soon as the job execution is successful/fails, we remove the job. 

Q.  In case of time out (the scenario when job processor stops/restarts or job execution has problems), will the same job processor or another job processor will pick it up again after the lock period and rerun it?

Thanks,
Rajiv

**Comment by OmgImAlexis** [comment]
Closing for now as this is over a year old. If you still need help with this please comment and someone can reopen it for you.
