### ISSUE TITLE
How can I connect to MongoDB using SSL

### ISSUE THREAD

**Issue by msmolyak** [agenda/agenda#208]
Does Agenda module support SSL connection to MongoDB. My application uses Mongoose, which supports such connections. Can agenda reuse a Mongoose connection? If not, is there another way to connect using SSL?

**Comment by wesley-harding** [comment]
I haven't tested it but I don't see any reason why it wouldn't support SSL. It looks like the options get passed straight through, so you should be able to do something like this:

```
var Agenda = require('Agenda');
var agenda = new Agenda({
    db: {
        address: 'localhost:27017/karmaCompanion',
        collection: 'agendaJobs',
        options: {
            ssl: true
        }
    }
});

```

**Comment by simison** [comment]
Latest Agenda v0.9.1 on npm supports SSL connections now. You can also pass `mongoose.connection` object to Agenda.
