### ISSUE TITLE
Issue Running Jobs In A Clustered Environment

### ISSUE THREAD

**Issue by nialldonnellyfh** [agenda/agenda#231]
Hi, I really like Agenda and am starting to use it in a project. I am having an issue when running Agenda in a clustered node environment.

I would like to create a PR to solve this issue if it is a bug and would like to get your thoughts on it first.

Scenario: [Example Code To Reproduce](https://gist.github.com/nialldonnellyfh/1e826c4340506f660a50)
1. A node master process forking a number of worker processes.
2. Each worker process sets up the Agenda with a single job **testjob**. Each Agenda is set up for a **defaultConcurrency** of 1.
3. The **testjob** Job finishes in _1 second_ and is scheduled to run every _2 seconds_.
4. I expect that the **testjob** Job should execute every _2 seconds_.

[Example Output](https://gist.github.com/nialldonnellyfh/93fbb3420236ad7394e8)

From the output above, you can see process _6713_ starts executing the job normally every 2 seconds as expected. However, at [this](https://gist.github.com/nialldonnellyfh/93fbb3420236ad7394e8#file-example-output-of-test-job-L10-L11) point, both processes end up executing the job at the exact same time.

I am debugging the issue at the moment to find a solution and would be very interested in any comments that you have on the above scenario that I have missed.

I will update this ticket with any issues I can find from debugging.

Kind Regards
Niall Donnelly

**Comment by nialldonnellyfh** [comment]
The issue seems to be related to more than a clustered environment.

I have added a unit test (https://github.com/nialldonnellyfh/agenda/tree/fix_concurrency_bug) to test concurrency that can reproduce the bug.

From debugging the code, it seems that the bug may occur between a Job saving and a deferred job executing on a timeout.

**Comment by lfryc** [comment]
I've updated original test case with inter-process messages that makes master to print current number of concurrent job executions as well as the number of miliseconds from the start of last job execution, and after few seconds we are getting interesting output:

````
#testjob Finished Mon Dec 07 2015 10:40:18 GMT+0100 (CET) 59786
#testjob Starting Mon Dec 07 2015 10:40:18 GMT+0100 (CET) 59786
Last job started before 2005 ms
Concurrent job executions: 1
#testjob Finished Mon Dec 07 2015 10:40:20 GMT+0100 (CET) 59786
#testjob Starting Mon Dec 07 2015 10:40:20 GMT+0100 (CET) 59786
Last job started before 1522 ms
Concurrent job executions: 1
#testjob Finished Mon Dec 07 2015 10:40:21 GMT+0100 (CET) 59786
#testjob Starting Mon Dec 07 2015 10:40:21 GMT+0100 (CET) 59786
Last job started before 1509 ms
Concurrent job executions: 1
#testjob Finished Mon Dec 07 2015 10:40:23 GMT+0100 (CET) 59786
#testjob Starting Mon Dec 07 2015 10:40:23 GMT+0100 (CET) 59786
Last job started before 1507 ms
Concurrent job executions: 1
#testjob Starting Mon Dec 07 2015 10:40:23 GMT+0100 (CET) 59787
Last job started before 494 ms
Concurrent job executions: 2
#testjob Finished Mon Dec 07 2015 10:40:24 GMT+0100 (CET) 59786
#testjob Starting Mon Dec 07 2015 10:40:24 GMT+0100 (CET) 59786
Last job started before 1011 ms
Concurrent job executions: 2
````

Note that the jobs should start at least ~2 seconds from the previous one, and there should not be two jobs executed at the same time (the job ends after 1.5 sec.).

Here is the test case and its output: https://gist.github.com/lfryc/c06fb4996234294617b6

**Comment by OmgImAlexis** [comment]
Please update to version 2.0 and let us know if the issue is still there.
