### ISSUE TITLE
Unique efficiency

### ISSUE THREAD

**Issue by gioenn** [agenda/agenda#232]
Hi,
I'm developing an application in which I have only one job definition and many instances of it, let's say one per user. I also need to delete a user's job or update the schedule date of a user's job if the user requests it.

I understood that the best practice for this kind of use case is to use the _unique_ procedure. 
So for updating a user's job I can do something like:

``` javascript
job.unique({'data.userId': '123', nextRunAt(date)});
job.save();
```

And for deleting a user's job:

``` javascript
agenda.cancel({'data.userId': '123'}, function(err, numRemoved) {});
```

As far as I understood agenda performs, for these operations, a mongo query that is relatively slow (`O(n)`) because `data.userId` is not indexed. 

To make this operations faster my team proposed three solutions:
1) create a map stored in our db where the key is the user id and the value is the mongo job id (`_id`) and then we can retrieve the jobs via `_id` (indexed). This solution needs two different queries in two separate dbs.
2) we manually set the job `_id` equals to the user id (that is of course unique by definition) before saving it and then we can retrieve the jobs via `_id`.
3) add an index to `data.userId` or add an index configuration option in agenda.

What do you think about these solutions? What do you suggest?

Thanks in advance
Giovanni

**Comment by saveman71** [comment]
I'm just passing by, but from what I can see, the best solution would be the last one because, in my opinion:
- The first one is harder to implement (and that's an additional call somewhere)
- I don't even know if the second solution is possible (if it is, it's just plain ugly).

**Comment by emilianobonassi** [comment]
Interesting question, I have the same issue.
IMO, I would not modify agenda model so the first or the third solution are ok. For the latter, I would choose index configuration instead of adding an index for a custom field.

**Comment by hughstephens** [comment]
We use option 3. Have several thousand active jobs processed at any one time. Works fine. Just index the hell out of the agenda collection - you aren't going to "break" anything in the module by _adding_ indexes that you use for other operations.

**Comment by code2be** [comment]
Just confirming usage of third option, without it had Mongo eating up the CPU.

Thank You.

**Comment by simison** [comment]
Change to readme was merged. Thanks everyone!
