### ISSUE TITLE
How to emits failure events to notify?

### ISSUE THREAD

**Issue by SantoshSKhavekar** [agenda/agenda#236]
Hi,

I just wanted to know that how to emits the failure jobs due to reasons like failure in API call or Memory leakage issues or DB connection failure etc for to get notification.

Any help would be appreciate on same.

**Comment by sraRas** [comment]
Hi, 

I ran into the same issue. Sometimes DB connection fails but there's no option to emit theese events. Before the native driver for MongoDB was used (I think with the latest release) I was able to handle such issues (MongoSkin didn't crash in case of connection failure) but now with the native driver it agenda crashes immediatly if no DB connection is available.

**Comment by SantoshSKhavekar** [comment]
Thank you SraRas for your reply on this.I find out "Agenda.fail" event but it will emit only when job gets failed.In case job failed due to some other reasons as a mentioned in earlier this agenda.fail will not emits.
