### ISSUE TITLE
Expose MongoDB connection object

### ISSUE THREAD

**Issue by richsilv** [agenda/agenda#237]
An agenda.js instance has a key, `_mdb`, which contains the MongoDB connection object.  I need to use this to close and reopen the connection for testing purposes (otherwise you can't stop and restart your server cleanly).

Can we have a method to return this mongo connection which isn't private and liable to change?

Please let me know if you would like me to PR for this.

**Comment by rschmukler** [comment]
Sounds good. Since agenda hopefully will get db adapters it should be something more generic than getMongo etc. maybe getDbClient or something.

**Comment by richsilv** [comment]
:+1:

**Comment by mdibaiee** [comment]
@richsliv: I'm trying to write tests for a project using `agenda`, I tried closing `agenda` using this:

```
await promisify(agenda.cancel)({});
await promisify(agenda.stop)();
await promisify(agenda._mdb.close)();
```
The process is successful, but I can't start Agenda again, neither `ready` nor `error` events don't emit.
If you have any experience doing this, I would appreciate any help. Thanks.

**Comment by simison** [comment]
Method for closing: https://github.com/agenda/agenda/pull/450

**Comment by leonardlin** [comment]
Has been implemented: https://github.com/agenda/agenda/pull/450
