### ISSUE TITLE
install failed with error MSB3428

### ISSUE THREAD

**Issue by zduantao** [agenda/agenda#263]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\Users\zhouyu\node_modules\kerberos\build\binding.s
ln]

So must I install the SDK...?

**Comment by jdiamond** [comment]
The kerberos package is an optional dependency of the mongodb package that agenda depends on. It's OK if kerberos fails to build as you're probably not using it. So if that's you're only build error, you should be able to use agenda just fine.
