### ISSUE TITLE
Agenda UI

### ISSUE THREAD

**Issue by nvartolomei** [agenda/agenda#273]
Is there anything better than agenda-ui project?

What do you use for monitoring/see how many jobs are pending / finished and other stats?

**Comment by joeframbach** [comment]
Hi! I've just published my first npm module. It's a new UI for Agenda. Take a look! https://github.com/joeframbach/agendash

**Comment by loris** [comment]
@joeframbach super good job already! would love to see batch delete/requeue though :)

**Comment by joeframbach** [comment]
I've added the ability to select multiple jobs to pull into the details pane at once. Batch api requests are still to-do.

**Comment by joeframbach** [comment]
Agendash 0.0.5 now has batch requeue/delete. Requeue is executed in serial in the backend. Delete is executed as an `$in` delete query.

**Comment by flashbag** [comment]
Very useful interface! Thx)

**Comment by BrainsoftLtd** [comment]
+1

**Comment by zysam** [comment]
+1, and I use koa.
