### ISSUE TITLE
`unique(properties, [options])` not working as expected

### ISSUE THREAD

**Issue by teckays** [agenda/agenda#283]
Hi there, I'm having a problem using your library. I have one worker running every day (for testing I ran it every 10 seconds) which calls the function bellow. The reason I'm doing this is in order to pick up newly registered accounts. This is the function:

```
data = { accountId: _id }
properties = { 'data.accountId': _id, nextRunAt: 'monday at 7am' }
agenda.create('jobName', data).unique(properties).schedule(schedule).save(function(error) {
    if (error) console.log(error)
});
```

however in the database, every time my supervisor job runs it creates new entries.

```
{
  "_id": ObjectId("56b8eb9bf6d752dfe7840a5d"),
  "data": {
    "accountId": ObjectId("56b88633982cbb3152b6e930")
  },
  "name": "jobName",
  "nextRunAt": new Date(1455512400975),
  "type": "normal",
  "priority": 0,
  "lastModifiedBy": null
}
```

```
{
  "_id": ObjectId("56b8eba5f6d752dfe7840a5e"),
  "data": {
    "accountId": ObjectId("56b88633982cbb3152b6e930")
  },
  "name": "jobName",
  "nextRunAt": new Date(1455512400979),
  "type": "normal",
  "priority": 0,
  "lastModifiedBy": null
}
```

The converted timestamps are:
1. `1455512400975` -> `2016-02-15 07:00:00+200`
2. `1455512400979` -> `2016-02-15 07:00:00+200`

as you can see, only the last digit from timestamp is different `+4ms` even if I'm always passing in `monday at 7am` to `schedule(time)` and because the timestamps are different there are new entries added every time (I suppose). 

So what would be the right way to handle such situations?

**Comment by RubenCordeiro** [comment]
I am having the same issue, did you manage to find a solution @teckays ?

**Comment by loris** [comment]
@teckays why do you include `nextRunAt` in your unique constraints? You want 1 recurring job per accountId right? then change it this way:
```
data = { accountId: _id };
agenda
  .create('jobName', data)
  .unique({'data.accountId': _id})
  .schedule('monday at 7am')
  .save(function(error) {
    if (error) console.log(error)
  });
```

**Comment by simison** [comment]
Closing as stale, feel free to re-open or open a new issue if still a problem.
