### ISSUE TITLE
Would love to see support for PostgreSQL

### ISSUE THREAD

**Issue by lewisdawson** [agenda/agenda#291]
I'd be happy enough if the database logic was moved to an ORM-based architecture so support for a wider set of databases could be integrated easily.

**Comment by hugocar** [comment]
Please look at the answer to a similar question : https://github.com/rschmukler/agenda/issues/309

**Comment by simison** [comment]
Follow ups ➡️ #18 Database adapters

All help appreciated! #414 Maintainers needed 🍻
