### ISSUE TITLE
Create job instance for every repetition

### ISSUE THREAD

**Issue by kbrandwijk** [agenda/agenda#292]
When a job definition is scheduled using every(...), there is only one entry in the database for that job. Since the execution result can differ for every run, and also since it would be nice to see that history when using one of the visualizers (agendash in my case), I think it's best to create a new entry in the database every time a repeating job is run. This allows you to save failure reason and execution time for every time the job is executed.

**Comment by flashbag** [comment]
I think the better way to log your job work using some logger (I'm using [bunyan)](https://github.com/trentm/node-bunyan) and then you will able to see history of every different job execution.

**Comment by BrainsoftLtd** [comment]
I don't see how that solution applies when using a GUI like agendash.

**Comment by boazjohn** [comment]
Found a hack to do this. This is not handling all the conditions, could make it better. 
```
// Initialialize jobs
agenda.on('ready', function() {
    agenda.schedule('10 seconds', 'job_name', { requestId: getRequestId(), cronInterval: '10 seconds' });
    agenda.start();
});

// Calling the same job on complete
agenda.on('complete', function(job) {
    agenda.schedule(job.attrs.data.cronInterval || '10 seconds', job.attrs.name, { requestId: getRequestId(), cronInterval: job.attrs.data.cronInterval || '10 seconds' });
});
```

**Comment by elyas-bhy** [comment]
Another alternative would be having a child job which executes your logic, and a parent job that you would schedule however you wish, which fires off the child job.  

This way, you can start or stop your recurring parent job as needed, and still have separate execution instances for your child jobs. The added benefit of this solution is that it is completely compatible with the current code base as well as the UI tools.

**Comment by BrainsoftLtd** [comment]
That sounds like a good idea. I'll try it out, and  I'll see if I can adapt the code base to do this automagically for me.

**Comment by robblovell** [comment]
The problem with the solution that @boazjohn puts forward is that on restart more than one job ends up being scheduled. Over time, each time the code is restarted another instance of the scheduled item gets put in place.

One thing that might address this is to add a job method "record" that would enter a line in the database corresponding to either the failed or successful job.
```
job.record(failReason, completionResults, cb) 
```
If failReason is not null it saves the job as a new entry in the database in the failed state, if completionResults is not null, a new entry in the database is saved as complete.

**Comment by fzondlo** [comment]
Would this feature solve your pain point?

https://github.com/agenda/agenda/issues/645

It would allow for storing each job's history and then recall using agenda dash UI.
