### ISSUE TITLE
Support Redis

### ISSUE THREAD

**Issue by foobar450** [agenda/agenda#309]
What is the current position on supporting Redis as a backend for Agenda?
There are several issues discussing it (#184, #188, #18 and #206 indirectly), but no clear indications on whether it is planned or not.

**Comment by loris** [comment]
@rschmukler should share his opinion here. But if it were up to me, imo it does not make any sense to support Redis :)
- It would bloat the whole codebase
- It would require a massive rewrite anyway
- There is already [kue](https://github.com/Automattic/kue) available, which is basically agenda for redis (well, I guess it is the other way around, agenda is kue for mongodb)

**Comment by rschmukler** [comment]
@foobar450 this is something that would only make sense with a rewrite. Ultimately I'd love to re-write agenda in ES6 with storage engines as plugins...
```js
import { Agenda } from 'agenda';
import { AgendaRedis } from 'agenda-redis';
import { Redis } from 'redis';
 
var redis = new Redis('localhost:6379');
var agendaRedis = new AgendaRedis(redis);
var agenda = new Agenda({ storage: agendaRedis });
```

That being said, as @loris mentioned, it's a lot of work to implement storage plugins in the code base, and the current implementation relies heavily on mongo. To break it out would be almost as much work as the rewrite itself.

Sorry, I wish I had a better answer for this.

**Comment by thomasmodeneis** [comment]
+1.

@rschmukler Any ideas when do you guys plan to get this one sorted ?

Cheers.

**Comment by jdnichollsc** [comment]
+1 for postgres!

**Comment by Shawyeok** [comment]
+1 for abstract storage layer, then `agenda` will able to support any database, even filesystem, just like [express-session-store](https://github.com/expressjs/session#session-store-implementation)!

**Comment by iagomelanias** [comment]
+1 for Redis!

**Comment by simison** [comment]
Follow ups ➡️ #18 Database adapters

All help appreciated! #414 Maintainers needed 🍻
