### ISSUE TITLE
Moment Timezone 0.3.1 was already loaded with data from 2015a

### ISSUE THREAD

**Issue by deecewan** [agenda/agenda#312]
I noticed this in my logs, and found a few Travis CI builds included this.

Any way to fix this?

Edit:  Anyone else coming here please just thumbs up this post.  No need to clog up the post with +1's

**Comment by loris** [comment]
Actually, this notice is output by `moment-timezone`, author is [already aware and working on a fix](https://github.com/moment/moment-timezone/issues/231#issuecomment-192046642). So, as agenda users, we just need to ignore it at the moment :)

**Comment by niftylettuce** [comment]
still not fixed?

**Comment by jdnichollsc** [comment]
I need the latest version of moment-timezone to use moment.tz.guess();

Any fix? thanks!

**Comment by niftylettuce** [comment]
Can you please re-open this issue until it is resolved in the other repo?  It's a core dep.

**Comment by jdnichollsc** [comment]
+1

**Comment by adamrabie** [comment]
+1

**Comment by dimd13** [comment]
+1

**Comment by huhamhire** [comment]
+1

**Comment by serganus** [comment]
+1

**Comment by ptitdje45** [comment]
+1

**Comment by edwardbrosens** [comment]
+1

**Comment by nikolajordanovski** [comment]
+1

**Comment by Radiergummi** [comment]
This has been fixed in `moment-timezone@0.5.11`: https://github.com/moment/moment-timezone/issues/231#issuecomment-269029712  
Would you mind updating agenda's dependencies?

**Comment by simison** [comment]
`moment-timezone` has been updated: https://github.com/agenda/agenda/blob/master/package.json#L34
