### ISSUE TITLE
Some jobs are not running in Heroku

### ISSUE THREAD

**Issue by FindBoat** [agenda/agenda#314]
I build my app using Heroku hobby Dynos (so there should be no sleep time). The app keeps generating agenda jobs once in a while. However, I notice that roughly half of the jobs don't get running, like this one:

```
{
    "_id": {
        "$oid": "5716d9fe2c6ce52800a765f1"
    },
    "name": "5716d9f02c6ce52800a765ef",
    "data": null,
    "type": "normal",
    "priority": 0,
    "nextRunAt": {
        "$date": "2016-04-20T01:25:10.186Z"
    },
    "lastModifiedBy": null,
    "lockedAt": {
        "$date": "2016-04-20T08:26:25.754Z"
    }
}
```

So what would be the best way to debug this issue?

**Comment by loris** [comment]
It looks like your job gets started (hence gets locked by agenda) but you don’t end it.
Do you properly call the `done` callback in your job definition like in the README example:
```
agenda.define('send email report', {priority: 'high', concurrency: 10}, function(job, done) {
  var data = job.attrs.data;
  emailClient.send({
    to: data.to,
    from: 'example@example.com',
    subject: 'Email Report',
    body: '...'
  }, done);
});
```
Anyway, to get better help, some code sample will help

**Comment by scopsy** [comment]
Having the same issue running 2 servers clustered with PM2. Seems like its very random. 95% of my tasks run with no problem, buy sometimes a gew tasks got into an endless locking loop. Usually after server restart and clearing the lock, it works as it should...
