### ISSUE TITLE
Time to publish a new version?

### ISSUE THREAD

**Issue by alexkwolfe** [agenda/agenda#318]
I see you have some bug fixes and it's been a while since you published a new version to NPM. Is now a good time? I ask because it looks like there's a bug fix in there that's impacting me. Thanks!

**Comment by jotapdiez** [comment]
+1 Agenda works for me only cloning this repo, I can't make it works with the NPM package.

**Comment by jakeorr** [comment]
Juan, did you know that you can use github urls in your package.json?
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by simison** [comment]
Latest v0.9.1 in NPM should have all the goodies in! :-)
