### ISSUE TITLE
TypeError: require(...).native is not a function

### ISSUE THREAD

**Issue by jotapdiez** [agenda/agenda#319]
I have a js that initiates and configures Agenda.
`var Agenda = require('./agenda/agenda.js');  //Because with npm module agenda not work`
`var agenda = new Agenda({
    db: { address: 'localhost:27017/cms'},
    processEvery: '1 second'
});`

`agenda.maxConcurrency(3);`
`agenda.defaultConcurrency(2);`

`agenda.define('holla', {}, function(job, done) {`
`console.log('Hola %s!!', job.attrs.data.someId);`
`setTimeout(function (){
        console.log('finished    (%s)', job.attrs.data.someId);
        done();
    }, 150);`
`});`

`agenda.on('ready', function() {
    agenda.start();
});`

`agenda.on('error', function(err) {
  console.log('agenda error', err);
});`

`module.exports = agenda;`

When I include this js on my JSX (React) to use Agenda with the UI, the Firefox console throws this error:

> TypeError: require(...).native is not a function

Jumping to the line who throws the exception (in bold):

> var inherits = require('util').inherits
>   , f = require('util').format
>   , bindToCurrentDomain = require('../connection/utils').bindToCurrentDomain
>   , EventEmitter = require('events').EventEmitter
>   , Pool = require('../connection/pool')
>   , b = require('bson')
>   , crypto = require('crypto')
>   , Query = require('../connection/commands').Query
>   , MongoError = require('../error')
>   , ReadPreference = require('./read_preference')
>   , BasicCursor = require('../cursor')
>   , CommandResult = require('./command_result')
>   , getSingleProperty = require('../connection/utils').getSingleProperty
>   , getProperty = require('../connection/utils').getProperty
>   , debugOptions = require('../connection/utils').debugOptions
>   **, BSON = require('bson').native().BSON**
>   , PreTwoSixWireProtocolSupport = require('../wireprotocol/2_4_support')
>   , TwoSixWireProtocolSupport = require('../wireprotocol/2_6_support')
>   , ThreeTwoWireProtocolSupport = require('../wireprotocol/3_2_support')
>   , Session = require('./session')
>   , Logger = require('../connection/logger')
>   , MongoCR = require('../auth/mongocr')
>   , X509 = require('../auth/x509')
>   , Plain = require('../auth/plain')
>   , GSSAPI = require('../auth/gssapi')
>   , SSPI = require('../auth/sspi')
>   , ScramSHA1 = require('../auth/scram');

I only found that on mongodb-core module inside this JS files.

> node_modules/mongodb-core/lib/topologies/server.js (lines 18 and 862)
> node_modules/mongodb-core/lib/topologies/mongos.js (lines 9 and 459)
> node_modules/mongodb-core/lib/topologies/replset.js (lines 15 and 291)

Somebody can help me?

Thanks in advance

**Comment by sylvanash** [comment]
I'm also encountering the same error after transpiling my ES6 code to ES5...no one has any ideas on how to resolve this?

**Comment by OmgImAlexis** [comment]
@jotapdiez please use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) for large amounts of code.

From what you said it sounds like you're trying to run agenda in a browser not node, correct?
