### ISSUE TITLE
Jobs with a defined timezone

### ISSUE THREAD

**Issue by xlarsx** [agenda/agenda#322]
Hi, is it possible to schedule a job using a expression like 'tomorrow at 8' using a concrete timezone?

As far as I can see in the source code, one possible option is to set the ENV TZ to a concrete timezone so all the validations are set to that time zone, is there a better way to do it? this option is error prone?

Thank you very much for your support, greetings,

**Comment by jakeorr** [comment]
Hi xlarsx, it is not currently possible to include a timezone in a date.js string. Agenda uses this useful module to handle those type of strings https://github.com/matthewmueller/date.

Interesting idea on the TZ environment variable. I didn't know there was such a thing, thanks for bringing it to my attention. Unfortunately a little googling uncovers [https://github.com/nodejs/node-v0.x-archive/issues/3286](some) [issues](https://github.com/nodejs/node/issues/3449) that make it look unusable for this purpose.

I agree that this would be a useful feature though. A PR to [date.js](https://github.com/matthewmueller/date) might be a good place to start if you want to work on it.

**Comment by simison** [comment]
@xlarsx feel free to open if your question wasn't answered yet. :-)
