### ISSUE TITLE
Unfinished non-interval jobs not getting picked up on next startup

### ISSUE THREAD

**Issue by cberigan** [agenda/agenda#324]
This is in regards to jobs that are created using `agenda.now`.

I think agenda should be able to pick up these jobs that were not finished due to abrupt shut downs. I didn't see it anywhere in the code that does this.  What I did find is the logic in `Agenda.prototype._findAndLockNextJob` that only picks up jobs that have a `nextRunAt` property.  I believe agenda should pick up jobs that were not finished and don't have `nextRunAt`. I'd like to hear some input on this or point me in the right direction if this functionality is available. Below is an idea I had to update the `findAndModify` function within `_findAndLockNextJob`:

```

this._collection.findAndModify(
  {
    $or: [
      {name: jobName, lockedAt: null, nextRunAt: null, lastFinishedAt: {$exists: false}, disabled: { $ne: true }},
      {name: jobName, lockedAt: {$lte: lockDeadline}, nextRunAt: null, lastFinishedAt: {$exists: false}, disabled: { $ne: true }},
      {name: jobName, lockedAt: null, nextRunAt: {$lte: this._nextScanAt}, disabled: { $ne: true }},
      {name: jobName, lockedAt: {$exists: false}, nextRunAt: {$lte: this._nextScanAt}, disabled: { $ne: true }},
      {name: jobName, lockedAt: {$lte: lockDeadline}, nextRunAt: {$lte: this._nextScanAt}, disabled: { $ne: true }}
    ]
  },
  {'priority': -1},  // sort
  {$set: {lockedAt: now}},  // Doc
  {'new': true},  // options
  function (err, result) {
    var job;
    if (!err && result.value) {
      job = createJob(self, result.value);
    }
    cb(err, job);
  }
);
```

**Comment by ashutosh-akss** [comment]
Same problem here, not working for me too.

**Comment by mirkods** [comment]
any news about?

**Comment by danibjor** [comment]
I added this to my `worker.js` - and after that, the problems about jobs being in an inconsistent state due to docker image restart was resolved.

```
function graceful() {
    console.log("shutting down...");
    agenda.stop(function() {
        console.log("agenda stopped and jobs  unlocked.");
        process.exit(0);
    });
}

process.on("SIGTERM", graceful);
process.on("SIGINT", graceful);
```

**Comment by cberigan** [comment]
Are you sure this works for non-repeating jobs (Created by agenda.now)?
I've done this too but the "now" jobs don't get picked up again.

**Comment by danibjor** [comment]
No. not sure. My environment runs repeating jobs, and it works there. 

But from reading the code, `stop()` runs `_unlockJobs()` witch then sets `lockedAt: null`.

What does the job look like in MongoDB?

**Comment by cberigan** [comment]
You are right that agenda unlocks them properly, but this is not that kind of issue. The reason why jobs created by  `agenda.now` are not being picked up is because agenda doesn't look for them. More specifically, it does not query for jobs that DO NOT have a `nextRunAt` property. To answer your question, jobs created using `agenda.now` do not have a `nextRunAt` property, which makes them slightly different than normal repeating jobs. The snippet of code I put up there is an off-the-cuff solution to the problem. I wanted to get some other opinions from those more knowledgeable about this project.

**Comment by simison** [comment]
Closing this, follow ups https://github.com/agenda/agenda/issues/324

**Comment by simison** [comment]
Closing this, follow ups https://github.com/agenda/agenda/issues/338

**Comment by lushc** [comment]
I think this related to #410 as well.
