### ISSUE TITLE
Error handling in agenda

### ISSUE THREAD

**Issue by seanlindo** [agenda/agenda#327]
Hi all,

I've purposefully included an explicit error in my code, calling `userStore.getUsersWithAccount()` as opposed to the actual function, `userStore.getUsersWithAccounts()`. 

I expected to see some sort of failure or a process exit, but the application hangs instead. Is there a way to catch these types of errors?

**Comment by manuel-di-iorio** [comment]
+1
Instead to catch the errors (or let the process crash), agenda logs them in the job record, not really helpful

**Comment by jakeorr** [comment]
You can hook a handler up to the fail event for the job and do whatever you like with the error: https://github.com/rschmukler/agenda#job-queue-events

**Comment by OmgImAlexis** [comment]
Typos should be caught by tests and linting. This should be closed as it's not really an issue with agenda.

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
