### ISSUE TITLE
Problems on Jobs after server restart

### ISSUE THREAD

**Issue by nunosilvamourao** [agenda/agenda#336]
Hi,

I've been reading all the existing Issues regarding the server restart methods but I wasn't able to define a valid solution for my case.

On my app, each user can define when their tables are updated, and this definition will lead to an Agenda Job (dynamic, as it will be different for each user, the schedule time for example can be 10 seconds, 1 minute, 1 hour, 1 day, 1 week, etc)

So, the problem is:
The Jobs are being saved on the Mongo collection, with the correct definitions and the scheduled and nextRun times also correct, the Jobs run and update when the server is up, but if for any reason the server restarts Agenda does not run them anymore, although they being on Mongo and not Locked.

What should be the solution in this case?

Thanks in advance!

**Comment by dff3bc** [comment]
Same problem here. Jobs are created in an express.post('/url') function and they run when they are created. However, when the server restarts, they no longer run. The jobs exist in the database and {locked:null} but still nothing. Is there a way to kick off all jobs in the database or is this not going to be a viable option?

**Comment by simison** [comment]
Follow ups: https://github.com/agenda/agenda/issues/410
