### ISSUE TITLE
Job runs immediately when the app starts

### ISSUE THREAD

**Issue by ephigabay** [agenda/agenda#344]
I'm scheduling a job using this code:

> var job = global.agenda.create('send happy hour notification', {});
> job.repeatEvery('0 21 \* \* *');
> job.unique({});
> job.save();

So the job should run everyday at 21:00.
But every time I run my app it runs this job.. 
Am I doing something wrong?

**Comment by jakeorr** [comment]
If you run a `job.computeNextRunAt();` after setting the repeat interval, it should set the next run time correctly.

**Comment by ephigabay** [comment]
@jakeorr  Thanks! Seems like it works..

**Comment by bvallelunga** [comment]
@jakeorr Shouldn't this be the default or at least an option when creating a job?

**Comment by simison** [comment]
Follow ups https://github.com/agenda/agenda/issues/422
