### ISSUE TITLE
Get individual job by ID? 

### ISSUE THREAD

**Issue by jcfergus** [agenda/agenda#346]
I've been fighting with this for a while now - is there an easy way to get a handle to an individual job, by _id?  

I've tried:

```
            var objId = new ObjectId( jobIdentifier );
            agenda.jobs({"_id": objId}, function( err, job ) {
            // agenda.jobs({"_id":jobIdentifier}, function (err, job ) {
            if ( err ) {
                   console.log( "Error getting job." );
            } else {
                   console.log( util.inspect(job) );
           }  });
```

And a few other variations - I'm not sure what I'm missing, but would appreciate any assistance anyone might have.  The first one errors out, the commented-out one just comes back empty.

**Comment by bkposton** [comment]
Have you tried require('mongodb').ObjectID( jobIdentifier )

instead of new ObjectId ( jobIdentifier )?

**Comment by C45tr0** [comment]
Using the below did work for me.

```
var mongodb = require('mongodb');
var jobIdentifier = ...
agenda.jobs({"_id": mongodb.ObjectID(jobIdentifier)}, function (err, job) {
  ...
});
```

**Comment by Deano24** [comment]
Using what @C45tr0 said did not work for me, I got TypeError: Argument must be a string. So I went on some searching and found [this](http://stackoverflow.com/questions/38603529/argument-must-be-a-string-in-nodejs).

replace require('mongodb') with require('agenda/node_modules/mongodb') and then do what @C45tr0 says.

My problem seemed to stem from the different mongodb versions.
