### ISSUE TITLE
Cron format Issue

### ISSUE THREAD

**Issue by arvindr21** [agenda/agenda#347]
Hello,

Thanks for the module. I have a Scheduler in my application where I build a cron string on the fly, based what a user selects. For instance, if a user selects - `2.22pm on a Tuesday`, I generate a cron string as `22 14 2 7 2` and current time is `2.15pm on Tuesday`  [Validated the cron string](http://crontab.guru/#22_14_2_7_2). 

But when I look at the scheduled job, I see that it is getting generated 6 hours later, as shown below. 

<img width="362" alt="screen shot 2016-08-02 at 14 12 31" src="https://cloud.githubusercontent.com/assets/2562992/17322464/3778d4e8-58bb-11e6-9d1b-834d3e0cc7f5.png">

Am I missing anything? Any other way to revalidate my Cron string? 

Any help is appreciated. 

Thanks,
Arvind.

**Comment by rtwalz** [comment]
@arvindr21 ever able to fix this? Followed the docs but it runs every hour when it should be once on certain days

**Comment by simison** [comment]
I think a good way to approach this problem would be to write some tests for the cron part of the library.

It has seen some changes in Agenda v0.9 so things might've changed since this was opened.

**Comment by leonardlin** [comment]
@arvindr21 is this still an issue for you? 

Since you filed the issue there have been lots of updates.

**Comment by simison** [comment]
I think it's fine to close and folks can re-open if it's still an issue.
