### ISSUE TITLE
Persistence layers guide - documentation - examples

### ISSUE THREAD

**Issue by jdnichollsc** [agenda/agenda#348]
Hi my friend,

Exist any guide to create a new adapter? I need to migrate my database from **MongoDB** to **PostgreSQL** and I would like to continue using agenda, is very useful for me.

Thanks in advance, Nicholls

**Comment by BrutalFaust** [comment]
+1

**Comment by raymatos** [comment]
I think making agenda DB agnostic would be awesome.

**Comment by simison** [comment]
Follow ups ➡️  #18 _Database adapters_

All help appreciated! #414 _Maintainers needed_
