### ISSUE TITLE
Cron format is broken

### ISSUE THREAD

**Issue by qwelias** [agenda/agenda#351]
``` js
agenda.define( 'test', () => { console.log('test') } );
agenda.every( '*/1 * * * * *', 'test' );
```

Logs 'test' every second

Edit: '\* \* \* \* \* *' does not run at all

Edit2: '0 \* \* \* \* *' registered "nextRunAt" : ISODate("2016-08-08T15:06:00.787Z"), but has not logged anything in 5 minutes.

**Comment by emhagman** [comment]
See #475 , should be fixed

**Comment by leonardlin** [comment]
https://github.com/agenda/agenda/pull/1150 merged
