### ISSUE TITLE
Some complex scheduling cases with delayed start date (and end date)

### ISSUE THREAD

**Issue by suryanaik** [agenda/agenda#356]
Have been struggling to find the right way to implement following scenarios
1. Daily at 8:00AM CST Starting 30-Aug-2016 till 30-Sep-2016
2. Every 3 days at 8:00 AM CST Starting 30-Aug-2016 till 30-Sep-2016
3. Every Wed and Fri at 8:00 AM CST Starting 30-Aug-2016 till 30-Sep-2016
4. Every 60 days at 8:00 AM CST Starting 30-Aug-2016 till 30-March-2017 (should run only once).

Following code could have solved scenario 1 (as shown in #100)
`job.schedule(startDate);`
`job.repeatAt("8:00");`
But can not handle TimeZone. 

Using agenda.every or job.repeatEvery I could solve 1, 2, 3 by using following cron syntax
`0 8 * * *`
`0 8 */3 * *`
`0 8 * * WED,FRI` 
respectively. But with just that I could not control the delayed start (start date). 
For scenario 4, I could not find any proper cron syntax.

I am not really concerned about the end date the same can be handled outside the module.

I have found at least one attempt (https://www.npmjs.com/package/agenda-n) of  introducing Start and End date to Agenda by forking it but I think they have not been have been merged back into agenda. 

At this point of time I am attempting to modify the 'job.attrs.runNextAt' value by calculating the correct date based on the start date. See the code below.
`scheduledJob = agenda.create(jobName, data);`
`scheduledJob.repeatEvery(interval, {timezone: timezone});`
`scheduledJob.computeNextRunAt();`
`scheduledJob = correctNextRunDate(scheduledJob, startDate);`
`scheduledJob.save(function(err) {`
`if (err) {`
`next("Failed to create schedule. Error::", err);`
`}`
`});`

Can someone help in solving the above use cases?

Thanks in advance.

**Comment by suryanaik** [comment]
I also realized that `0 8 */x * *` will also fail if x greater than the number of days left in the month. In such a case, the nextRunAt will be 1st of the next month.

A special treatment has to be given to this case too.

**Comment by suryanaik** [comment]
I have attempted to solve the problem by introducing startDate and skipDate as options to be passed to `job.repeatEvery(interval, options)`. The updated repeatEvery function now looks like following.

```JavaScript
Job.prototype.repeatEvery = function(interval, options) {
    options = options || {};
    this.attrs.repeatInterval = interval;
    this.attrs.repeatTimezone = options.timezone ? options.timezone : null;
    // Following options are added to handle start date
    // and cases like run job every x days (skip some days)
    this.attrs.startDate = options.startDate ? options.startDate : null;
    this.attrs.skipDays = options.skipDays ? options.skipDays : null;
    return this;
};
```
Also modified computeFromInterval function to make use of startDate and skipDays.
```JavaScript
    function computeFromInterval() {
        var dateNow = new Date();
        // If a job has not run in the past, set lastRun to dateNow. This will be used to identify if the date has run in the past or not.
        var lastRun = this.attrs.lastRunAt || dateNow;

        var startDate = this.attrs.startDate;
        var skipDays = this.attrs.skipDays;
        lastRun = dateForTimezone(lastRun);
        try {
            var cronTime = new CronTime(interval);
            var nextDate = cronTime._getNextDateFrom(lastRun);
            if (nextDate.valueOf() == lastRun.valueOf()) {
                // Handle cronTime giving back the same date for the next run time
                nextDate = cronTime._getNextDateFrom(dateForTimezone(new Date(lastRun.valueOf() + 1000)));
            }

            //If start date is present, check if the nextDate should be larger or equal to startDate. If not set startDate as nextDate
            if(startDate != null)
            {
                startDate = moment.tz(moment(startDate).format('YYYY-MM-DD'),timezone);
                if(startDate > nextDate)
                {
                    nextDate = cronTime._getNextDateFrom(dateForTimezone(startDate));
                }
            }

            //If job has run in the past and skipDays is not null, add skipDays to nextDate
            if ((dateNow > lastRun) && skipDays != null) {
                try {
                    nextDate = nextDate.valueOf() + humanInterval(skipDays);
                } catch (e) {}
            }

            this.attrs.nextRunAt = nextDate;
        } catch (e) {
            // Nope, humanInterval then!
            try {
                if (!this.attrs.lastRunAt && humanInterval(interval)) {
                    this.attrs.nextRunAt = lastRun.valueOf();
                } else {
                    this.attrs.nextRunAt = lastRun.valueOf() + humanInterval(interval);
                }
            } catch (e) {}
        } finally {
            if (isNaN(this.attrs.nextRunAt)) {
                this.attrs.nextRunAt = undefined;
                this.fail('failed to calculate nextRunAt due to invalid repeat interval');
            }
        }
    }
```

I have passed the additional parameters using options so that it does not break existing code.
Suggest enhancements/improvements to the code.

**Comment by aitvijay** [comment]
You Missed endDate declaration in computeFromInterval
