### ISSUE TITLE
Bug in calculating next month

### ISSUE THREAD

**Issue by mgregier** [agenda/agenda#358]
My CRON expression looks like this: '0 12 4 8 *' ( 4th August at 12:00) but i can see that nextRunAt value in mongo is set to one month forward ( 4th September at 12:00)
I'm using job.computeNextRunAt(); function to calculate next run.
Internally job.js is using computeFromInterval funciton and is calling cronTime._getNextDateFrom(lastRun); to calculate next run. 
_getNextDateFrom is using date from moment.js which has 0-based months - January is 0 and in CRON expressions January is 1. That's why it is always calculating next run one month forward.

**Comment by OmgImAlexis** [comment]
@mgregier Is this still an issue?

**Comment by mgregier** [comment]
@OmgImAlexis I'm not sure because I'm not using Agenda anymore in my project. This was a bug that moment.js treated months as 0-based while in CRON expressions January has number 1 in months sequence.

**Comment by ldsmike88** [comment]
Why is this still an issue?

**Comment by leonardlin** [comment]
merged https://github.com/agenda/agenda/pull/1150
