### ISSUE TITLE
No SSL support in mongodb connections

### ISSUE THREAD

**Issue by cojack** [agenda/agenda#359]
Hello guys,
I have a request for you, could you change your dependency for mongodb from static numer:
`"mongodb": "2.1.11"`
to something more flexible? fe:
`"mongodb": "^2.1.11"`

Thanks in advance.

P.S. this cause me a problem with ssl validation, in version 2.2.x is fixed. Regards.

**Comment by demianhh** [comment]
asphalt nitro loft 36

**Comment by demianhh** [comment]
"mongodb":. "2.1.12.4

**Comment by cojack** [comment]
@demianhh what?

**Comment by adrukh** [comment]
Ran into this issue myself. Current dependency of `"mongodb": "2.0.34"` is preventing the use of `agenda` with ssl-enabled mongodb.

Example of failing code:
```
const address = 'mongodb://user:password@host1:port1,host2:port2/dbname?ssl=true'; // `ssl=true` part forces ssl connection 
const ca = [fs.readFileSync(__dirname + '/server.crt')];

var options = {
  mongos: {
    ssl: true,
    sslValidate: true,
    sslCA: ca,
  },
};

const agenda = new Agenda({ db: { address, options }});
agenda.on('ready', () => {
  console.log('This never gets printed!');
});

```

The code above hangs as `'ready'` event never fires for `agenda`.

I'll open a PR that bumps `mongodb` dependency to fix this and mention it here shortly.

**Comment by adrukh** [comment]
@cojack how about changing the title of this issue to reflect the problem? 'No SSL support in mongodb connections' seems appropriate :)

**Comment by cojack** [comment]
@adrukh good point, thanks

**Comment by adrukh** [comment]
A workaround would be to use `agenda`'s ability to initialise with an existing mongodb connection:
```
const address = 'mongodb://user:password@host1:port1,host2:port2/dbname?ssl=true'; // `ssl=true` part forces ssl connection 
const ca = [fs.readFileSync(__dirname + '/server.crt')];

var options = {
  mongos: {
    ssl: true,
    sslValidate: true,
    sslCA: ca,
  },
};

return mongoClient.connect(address, options)
.then(db => {
  const agenda = new Agenda({ mongo: db });

  agenda.on('ready', agenda.start);

  agenda.define('webhook', function (job, done) {
    const options = undefsafe(job.attrs, 'data.callback');
    logger.info({ options }, 'Sending callback request');
    request(options, done);
  });

  return agenda;
});
```

This requires `"mongodb": "^2.2.10"` in your `package.json` file, and will duplicate the dependency as `agenda` will fetch an earlier version.

See https://github.com/rschmukler/agenda#mongomongoclientinstance

**Comment by cojack** [comment]
@rschmukler could you?

**Comment by simison** [comment]
Version 0.9.1 on npm now supports SSL for Mongo connections.
