### ISSUE TITLE
Run Agenda as bg queue

### ISSUE THREAD

**Issue by pravin-d** [agenda/agenda#371]
I have some questions with regards to the example in
https://github.com/rschmukler/agenda#example-project-structure

Can I use pm2 to run 2 process namely
1. JOB_TYPES=email node server.js
For adding job to database
2. JOB_TYPES=email node worker.js
to process the job

When agenda.now(...) is called from app.post('/users',..) where or who  runs the job ?  server.js or worker.js process ? What happens when server.js goes down ? 

The Implementation I was looking for was something like bulljs. Using server.js I want to add a job into the database. I want another process to pick up the job and execute it based on the schedule. 
Does the example do the same thing or something else. A little confused here.
Any help would be much appreciated.

**Comment by OmgImAlexis** [comment]
> Fire up an instance with no `JOB_TYPES`, giving you the ability to process jobs, but not wasting resources processing jobs.
