### ISSUE TITLE
Mismatch MongoDB version when npm install

### ISSUE THREAD

**Issue by jirayuzanroo** [agenda/agenda#376]
Hello.

I'd like to npm install agenda@0.9.0 with Mongodb that support SSL version (2.2.10) 
but I got MongoDB version 2.1.11 when npm install agenda@0.9.0

Thank you.
Regard.

**Comment by simison** [comment]
Duplicate? #359

**Comment by obbaeiei** [comment]
It's fixed commit https://github.com/rschmukler/agenda/commit/72101bc528a27aa5f8c0aa8406f971bc631d8221

But there didn't publish to npm yet. 
I still got MongoDB 2.1.11 on agenda@0.9.0

**Comment by simison** [comment]
Agenda 0.9.1 on npm solves this.
