### ISSUE TITLE
MongoDB crashes after findAndModify calls

### ISSUE THREAD

**Issue by gsmhcrew** [agenda/agenda#378]
Hello everybody,

Lately, I've been seeing that not all of my jobs are being ran at the proper time,
I'm using node-windows for making the agenda process work as a service,
And after examining some of the logs, I can see that the errors I receive are mainly from
the mongodb instance, which tells my **errconrefused**, from the 127.0.0.1 port.

I was suspicious about it, so after reading the mongodb logs, I've seen huge chunks of findAndModify logs, and then an 'MongoDB has exhausted the system memory capacity' message, and a shutdown.

For scheduling tasks, I'm currently using agenda.define('some-unique-id') and agenda.every for each of my tasks,
and on reboot of the server, I'm purging every scheduled task and re-defining it,
I'm scheduling 225 jobs, all at once, which some will execute immediately and some will wait for
a specific interval, (lets say, the interval is an hour, the agenda service have shut down thirty minutes ago, 
so I should wait thirty minutes more for the next run), and I will schedule it as agenda.define('some-unique-id'+'FirstRun'), agenda.schedule, when the first run has finished, I will agenda.every it.
The reason for all of this scheduling is the difference between each of the jobs (mostly the intervals, starting dates and the data passed to it). When I started using the package I've tried defining a single job and passing data and intervals to it, but it didn't work as I expected.

I've came across this issue a couple of times, and I feel that my system is not very reliable anymore,
probably caused by misuse of this great package.

Unfortunately, I cannot reproduce the issue currently
due to the fact that the whole thing is at work and I won't be there for a while.

Thanks in advance!

**Comment by timelf123** [comment]
Does this change fix it? https://github.com/rschmukler/agenda/pull/268

**Comment by OmgImAlexis** [comment]
@gsmhcrew can you please confirm that this is still an issue, if not we can close this.

**Comment by simison** [comment]
#448 is available at master now, but not published to npm just yet.

Testing by @gsmhcrew and @etsalah would be so awesome!

**Comment by simison** [comment]
No more deprecated `findAndModify()` in Agenda.
