### ISSUE TITLE
Agenda Every vs agenda repeatEvery

### ISSUE THREAD

**Issue by panagorn** [agenda/agenda#382]
Hello,

I want to run same job multiple times with different data i use
agenda.every('15,35,55 * * * *',   'myjob', {name:"john"});

but i see in the issues that i have to use this
agenda.create('myjob',{name:"john"}).repeatEvery('15,35,55 * * * *').save();
but this codes runs when it is execute and then it repeats at the given time.

The previous code agenda.every('15,35,55 * * * *',   'myjob', {name:"john"});
runs only the given time.

Why is that happening and how to fix repeatEvery to run only the given time?

**Comment by havanakoda** [comment]
It has been fixed here: https://github.com/rschmukler/agenda/issues/192

To sum up, if you'd like to use job.repeatEvery(), you should call job.computeNextRunAt() before saving it. This will avoid the job to run when it is saved.
