### ISSUE TITLE
Multiple jobs with same schedule time are not getting scheduled. 

### ISSUE THREAD

**Issue by sudersen** [agenda/agenda#390]
I'm able to reproduce [issue](https://github.com/rschmukler/agenda/issues/278) even on 0.8.1
have at least 2 instances of agenda running on your local and fire multiple request for jobs bearing same timestamp. You would notice that some of them gets stuck in mongo with only **lockedAt** field set. This would go on till you choose to restart the whole agenda set up.

**Comment by OmgImAlexis** [comment]
@sudersen is this still an issue on 0.9.1?

**Comment by OmgImAlexis** [comment]
Since this has had no response I'm closing it. If this is still an issue please let us know and we can reopen it.
