### ISSUE TITLE
Get Job Id when save

### ISSUE THREAD

**Issue by panagorn** [agenda/agenda#392]
Hello i want to get the job id when save so i can access it later

if i write the following i get the below results:
var job = agenda.create("LIGHT",{macAddress:"ASDf", isOn:2}).repeatEvery('0 '+1+' '+2+' * * '+1).computeNextRunAt().save();
  console.log(job);

where is _id field?

Job {
  agenda: 
   EventEmitter {
     _name: undefined,
     _processEvery: 30000,
     _defaultConcurrency: 5,
     _maxConcurrency: 20,
     _defaultLockLimit: 0,
     _lockLimit: 0,
     _definitions: { LIGHT: [Object] },
     _runningJobs: [],
     _lockedJobs: [],
     _jobQueue: [],
     _defaultLockLifetime: 10000,
     _isLockingOnTheFly: false,
     _jobsToLock: [],
     _events: { ready: [Function] },
     _eventsCount: 1,
     _mdb: 
      Db {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        s: [Object],
        serverConfig: [Getter],
        bufferMaxEntries: [Getter],
        databaseName: [Getter] },
     _collection: Collection { s: [Object] },
     _processInterval: 
      Timeout {
        _called: false,
        _idleTimeout: 30000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 2781,
        _onTimeout: [Function: bound processJobs],
        _timerArgs: undefined,
        _repeat: 30000 },
     _nextScanAt: 2016-12-30T18:04:17.870Z },
  attrs: 
   { name: 'LIGHT',
     data: { macAddress: 'ASDf', isOn: 2 },
     type: 'normal',
     priority: 0,
     nextRunAt: 
      { [Number: 1483315260878]
        _isAMomentObject: true,
        _i: 2016-12-30T18:03:47.878Z,
        _isUTC: false,
        _pf: [Object],
        _locale: [Object],
        _z: null,
        _d: 2017-01-02T00:01:00.878Z,
        _isValid: true },
     repeatInterval: '0 1 2 * * 1',
     repeatTimezone: null } }

**Comment by valetzyzy** [comment]
I found some workaround 

```
var job = jobsQueue.create('name', data);
job.priority('low');
job.save(function (err, data) {
    console.log(data.attrs._id); //58ab0d57773c0b9e013d1f24
});
```

**Comment by simison** [comment]
Job `_id` is same as MongoDB `_id` so it will be there only after saving the job.

It gets set here:
https://github.com/agenda/agenda/blob/b818de4d47a3182b95db327edb12f861738957b0/lib/agenda.js#L381

**Comment by pprathameshmore** [comment]
I am not receiving job id 

```      const job = this.agenda.create(queueName, data);
      job.repeatEvery(interval);
      job.save();
      logger.info(`Job Added with interval: ${job.attrs._id}`);
      return job;```
