### ISSUE TITLE
What I want is to not `behavior` at the moment of booking

### ISSUE THREAD

**Issue by ucpwang** [agenda/agenda#397]
hi~

Thank you for making the module so good.
I found this and it was so much fun.
I am developing a question, so I leave a question.

I am doing iterative scheduling using the `job.repeatEvery` function.
What I want is to not `behavior` at the moment of booking
I don't know if I can control this as an option.

**Comment by OmgImAlexis** [comment]
Closing this support request as it's been over 3 months since the last comment. If you still have an issue please open a new issue and reference back to this one.
