### ISSUE TITLE
Cannot read property 's' of undefined after updating mongodb & mongoskin

### ISSUE THREAD

**Issue by ceh-deployer** [agenda/agenda#404]
Hi,

Using Agenda@0.9.0 and after updating mongodb to 2.1.22 and mongoskin to 2.1.0 I'm getting the next error:

```
TypeError: Cannot read property 's' of undefined
  at Agenda._findAndLockNextJob (/home/ubuntu/canariasenhora/node_modules/agenda/lib/agenda.js:426:16)
  at jobQueueFilling (/home/ubuntu/canariasenhora/node_modules/agenda/lib/agenda.js:607:10)
  at processJobs (/home/ubuntu/canariasenhora/node_modules/agenda/lib/agenda.js:485:7)
  at ontimeout (timers.js:365:14)
  at tryOnTimeout (timers.js:237:5)
  at Timer.listOnTimeout (timers.js:207:5)
```

Is there any solution? Any fix?

Thanks!

**Comment by ccanete** [comment]
I've found [here](http://stackoverflow.com/a/40558691/5085859) that the problem comes from the `mongodb-core` version used.

> MongoDB driver 2.2 uses mongodb-core 2.0 (and bson 0.5) whereas MongoDB driver 2.1 uses mongodb-core 1.3 and bson 0.4. If you try to use a MongoDB driver 2.1 ObjectId with MongoDB driver 2.2 you'll get this error.

So, if you are using a mongodb version > 2.2.x in your project, ObjectIDs are not compatible.

The solution I've found is to hack the dependencies of agenda and force it to use mongodb@2.2.x and mongodb-core@2.0.x. To do so, you can use `npm shrinkwrap` that will generate a `npm-shrinkwrap.json` file. Then, you can change the dependencies of agenda.
It worked for me.

**Comment by lakamsani** [comment]
Seeing a similar problem, with agenda 0.9.0.Here are my mongodb dependencies. This is with node.js 7.6.0

├─┬ mongodb@2.1.11
│ ├─┬ mongodb-core@1.3.10
│ │ ├── bson@0.4.23

````bash
TypeError: Argument must be a string
    at Buffer.write (buffer.js:782:21)
    at serializeObjectId /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:242:10)
    at serializeInto /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:699:17)
    at serializeObject /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at serializeObject /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:551:17)
    at serializeObject /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:280:18)
    at serializeInto /Users/me/myapp/node_modules/bson/lib/bson/parser/serializer.js:705:17)
    at BSON.serialize /Users/me/myapp/node_modules/bson/lib/bson/bson.js:47:27)
    at Query.toBin /Users/me/myapp/node_modules/mongodb-core/lib/connection/commands.js:116:25)
    at executeSingleOperation /Users/me/myapp/node_modules/mongodb-core/lib/topologies/server.js:780:28)
    at Server.command /Users/me/myapp/node_modules/mongodb-core/lib/topologies/server.js:853:12)
    at executeWrite /Users/me/myapp/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:47:12)
    at LegacySupport.insert /Users/me/myapp/node_modules/mongodb-core/lib/wireprotocol/2_6_support.js:55:3)
    at Server.insert /Users/me/myapp/node_modules/mongodb-core/lib/topologies/server.js:970:37)
    at Server.insert /Users/me/myapp/node_modules/agenda/node_modules/mongodb/lib/server.js:312:17)
    at insertDocuments /Users/me/myapp/node_modules/agenda/node_modules/mongodb/lib/collection.js:497:19)
    at Collection.insertOne /Users/me/myapp/node_modules/agenda/node_modules/mongodb/lib/collection.js:345:3)
    at Collection.wrapped /Users/me/myapp/node_modules/newrelic/lib/transaction/tracer/index.js:155:28)
    at Collection.wrappedQuery /Users/me/myapp/node_modules/newrelic/lib/instrumentation/mongodb.js:281:53)
    at Collection.wrapped [as insertOne] /Users/me/myapp/node_modules/newrelic/lib/instrumentation/mongodb.js:251:22)
    at module.exports.Agenda.saveJob /Users/me/myapp/node_modules/agenda/lib/agenda.js:349:22)
    at Job.save /Users/me/myapp/node_modules/agenda/lib/job.js:232:15)
    at createJob /Users/me/myapp/node_modules/agenda/lib/agenda.js:262:9)
    at module.exports.Agenda.schedule /Users/me/myapp/node_modules/agenda/lib/agenda.js:253:12)
````

**Comment by lakamsani** [comment]
In my case problem seems to be the new 4.8.x version of mongoose and the dependencies it is pulling. I went back to 4.4.17 version of mongoose so the dependencies look like this:

````bash
%npm list bson
└─┬ mongoose@4.4.17
  └── bson@0.4.23

% npm list mongodb
├── mongodb@2.1.11
└─┬ mongoose@4.4.17
  └── mongodb@2.1.18

%npm list agenda 
└── agenda@0.9.0
````
And the above error went away.

**Comment by rubenjimenez** [comment]
Hi,

I have the same issue. Tried all the solutions here but none worked.

```
TypeError: Cannot read property 's' of undefined
  at Agenda._findAndLockNextJob (/home/ubuntu/app/node_modules/agenda/lib/agenda.js:426:16)
  at jobQueueFilling (/home/ubuntu/app/node_modules/agenda/lib/agenda.js:607:10)
  at processJobs (/home/ubuntu/app/node_modules/agenda/lib/agenda.js:485:7)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

TypeError: Cannot read property 's' of undefined
  at Agenda._findAndLockNextJob (/home/ubuntu/app/node_modules/agenda/lib/agenda.js:426:16)
  at jobQueueFilling (/home/ubuntu/app/node_modules/agenda/lib/agenda.js:607:10)
  at processJobs (/home/ubuntu/app/node_modules/agenda/lib/agenda.js:485:7)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at Immediate._tickDomainCallback (internal/process/next_tick.js:122:9)
  at runCallback (timers.js:651:20)
  at tryOnImmediate (timers.js:624:5)
  at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by lakamsani** [comment]
@rubenjimenez send the output of `npm list bson` as well.  Did you use `npm shrinkwrap` as suggested by @ccanete above to get `agenda 0.9`  to use  `mongodb 2.2.24`?

**Comment by rubenjimenez** [comment]
```
%npm list bson
├─┬ agenda@0.9.0
│ └─┬ mongodb@2.2.24
│   └─┬ mongodb-core@2.1.8
│     └── bson@1.0.4
├─┬ connect-mongodb-session@1.3.0
│ └─┬ mongodb@2.2.24
│   └─┬ mongodb-core@2.1.8
│     └── bson@1.0.4
└─┬ mongoose@4.8.5
  └── bson@1.0.4
```

Yep @lakamsani, I used it and nothing. I'm debugging agenda.js (0.9.0) code and I'm discovering some weird things.

The first one, in **_findAndLockNextJob** method, the github code version has this line:

`var s = this._mdb.s || this._mdb.db.s;`

But the 0.9.0 npm version has not.

It's there where the error is occurring because _mdb is undefined.

The **database** method should run the MongoClient.connect method:

```
MongoClient.connect(url, options, function ( error, db ){
    if (error) {
      if (cb) {
        cb(error, null);
      } else {
        throw error;
      }

      return;
    }

    self._mdb = db;
    self.db_init( collection, cb );
  });
```

But it is not running the callback, so there it is the main problem. Agenda is not connecting to MongoDb. Reading documentation, MongoDB native driver is only able to connect once so I'm guessing that if Agenda is being used in a project where it is already connected to MongoDb Agenda is not going to work.

Could it be?

**Comment by lakamsani** [comment]
I think the callback is called later in `handleLegacyCreateIndex` which in turn is called by `self.db_init`. 
In my project I have multiple mongo db connections via mongoose. And Agenda 0.9 is able to make its own (non-mongoose connection) just fine. If possible send the 'config.db' property value you are passing in when constructing the Agenda object initially. Also definitely try with older versions of mongoose and mongodb (without any shrinkwrap) as I found that to be the only reliable combination for this to work unless you need the newer mongoose/mongdb versions for some new features you are using there.

**Comment by rubenjimenez** [comment]
This is the config.db value:

`mongodb://user:password@shard0.mongodb.net:27017,shard1.mongodb.net:27017,shard2.mongodb.net:27017/master?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin`

You're right, after a little delay it connects but initially it prints those undefined errors. I have not tested if Agenda works properly but it should.

Right now, in production, we're running using Agenda 0.6 and we don't get those errors. But we need to upgrade our MongoDb native driver so we must upgrade Agenda as well.

**Comment by lakamsani** [comment]
@rubenjimenez  some of the issues I encountered above have been fixed with 0.9.1 version of agenda that was released a few days ago. https://github.com/rschmukler/agenda/issues/395 . It appears there was publish issue with 0.9.0 due to which the code downloaded via  didn't really support the newer mongo drivers. 0.9.1 of agenda seems to work in my app with mongodb node module version 2.2.25 and mongoose node module version 4.9.2

**Comment by rubenjimenez** [comment]
Thanks for the notice @lakamsani. We'll try it out. We were running 0.9.0 with latest mongo drivers without glitches excepting that undefined error at startup.

I'll update this post if I find some kind of issue.

**Comment by itsyogesh** [comment]
I had the same issue. Apparently using the ready event solves this. Here is what I did before starting agenda. I am using agenda@0.9.1.
```
agenda.on('ready', () => {
    agenda.start()
  })
```
This works perfectly now.

**Comment by dff3bc** [comment]
@itsyogesh That seems to be the solution. Just tested.

**Comment by simison** [comment]
This is now mentioned in [docs](https://github.com/agenda/agenda#example-usage) as well, closing.

Also Mongo driver version is now ^2.2: https://github.com/agenda/agenda/commit/72101bc528a27aa5f8c0aa8406f971bc631d8221
