### ISSUE TITLE
Integrate `semantic-release`

### ISSUE THREAD

**Issue by adrukh** [agenda/agenda#406]
Seeing the tension between people wanting to see releases published to npmjs, synced with github releases, etc., I'd like to suggest using [semantic-release](https://www.npmjs.com/package/semantic-release)!

### How does this help:
Using `semantic-release` greatly simplifies release processes. Once used, every commit to the `master` branch will publish a new build on npmjs.com and a new release on github.com.

### What does this need:
- Configuration setup by running `npm install -g semantic-release-cli; semantic-release-cli setup` once on a dev env of a maintainer of this wonderful project. npm token and github token will be captured and used as env vars on travis
- Commit messages need to follow semantic release convention (start with `fix: ...` for fixes, `feat: ...` for features, etc.)
- Giving up on manually deciding on release version numbers.

### What this actually does:
- adds `NPM_TOKEN` and `GH_TOKEN` as travis env variables
- adds `semantic-release` as a target to `package.json`
- adds `npm run semantic-release` to `.travis.yml` under the `after_success` section

Hope the maintainers of this wonderful project find this helpful! :)

**Comment by OmgImAlexis** [comment]
Closing this as we already have a way to handle versions and it doesn't look like the other devs or any other uses want this at the moment.
