### ISSUE TITLE
Maintainers needed?

### ISSUE THREAD

**Issue by simison** [agenda/agenda#414]
Heyy @rschmukler,

I really like Agenda and I use it a lot! :beers: Just pity that maintaining this package isn't very active anymore. :-(

There seems to be enough interest from community to send pull requests and open issues tho, so perhaps we could find some folks to help with looking after PRs and issues?

WDYT?

Unfortunately I'm already super busy with other open source stuff myself.

Anyone else interested?

**Comment by gastonelhordoy** [comment]
I'll be more than willing to help out and contribute if needed. I'm also heavily relying on this project so it would be good to get some progress on PRs and issues.

Let us know your thoughts on this @rschmukler

**Comment by Firanolfind** [comment]
Agree. +1

**Comment by rschmukler** [comment]
Hey all! I would be ecstatic to get some help maintaining. I deeply apologize for the lack of maintenance. I recently founded a company and have largely transitioned away from Node so my efforts have been limited as late. 

How would you all suggest I proceed from here? Just grant access to a few people on the repo?

PS I will publish #395 tonight

**Comment by rschmukler** [comment]
Hey all. I just got Node re-set up on my home computer. This means that I should be better equipped to handle maintenance issues around agenda.

That being said, I would still love help maintaining (and even further developing) this package!

If anyone wants to get involved, please feel free to post here or email me at `ryan@slingingcode.com`. I propose the following: People who want to maintain, please contact me and also start replying to issues / PRs with a LGTM etc. Like I said, I won't being reviewing too much but once we get a consensus going I will keep note of the interested parties who are helping along. From there, I (or you, the community) can pick a few members to get NPM publishing / GitHub write access so that maintenance can continue along at a more rapid speed and is no longer dependent on me as a gate keeper.

PS. Existing maintainers will be kept on (@loris, @nkweekly and @droppedoncaprica) in case they also want to help contribute.

I'm very excited to get others involved in this, so please don't hesitate to join in!

**Comment by bonesoul** [comment]
hope this package can get the love from community that it deserves

**Comment by droppedoncaprica** [comment]
I totally agree that this package needs a more active maintainers to keep this running.  I've moved to a new job that uses a completely different back-end myself, so I've not been keeping up with this library's issues / pull requests as much as I have in the past. 

If anyone needs help with maintenance, feel free to @ ping me and I'll do my best to take a look at it!

**Comment by OmgImAlexis** [comment]
@rschmukler maybe look at moving this to an org so it's easier to handle others getting merge rights, etc?

**Comment by simison** [comment]
>Edit: Looks like agenda is free maybe contact Github about getting it moved to an org for you?

It's possible to transfer the repo for an org from here (at "danger zone"):
https://github.com/rschmukler/agenda/settings

Just create a new org first:
https://github.com/account/organizations/new

**Comment by dylanjha** [comment]
@rschmukler thanks for all the work you have done on agenda. I second @OmgImAlexis @simison that I would be happy to help maintain

**Comment by OmgImAlexis** [comment]
@rschmukler if you're okay with moving it to an org I'd be more than happy to start clearing out old issues as well as getting all the dev deps updated.

**Comment by michelem09** [comment]
I'm in too, if you need.

**Comment by jpiepkow** [comment]
Same I use this in a production application and have had to look into the code more then a couple times.

**Comment by nwkeeley** [comment]
Hi,

I am in a place to become more actively engaged with this module. I dropped offline for awhile to handle some family/work stuff but I am back and engaged.. I actually have this module running in production in 4 different applications soon to be 5 ..... so I am extremely vested in its success.

Really great to hear everyone interested in helping Ryan this is a fantastic module he's put together super excited to see it keep growing!

-Nate

**Comment by joeframbach** [comment]
I would also like to move Agendash into the new Org. :+1: or :-1:?

**Comment by simison** [comment]
@joeframbach is doing wonderful job with [agendash](https://github.com/joeframbach/agendash), would you like to move that to new org as well, WDYT? I would probably get more attention like that.

**Comment by joeframbach** [comment]
Yup, can you create the org and invite me in? I'm not 100% on the process Github has for transferring, or how npm publishing handles it. But I'm sure I can figure it out.

**Comment by simison** [comment]
@joeframbach see my comments above: https://github.com/rschmukler/agenda/issues/414#issuecomment-301304822

**Comment by joeframbach** [comment]
I've sent a request to a human at Github to see if "agenda" is inactive and if we can take the name.

**Comment by joeframbach** [comment]
Good news! I've created the Org https://github.com/agenda and will send invitations shortly. (I'm at work, it'll be over my lunch break so be patient)

**Comment by dylanjha** [comment]
thanks @joeframbach!

**Comment by joeframbach** [comment]
@rschmukler I've created the @agenda org and sent invites to anyone above who offered to maintain Agenda. I've invited you as an Owner of the org. Could you transfer Agenda to the org, and I believe that will close this issue :)

**Comment by rschmukler** [comment]
Hey all! It has been transferred. Thank you all for your efforts and your help. Closing this issue. Hoping that agenda can get the love it needs.

If you guys need publishing access on NPM, please email me (see my profile) your NPM username so that I can add you. Initially I'd like to keep publishers / release cutters to just a few people, but am happy to bring more on if you guys think otherwise.

PS. I use [tj/git-extras](https://github.com/tj/git-extras) for `git-changelog` and `git-release` commands which generate the changelog and tagging schema.

**Comment by dylanjha** [comment]
Thanks @rschmukler !

**Comment by simison** [comment]
@joeframbach I think a lot of people added as contributors still cannot close/edit/merge issues or PRs: I think after adding to people to organisation, you still need to add them to a team and then assign that team to repository.

@dylanjha @nwkeeley @jpiepkow @michelem09 @OmgImAlexis @gastonelhordoy Follow ups here; #441 FYI: I'm too busy myself to do coding for this but never too busy to try inspire others. ;-)

**Comment by michelem09** [comment]
I confirm I can't close/edit/merge issue.

**Comment by joeframbach** [comment]
I have created a @agenda/maintainers Team and assigned it Write access to agenda/agenda and agenda/agendash. I don't know if this grants rights to modify issues.

**Comment by simison** [comment]
@joeframbach thanks, that worked.

**Comment by michelem09** [comment]
@joeframbach am I in? I still can't do much.

**Comment by OmgImAlexis** [comment]
@joeframbach can't edit issues either. I'd like to go and sort open issues with tags so we can try and get it the backlog sorted.

**Comment by michelem09** [comment]
Yes the same as @OmgImAlexis I'd like to manage issues to try organise (and possibly close) them.

**Comment by joeframbach** [comment]
Ah, I see. Members of the "organization" are able to push code but can't close issues. Members of the "team" are able to close issues. Silly Github. I've added you both to the team.

**Comment by niftylettuce** [comment]
@joeframbach @rschmukler I'd like to work more on Agenda and would love an invite to @Agenda/maintainers. I've done quite a bit of work and have solid fundamental understanding of the codebase per my work in #464. I also was going to do a complete write from scratch of my own job scheduler, but after a battle of patience I decided it'd be best if I focused on contributing instead; helping us get where we need to be with this package. I publish and maintain [quite a few other packages](https://www.npmjs.com/~niftylettuce) and would love to be a part of the Agenda organization so I can more readily contribute and feel welcome. Thanks! ❤️

**Comment by simison** [comment]
@niftylettuce great! I've been inspired by your work on open source for a while already. Great to see you jumping in here, too! ❤️

Now that we're quite a few working together, I thought of writing a quick "how we work" checklist and code of conduct, please all @agenda/maintainers [have a look](https://github.com/agenda/agenda/wiki) and feel free to comment/modify! And always show this to new maintainers so we ensure common methods and pace of working.

If you think it's over the top, feel free to try shorten it to be more concise.

**Comment by nwkeeley** [comment]
@niftylettuce - I also have followed your work. I would be really excited to have you become a maintainer of this project I think you could bring a lot of value.

**Comment by joeframbach** [comment]
I have sent an invite to @niftylettuce as a maintainer.

**Comment by lushc** [comment]
@simison thanks for putting that together, it looks perfect to me.

@niftylettuce welcome!

**Comment by rschmukler** [comment]
Hey all! Sorry on the delay, again. I've added @simison, @joeframbach, and @niftylettuce as package owners on NPM. I would also be happy to add @lushc and @OmgImAlexis but their NPM user names don't appear to be the same as their github's.

All other maintainers, feel free to add NPM owners freely.

Thanks all!

**Comment by niftylettuce** [comment]
Thank you @rschmukler 🎉

**Comment by niftylettuce** [comment]
@rschmukler @joeframbach can you please add @OmgImAlexis and I as owners of the repo?  I've also sent you invites on Slack (once you accept I will make you team owner like the rest of us). https://github.com/agenda/agenda/issues/516

Also we need to ensure and enforce that all owners / collaborators have 2FA enabled per https://github.com/agenda/agenda/issues/516

We are going to get <agendajs.com> up with documentation per https://github.com/agenda/agenda/issues/517 as well.
