### ISSUE TITLE
Is it possible to configure initial delay for a job?

### ISSUE THREAD

**Issue by serge-nikitin** [agenda/agenda#415]
I need to run my jobs with different initial delay. Pseudo code:

```
job1.repeatEvery('5 seconds').initialDelay('10 minutes');
job2.repeatEvery('20 seconds').initialDelay('40 minutes');
```

Is it possible to do it with agenda?

**Comment by code2be** [comment]
I think You can use `.schedule(time)` for that purpose ?
Please check: https://github.com/rschmukler/agenda#scheduletime

**Comment by michelem09** [comment]
I'm closing this, feel free to reopen if needed.
