### ISSUE TITLE
TypeError: this._mdb.collection is not a function

### ISSUE THREAD

**Issue by arpithparikh** [agenda/agenda#416]
While compiling the node application , I'm getting following error! Hope developers can help me out to sort this error. Working on Mongo  reporting tool using agenda.
```
ypeError: this._mdb.collection is not a function
    at Agenda.db_init (/Worker/node_modules/agenda/lib/agenda.js:100:15)
    at Agenda.mongo (/Worker/node_modules/agenda/lib/agenda.js:58:8)
    at new module.exports (/Worker/node_modules/agenda/lib/agenda.js:46:10)
    at Object.<anonymous> (/Worker/app.js:30:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
```

**Comment by MuraevArt** [comment]
this error occured if you use following `new Agenda({
        mongo:{ db: mongo, collection: 'tasks'}});`
Try this `new Agenda().mongo(mongo, 'tasks');`
This works for me.

**Comment by hvarday** [comment]
Even I'm getting the same error, did you find any solution @arpithparikh ?

**Comment by SamClayton** [comment]
Same issue when I supply an existing mongoClient instance ('db' here).

agenda = new Agenda({
    name: agendaName,
    mongo: db,
    db: { collection: agendaCollection },
    processEvery: processEvery
  })

**Comment by simison** [comment]
Are you ensuring you don't try to initiate Agenda before you've really connected to MongoDB?

See example:
https://mongodb.github.io/node-mongodb-native/2.2/quick-start/quick-start/#connect-to-mongodb

same for Mongoose:
http://mongoosejs.com/docs/index.html

**Comment by yanisIk** [comment]
Did someone find a solution for that ?

I tried the following and it didn't work:

- Letting agenda handle the connection.
- Using the same mongoose connection as the one in my app and only initiating agenda once the connection is open.

**Comment by SamClayton** [comment]
In my case, it turned out that the variable being passed as 'db' was being mediated by another module and was not always resolving to a mongoClient instance. I cannot, however, speak to the OP's issue.

**Comment by ezos86** [comment]
??? Anyone.. still getting this.

**Comment by FlawaCLV** [comment]
I'm getting `this.databaseConnection.collection is not a function`. Any idea ?!

**Comment by gubarez** [comment]
For mongoose you need to use db.connection instead.
```
agenda = new Agenda({ 
  mongo: db.connection
})
```

**Comment by dandv** [comment]
I get the "this._mdb.collection is not a function" erorr if I try to instantiate Agenda by passing a mongoClient object to `new Agenda({ mongo: mongoClient })`:

```js
const mongoClient = await MongoClient.connect(mongoUrl, { useNewUrlParser: true });

config.agenda = new Agenda({
  mongo: config.mongoClient,
});

The solution is to pass the database, not the client. If you only pass the mongoClient, Agenda would not know which database it should use.

```js
const mongoClient = await MongoClient.connect(mongoUrl, { useNewUrlParser: true });

config.agenda = new Agenda({
  mongo: config.mongoClient.db(),  // <-- note the .db()
});

**Comment by mdelclaro** [comment]
@dandv that worked :)

**Comment by vemundeldegard** [comment]
Thanks @dandv !

**Comment by matthiasdg** [comment]
also noticed this, think this is due to the changes in node-mongodb-native v3; see https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md
`MongoClient.connect works as expected but it returns the MongoClient instance instead of a database object.`
So documentation should probably be updated to reflect these changes

**Comment by simison** [comment]
> this is due to the changes in node-mongodb-native v3
> ...
> So documentation should probably be updated to reflect these changes

Good finding! Could someone do a pull request, please?

**Comment by nkemcels** [comment]
This worked for me:
```js
const client = await MongoClient.connect("mongodb://localhost:27017");
const agenda = new Agenda().mongo(client.db("database_name"), "jobs");
```
As from version 3.0 of the mongodb nodejs native driver, you get an instance of the client object containing the database object instead
