### ISSUE TITLE
agenda.schedule

### ISSUE THREAD

**Issue by macasas** [agenda/agenda#419]
When I add a job using 
        agenda.schedule(scheduleTime, 'reminder', {
          fbid,
          first_name,
          task
        });

everything runs fine.

In the same app, I have added another
        agenda.schedule(scheduleTime, 'subscription', {
          fbid,
          first_name,
          task
        });
and nothing happens.

The job is in the database and reports it should have run 2 hours ago if asked.
 I have a
        agenda.start();

What am I missing?

**Comment by macasas** [comment]
Okay, i've got my head around it now :-) Sorry to jumped the gun.

**Comment by v1adko** [comment]
@macasas Probably better to close the issue then.

**Comment by michelem09** [comment]
Please close this.
