### ISSUE TITLE
Scheduling job with agenda.every method with human interval runs the job immediately

### ISSUE THREAD

**Issue by jagadish-kb** [agenda/agenda#422]
Scheduling the job with agenda.every method with human interval runs the job immediately and not after at the defined interval. 
For ex., If i would like to run a Job every '4 hours', with the option 
```
agenda.every('4 hours', 'MY_JOB_NAME');
```
I see that the 'MY_JOB_NAME' runs immediately. Not sure why it is required to run the job immediately when scheduling via human interval. Even if it is required, can we atleast have an option where we can skip this immediate run? 

I did a minor fix in the function 'computeFromInterval' in job.js and it skips running this immediately. PFB fix:

```
function computeFromInterval() {
    var lastRun = this.attrs.lastRunAt || new Date();
    .....
      // Nope, humanInterval then!
      try {
        //Just removed the special check if nextRunAt is !present 
         this.attrs.nextRunAt = lastRun.valueOf() + humanInterval(interval);
      } catch (e) {}
    ....
  }
```
If at all, the immediate run is also required then `computeNextRunAt` method could be passed the `options` attrib which could have a flag `skipImmediate=true` which could be put in the above block of fix and both behaviors can co-exist. But I did see few other defects where people didnt want this default run to happen immediately. So kindly advise.

**Comment by Neoflash1979** [comment]
@jagadish-kb Not only with human interval, but also with numbers. Unless I did something wrong, I'm having a problem where the job will run immediately and only once. It won't run again at the selected interval. Here is my code:

```
const dburl = 'mongodb://localhost:27017/nightlife';
const url = process.env.MONGOLAB_URI;

import * as Agenda from 'agenda';

const agenda = new Agenda({
  db: { address: url || dburl, collection: 'agendaJobs' },
  processEvery: '60 seconds'
});

agenda.define('print to console', function (job, done) {
  console.log('Job just fired');
});



agenda.on('ready', function () {
  agenda.every(90000, 'print to console');
  agenda.start();
});

function graceful() {
  agenda.stop(function () {
    console.log('Exiting Agenda')
    process.exit(0);
  });
}

process.on('SIGTERM', graceful);
process.on('SIGINT', graceful);
```

**Comment by lushc** [comment]
It looks like the behaviour for running a human interval job immediately was introduced in dd5bd407.

**Comment by arihantdaga** [comment]
In the new library version 1.0.3 its is still happening..

**Comment by marcusjwhelan** [comment]
I currently have this and my agenda scheduled job will lose its nextRunAt after the first run.

```javascript
module.exports = function (agenda) {
    agenda.define('SundayPastWeekEmail', {concurrency: 1}, (job, done) => {
    SundaySaturdayTotalEmail()
      .then(() => {
        log.trace('Finished SundayPastWeekEmail Task');
        done();
      })
      .catch((err) => {
        log.error({error: err}, "Error while trying to email Sunday Past week summary" + err);
        done();
      });
  });
  
  agenda.on('ready', () => {
    agenda.schedule('sunday at 15:00', 'SundayPastWeekEmail');
  });
}
```
The method is imported correctly and I have an agenda job just like this but is a `agenda.every` version and that one always works correctly. However my two scheduled ones always lose the nextRunAt after one go through. 

My server also restarts ofter for changes and other things and the jobs are duplicated on the server while the `agenda.every` jobs are not.

**Comment by arihantdaga** [comment]
@marcusjwhelan Did you check the commit i refrence above.. 
If you can manually apply this patch and see if it is working for you ??

**Comment by marcusjwhelan** [comment]
@arihantdaga I actually ended up just putting 
`agenda.schedule('sunday at 15:00', 'SundayPastWeekEmail');` before `done()` and it worked but still getting extra jobs that have null nextAtTime. Just extra ones. I am guess this is more about my graceful shutdown not working right. 

I have several files with jobs and I can't seem to cancel them all in time before the process ends.

**Comment by okaybroda** [comment]
```javascript
job.repeatEvery('5 minutes')
job.attrs.lastRunAt = new Date()
job.attrs.lastFinishedAt = new Date()
job.computeNextRunAt()
```

Had the same problem and the above worked for me.

**Comment by simison** [comment]
Agenda v2.0.0 now has `skipImmediate ` option in `repeatEvery()`: https://github.com/agenda/agenda#repeateveryinterval-options
