### ISSUE TITLE
Defining and running agenda jobs from separate files.

### ISSUE THREAD

**Issue by majidhassan** [agenda/agenda#426]
Hello,

I want to define the agenda jobs and run them in two separate files. I'm defining the jobs in one file, however, I want to connect to the same agenda from a separate file and run the jobs immediately. I thought configuring a new agenda with the same database url should do the trick, but I can't get it to work.

This is what I currently do:

File 1

```js
var agenda = new Agenda({db: {address: 'mydburi'}});
agenda.processEvery('30 seconds');

agenda.define('myjob', function(job, done) {
    done();
});
```

File 2

```js
var agenda = new Agenda({db: {address: 'mydburi'}});
agenda.processEvery('30 seconds');

agenda.now('myjob');
```

Any ideas how to do this?

**Comment by manojchandrashekar** [comment]
I'm trying to do the same, with  no luck so far.

**Comment by lushc** [comment]
You should use [module.exports](https://stackoverflow.com/a/5311377/1983684). Here's an example, given the following directory structure:

```
.
├── foo.js
├── jobs
│   └── index.js
```

```js
// index.js
var agenda = new Agenda({db: {address: 'mydburi'}});
agenda.processEvery('30 seconds');

agenda.define('myjob', function(job, done) {
    done();
});

module.exports = agenda;
```

```js
// foo.js
var agenda = require('./jobs');

agenda.now('myjob');
```

**Comment by manojchandrashekar** [comment]
@lushc I followed the same `agenda.now()` fails if the connection to mongoDB is not established yet - which is 90% of the case for me.

What I have currently done is, I am connecting to mongoDB and passing the connection instance to agenda, which is working well as of now.

**Comment by majidhassan** [comment]
@manojchandrashekar could you post your solution please?

**Comment by manojchandrashekar** [comment]
Sure, I can do it later today.

**Comment by manojchandrashekar** [comment]
`-- queue.js --`

```
'use strict';

module.exports = function (db) {
  const Agenda = require('agenda');
  const agenda = new Agenda({
    name: 'queueID',
    mongo: db,
    processEvery: '3 minutes',
    lockLimit: 10
  });

  require('./job')(agenda);
  return agenda;
};
```

`-- worker.js --`

```
module.exports = function (db) {
  let worker = require('./queue')(db);
  return worker;
};
```

`-- job.js --`

```
module.exports = function (agenda) {
  agenda.define('jobName', function (job, done) {
    // Job definition
    done();
  });
};
```

`-- data-source.js -- [This is the file you need to customize to return the DB connection object. Since I use loopback (http://loopback.io), this is what I have. You may actually use it as-is by installing the dependencies used below - but please do some extensive testing anyway.]`

```
const DataSource = require('loopback-datasource-juggler').DataSource;

function DS(url) {
  this.dbUrl = url;

  const dataSource = new DataSource({
    connector: require('loopback-connector-mongodb'),
    url: this.dbUrl,
    lazyConnect: false
  });

  this.db = null;

  this.connector = function (cb) {
    if (this.db) {
      cb(this.db);
    } else {
      const self = this;
      dataSource.connect(function (err) {
        if (err) throw err;
        self.db = dataSource.connector.db;
        cb(self.db);
      });
    }
  };
}

module.exports = DS;
```

Finally, to use all this to create a job,

```
ds.connector(function (db) {
  let data = {
    key: 'value'
  };

  const worker = require('./worker')(db);
  worker.now('jobName', data);
});
```

Hope this helps.
