### ISSUE TITLE
MongoError: connection 3 to xxxxxx.mlab.com:yyyyy timed out

### ISSUE THREAD

**Issue by mariokam** [agenda/agenda#428]
I am having a problem with the connection timeoout sometimes on agenda. Can u help me pls?

MongoError: connection 3 to xxxxxxxx.mlab.com:yyyyy timed out

Using the free tier of mLab, is there any way to do more stable initialization of agenda mongodb connection?

thnx

**Comment by simison** [comment]
You can pass Agenda existing Mongo connection from the main app instead of letting it connect on its own.

See https://github.com/rschmukler/agenda/blob/master/lib/agenda.js#L45-L49

**Comment by mariokam** [comment]
The way I do it is the following:

```
var mongoConnectionString = "mongodb://xxxxxxx:yyyyyyyyy@zzzzzzzzzzz.mlab.com:15131/some_client";
var agenda = new Agenda({db: { address: mongoConnectionString, options: {server:{auto_reconnect:true}} }, maxConcurrency: 2000, lockLimit: 0, defaultLockLifetime: 10000 }, function() {
    // Should add this code before setting middleware.
    agenda._db = agenda._collection;
    app.use('/agenda-ui/', agendaUI(agenda, {poll: 5000}));
});
agenda.on('ready', function() {

  agenda.jobs({priority: 'high'}, function(err, jobs) {
    jobs.forEach(function(job) {
       console.log("job Name:",job.attrs.name);
      // sampleJob.sendEmail(agenda,job.attrs.name);
    });
  });
  agenda.start();
});
```

**Comment by simison** [comment]
Yep, so just use `mongo` config key instead.

> If your app already has a MongoDB connection then use that. ie. specify `config.mongo` in the Constructor or use `Agenda.mongo()`.

If you then face connection issues, it's between your app and Mongo, and not Agenda related.

**Comment by mathieug** [comment]
When I stop my local MongoDB server while my app is launched, I get an this error before it crashes:
```
/Users/mathieug/project/node_modules/agenda/lib/agenda.js:609
        throw err;
        ^

Error: No MongoDB Connection
    at Agenda._findAndLockNextJob (/Users/mathieug/project/node_modules/agenda/lib/agenda.js:427:8)
    at jobQueueFilling (/Users/mathieug/project/node_modules/agenda/lib/agenda.js:607:10)
    at processJobs (/Users/mathieug/project/node_modules/agenda/lib/agenda.js:485:7)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

I've tried to use the `mongo` config key, I've also tried db:{address:mongoConnectionString} (with auto_reconnect set to true).

**Comment by simison** [comment]
@mariokam did this get solved and can be closed?

**Comment by mariokam** [comment]
I went for paid version of MongoDB and now it looks more stable, hopefully that was the problem. Sure, close it. Thanks!

**Comment by simison** [comment]
Just leaving this here in case anyone ends up here via search: https://docs.mongodb.com/manual/administration/monitoring/
