### ISSUE TITLE
mongodb user's role

### ISSUE THREAD

**Issue by omidmaldar** [agenda/agenda#431]
Hi, 
What kinds of permission rights this module needs on MongoDB. And how we can define one in mongo? I know at least there is one: createIndex, what else?

**Comment by michelem09** [comment]
It has to read and write the DB collection created by Agenda.

**Comment by simison** [comment]
@omidmaldar I'm closing this, feel free to re-open if something is not clear.

**Comment by omidmaldar** [comment]
thanks, it's clear
