### ISSUE TITLE
agenda._db is getting undefined. 

### ISSUE THREAD

**Issue by medaamarnadh** [agenda/agenda#434]
Hi I am using agenda 0.9.1 version on Nodejs 6.9.5.

I had written some code as below.

```agenda = new Agenda({
  db: {
    address: props.agendadb,
    collection: props.agendaJobCollection
  }
});

agenda._db.update({
    '$and': [{
      'lockedAt': {
        '$exists': true,
        '$ne': null
      }
    }, {
      'name': {```

In the above program agenda._db is getting undefined. But It worked on agenda 0.6 on node 0.10.38 version. 

Can any one please help me to solve this issue.?

**Comment by manojchandrashekar** [comment]
Perhaps the MongoDB connection is not established yet. Try wrapping your code within `agenda.on('ready', () => { ... });`

**Comment by simison** [comment]
@medaamarnadh did @manojchandrashekar tip help?

**Comment by medaamarnadh** [comment]
@simson I have solved the issue on the same day when I raised the issue.  I have done in the same way but used ES5 format.
