### ISSUE TITLE
Multiple workers process the same Job

### ISSUE THREAD

**Issue by Hyra** [agenda/agenda#436]
I have tried several things, but I can't seem to get multiple workers to work correctly.

One process will create a lot of jobs, and then I have a worker process processing those jobs (takes about 2 seconds per job).

I have scaled the worker process to 2, but i see that both workers process the same jobs, as if the locking doesn't work. 

Does anyone have an example on how to make sure each worker reads from the same job pool but doesn't process a job that's already being handled by another consumer?

**Comment by manojchandrashekar** [comment]
Hey @Hyra - I created multiple workers for my queue and it is working as expected for me. Each job is picked by one of the workers only.

Note: I had both workers running on the same machine. Are yours spread across a network?

**Comment by michelem09** [comment]
I have an Agenda with 8 different servers running jobs concurrently without any problems, check your code that's not a regular behaviour.

**Comment by manojchandrashekar** [comment]
@michelem09 Thanks for confirming. I'm about to deploy a similar setup.

**Comment by moar55** [comment]
@michelem09  I ran two servers where one will get the job called and I see only one of the two servers executing the tasks. If I reduce the locklifetime both executes but some jobs are executed more than once(i.e: the two servers would do the sam job). Can you please tell me how is your setup laid out?

**Comment by simison** [comment]
@moar55 ensure you're calling `done()` at the end of task, otherwise it won't unlock.

As this is working as expected and [docs](https://github.com/agenda/agenda#multiple-job-processors) seem pretty decent for this, I'll close for now.

@Hyra feel free to re-open if you still have issues / questions!
