### ISSUE TITLE
Question: Schedule and repeat

### ISSUE THREAD

**Issue by alexbeletsky** [agenda/agenda#44]
I need to have a job, that scheduled for particular time.. but then repeated again next time. Something like

``` js
agenda.schedule('every saturday 12:00', 'send email');
```

So, it would run **every** saturday 12:00. Is it possible to do that?

**Comment by adamsoffer** [comment]
@rschmukler is it still possible to schedule and repeat with today's syntax? I noticed `scheduleAt` has been deprecated.

**Comment by amilcar-sanchez** [comment]
I think is possible with **repeatAt(time)** yo can se an example in the documentation
