### ISSUE TITLE
Priority of specific job

### ISSUE THREAD

**Issue by DVassilev** [agenda/agenda#440]
Hey, is it possible to set the priority of a specific job not all jobs of that job type? For example, when doing .now() to specify high priority so it gets executed before other .now() jobs that may have been scheduled but not yet performed.

**Comment by michelem09** [comment]
I think `job.priority()` changes the priority of that specific job only.

https://github.com/rschmukler/agenda#prioritypriority

**Comment by niftylettuce** [comment]
This is definitely a bug cc @simison - you can't specify `priority` in `data`.

Perhaps we should add support here <https://github.com/agenda/agenda/blob/162e6625dc4b446c4eda617a2eae42a0fa3ffdf9/lib/agenda.js#L222> for detecting `_priority` or `priority` in the `data` object.

**Comment by niftylettuce** [comment]
Added support in #464 for this.
