### ISSUE TITLE
Agenda Logo

### ISSUE THREAD

**Issue by michelem09** [agenda/agenda#442]
Hello,
if someone has some spare time and with a very low priority, what do you think about looking at an official  logo for Agenda (and for Agendash too)?

If you have some ideas we could share them here.

**Comment by simison** [comment]
Here are three one minute sketches for something that would probably fit both:

---

![image](https://user-images.githubusercontent.com/87168/27223987-8b70616c-529b-11e7-8417-c9b9ef7af888.png)
Vote: :tada:

---

![image](https://user-images.githubusercontent.com/87168/27223990-92754752-529b-11e7-9cd7-4eb5b64e7a8c.png)
Vote: 😄 

---

![image](https://user-images.githubusercontent.com/87168/27223995-99991536-529b-11e7-82f8-5c702db872e9.png)
Vote: :heart:

**Comment by simison** [comment]
@joeframbach sorry to bother with such a small thing — could you upload this photo:

![image](https://user-images.githubusercontent.com/87168/27421930-221bae08-5735-11e7-96a5-aa6932659d0f.png)

...to here:

https://github.com/organizations/agenda/settings/profile

Thanks! 🌼

**Comment by joeframbach** [comment]
I didn't see this thread until now. Holy moley that's a great logo. Thanks for putting so much effort into this!

**Comment by michelem09** [comment]
We could put them also in each README. Could you manage this?

**Comment by simison** [comment]
@michelem09 I can do at some point.

@joeframbach thanks, it was reeeeally quick, literally less than 5mins. ;-)

**Comment by simison** [comment]
Oh and @agenda/maintainers remember to change your status to "public" from https://github.com/orgs/agenda/people ;-)
