### ISSUE TITLE
Define a job but don't start when the server restarts

### ISSUE THREAD

**Issue by kokno** [agenda/agenda#444]
Hello,

I would like to define a new job with a given interval but I don't want that the job launch when my server restarts. If I remove the agenda.start(), it doesn't work and if I leave it, the job is scheduled but it is launch when I restart the server.

How can I do it ?

Here's my code :
```
agenda.define(modules[i].name, function (job, done) {
   console.log(modules[i].name+ " -> cron");
   config.findOne({}, function (err, conf) {
       try {
           eval(fs.readFileSync('modules/'+modules[i].name+'/'+modules[i].name+'.js')+'');
       } catch (e) {
           if (e instanceof SyntaxError) {
               console.log(e.message);
           } else {
               throw( e );
           }
       }
  });
  done();
});
...
agenda.every(cron, modules[i].name);
agenda.start();
console.log("Scheduler started!");
```

**Comment by joeframbach** [comment]
`every` can also take a [cron format string](http://www.thegeekstuff.com/2009/06/15-practical-crontab-examples).

    agenda.every('3 minutes', 'delete old users');
    
    // Alternatively, you could also do:
    agenda.every('*/3 * * * *', 'delete old users');

This allows you to define the exact time and schedule.

**Comment by kokno** [comment]
I found the problem. I was cancelling the job before defining the job. But if a job is not defined (or cancelled), the job start at the beginning (so every time in my case)
