### ISSUE TITLE
main job runs child jobs

### ISSUE THREAD

**Issue by stolendog** [agenda/agenda#447]
I have the main job which runs constantly every 1 minute. It runs other jobs using agenda.now('other_job'). I don't want to run the main job again while other child jobs aren't finished. I set different priorities for main job(low) and child jobs(high), but still the main job runs every 1 minute despite there are queued/not-finished child jobs.  How can I solve this case?

**Comment by manojchandrashekar** [comment]
Can you not check the DB if there are any child jobs running before invoking them?

```
MainJob:
  Check DB if child jobs are still running
  if true
    don't start any more child jobs
  else
   start a child job
```

**Comment by stolendog** [comment]
I was thinking the same. What is the right way to check is job still running or not? any ideas?
I was thinking about to check if property lastFinishedAt exist in job attrs object?

**Comment by michelem09** [comment]
Agendash checks when lastRunAt is greater than lastFinishedAt so you could use something like this:

```
agenda._collection.aggregate({ $project: { running: { $gt: ['$lastRunAt', '$lastFinishedAt'] } } }, function(err, jobs) {
   // Do something
});
```
Of course you can add your own filters like per job definition name.

**Comment by stolendog** [comment]
@michelem09 thanks!
