### ISSUE TITLE
Better code linting

### ISSUE THREAD

**Issue by OmgImAlexis** [agenda/agenda#455]
I noticed that eslint isn't a dev dep and that eslint isn't actually setup to lint any files even though we have a `.eslintrc`. Personally I'd go for switching to [xo](https://github.com/sindresorhus/xo) which is built on top of eslint and works out of the box without needing any config.

Either way we should turn on linting for the travis build.

PING @agenda/maintainers

**Comment by simison** [comment]
Ready for 1.0.0 with this?

**Comment by OmgImAlexis** [comment]
Yep I'm good with releasing `1.0.0` now if you want?

[History](https://github.com/agenda/agenda/blob/master/History.md) looks good according to the [milestone](https://github.com/agenda/agenda/milestone/4).

**Comment by simison** [comment]
Yep good for me!

After that Agendash might need some slight refactoring.
