### ISSUE TITLE
Jobs aren't removed from the queue when cancelled

### ISSUE THREAD

**Issue by lushc** [agenda/agenda#461]
## Problem
By default, Agenda will query the database every 5 seconds to check for jobs to process. It will fill the queue with jobs that are due to run before the next scan at time ("now" + 5 seconds). However,
 [cancel](https://github.com/agenda/agenda#cancelmongodb-native-query-cb) only removes jobs matching the query from the database and doesn't account for jobs that have already been queued. By using a higher `processEvery` interval (e.g. 1 minute) you're more likely to come across the problem of cancelled jobs still running, because they were queued before `cancel()` was called.

## Solution
We could check if the job is still in the database in `runOrRetry()` at the same point it [checks if the lock has expired](https://github.com/agenda/agenda/blob/da73bcc2cf7be7b9891d070728eda4b8ba31974a/lib/agenda.js#L652). Since the job keeps a reference to its ObjectId it would be a fast lookup:

```js
var exists = this._collection.find({_id: job.attrs._id}, {_id: 1}).limit(1).count() > 0;
```

Or, we could refactor the cancel method to first find jobs matching the query, [create jobs out of the returned values](https://github.com/agenda/agenda/blob/da73bcc2cf7be7b9891d070728eda4b8ba31974a/lib/agenda.js#L586) and then splice them out of the `_lockedJobs` array. However, we'd most likely need to manage a flag to "pause" the job queue while a cancellation is in progress, otherwise, I think there's a potential race condition where a job to be cancelled could be executed or requeued.

While the former solution results in more database queries as the check happens every time a job is due to run, it'll be less error prone and shouldn't have much of a performance impact. Thoughts?

**Comment by niftylettuce** [comment]
This is also similar to #401

**Comment by simison** [comment]
@lushc wanna move this over to #401 so that we wouldn't have duplicate issues?

**Comment by lushc** [comment]
@niftylettuce @simison thanks, I missed that issue, let's move over to that one.
