### ISSUE TITLE
Add promise support and deprecate callbacks

### ISSUE THREAD

**Issue by OmgImAlexis** [agenda/agenda#470]
For starters this would help with the tests being nested 4+ levels deep.

For example.

```js
  afterEach(done => {
    setTimeout(() => {
      jobs.stop(() => {
        clearJobs(() => {
          mongo.close(() => {
            jobs._mdb.close(done);
          });
        });
      });
    }, 50);
  });
```

Ref for my own use later on: https://futurestud.io/tutorials/callback-and-promise-support-in-your-node-js-modules

**Comment by OmgImAlexis** [comment]
So looks like we just need to wrap the `return this` in a promise that resolves `this`.

```js
module.exports = function() {
    const self = this;

    return new Promise(resolve => resolve(self));
};
```

**Comment by OmgImAlexis** [comment]
This allows both of these to work.

```js
const agenda = new Agenda();

agenda.cancel().then(async agenda => {
   console.log('cancelled') ;
   
   await agenda.stop().close();
});
```

```js
const agenda = new Agenda();

agenda.cancel(() => {
   console.log('cancelled') ; 
   
   agenda.stop(() => {
     agenda().close();  
   });
});
```

**Comment by OmgImAlexis** [comment]
@agenda/maintainers thoughts?

**Comment by niftylettuce** [comment]
👍

**Comment by simison** [comment]
Seems like a reasonable path forward.

**Comment by OmgImAlexis** [comment]
Since all tests are passing after making this change to a few files it looks like we should be fine adding this it breaking anything.

I'd do some tests but I think we may be able to land this in `1.1.0`. 🙏

**Comment by simison** [comment]
Awesome!

**Comment by OmgImAlexis** [comment]
We should also support job definitions returning a function or a promise.

Ref: https://github.com/agenda/agenda/issues/508

**Comment by zusamann** [comment]
🙏 🎉

**Comment by elias-garcia** [comment]
Any news on promise support? It can be a very good feature if it can support promises on all methods so you can call agenda functions with async/await.

**Comment by toddhickerson** [comment]
This is a deal-breaker for me. Any update on when this will be implemented?

**Comment by OmgImAlexis** [comment]
@toddhickerson we've been working on it. https://github.com/agenda/agenda/pull/557

**Comment by simison** [comment]
@toddhickerson @elias-garcia help testing and reviewing #557 always very much appreciated to move things onwards faster!  ;-)

**Comment by simison** [comment]
https://github.com/agenda/agenda/pull/557 is now merged :tada:
