### ISSUE TITLE
Refer questions to stackoverflow?

### ISSUE THREAD

**Issue by menzow** [agenda/agenda#482]
Hey,

First of all it's great to how many people started helping out since Maintainers Needed(https://github.com/agenda/agenda/issues/414) got opened.

Would it be an idea to start closing issues labeled question? Some questions are quite old and not relevant anymore, not related to agenda or better suited for Stackoverflow. 

To keep the open issues clean it might be useful to make an assessment of the question and close it if it's not directly related to agenda. Make a nice message saying that Stackoverflow is better suited for such questions, and that the user can re-open it if they can't get an answer there.

Thanks to everyone working on this repo!
- Menzo

**Comment by OmgImAlexis** [comment]
Already way ahead of you and I'd much rather keep all questions here while we have people that know the code instead of just fobbing people off to stackoverflow.

I've already gone through and closed around 100 issues so this isn't really an issue anymore. Thanks though.

**Comment by simison** [comment]
Yep, and right now docs still need improving so it's nice to be able to have a close look to questions and see what exactly needs improving.
