### ISSUE TITLE
Locking explaination?

### ISSUE THREAD

**Issue by moar55** [agenda/agenda#495]
I am having trouble understanding the lock mechanism here. So what is meant by locking is it similar to the concept of locking on os level or exactly what?
 Also it says here in the documentation :
> Also worth noting is that if the job is queue is shutdown, any jobs stored in memory that haven't run will still be locked, meaning that you may have to wait for the lock to expire.

What does shutdown of job mean? Does this refer to a crash of the job? And again here what does the lock refer to and subsequently what does it expiry mean.
I know these might be many questions but I am quite confused here. 
Thank You.

**Comment by senser1** [comment]
Any thoughts on this question? Having some locked job issues myself as well..

**Comment by Getitdan** [comment]
It would be helpful to get some information on the mechanism.

**Comment by wootwoot1234** [comment]
@moar55 why did you close this?  Did you get an answer to this?
