### ISSUE TITLE
Dropping support for MongoDB 2.x.x

### ISSUE THREAD

**Issue by OmgImAlexis** [agenda/agenda#497]
According to MongoDB the end of life for v2.6 is October 2016 which means really we should only be supporting 3.x.x officially.

This would affect https://github.com/agenda/agenda/issues/490

PING: @agenda/maintainers

**Comment by simison** [comment]
Sure!

**Comment by simison** [comment]
Do we have anything we'd want to publish in between or should we jump directly to 2.x?

**Comment by OmgImAlexis** [comment]
I think it'd be worth it to get xo and ava support added in `v1.1.0` before jumping to `v2.0.0`.
Then we can remove MongoDB support and publish `v2.0.0`.

**Comment by simison** [comment]
@shellscape we'll push this in 2.x — reviewing #616 will speed things up! ;-)
