### ISSUE TITLE
Add 0.10.1 and 0.10.2 to History.md

### ISSUE THREAD

**Issue by simison** [agenda/agenda#511]
Just realised these are missing from [changelog](https://github.com/agenda/agenda/blob/master/History.md).

From `npm view agenda`:
```
     '0.10.0': '2017-08-08T03:13:07.938Z',
     '0.10.1': '2017-08-10T03:21:46.528Z',
     '0.10.2': '2017-08-10T03:30:44.728Z',
```

Wanna summarise the changes @OmgImAlexis ?

**Comment by OmgImAlexis** [comment]
`0.10.1` isn't installable it's a unpublished version when I accidently pushed master(1.0.0).
`0.10.2` just adds the `debug` dep.
