### ISSUE TITLE
Async Request

### ISSUE THREAD

**Issue by arthursp** [agenda/agenda#522]
I tried this : 

```javascript
var Agenda = require('agenda')
var request = require('request')

var mongoConnectionString = 'mongodb://127.0.0.1/agendaDb'

var agenda = new Agenda({
  db: {address: mongoConnectionString},
  processEvery: '1 seconds',
  collection: 'agendaJobs'
})

agenda.on('ready', function () {
  agenda.define('test', function (job, done) {
    request.get('https://jsonplaceholder.typicode.com/').on('data', function (data) {
      console.log(data.toString());
      done();
    })
  })
  agenda.every('10 seconds', 'test')
  agenda.start()
})
```

And i got : 

Error: callback already called - job test already marked complete

but I am in async mode

**Comment by michelem09** [comment]
`agenda.start()` must be called outside the event `on('ready')`

**Comment by michelem09** [comment]
Sorry I confused, the `define` must be outside:

```
agenda.define('test', function (job, done) {
    request.get('https://jsonplaceholder.typicode.com/').on('data', function (data) {
      console.log(data.toString());
      done();
    })
})

agenda.on('ready', function () {
  agenda.every('10 seconds', 'test')
  agenda.start()
})
```

**Comment by arthursp** [comment]
Same with outside

**Comment by michelem09** [comment]
Oh well the problem is also another one, you are streaming the request data (`on('data', function (data)`), while you should get it all in a shot:

```
agenda.define('test', function (job, done) {
    request.get('https://jsonplaceholder.typicode.com/', function (err, response, data) {
      console.log(data);
      done();
    })
})
```

**Comment by arthursp** [comment]
Exactly !

But anyways the function need to wait until done() call before to complete the job

**Comment by michelem09** [comment]
Request is async so job is set complete when you call done() after the full request.

**Comment by arthursp** [comment]
But why full request and not just when I want ? With Promise, i can choose when I want to resolve() ...

**Comment by michelem09** [comment]
When you want, but don't call it more then one time per job. In your initial code you was calling it each time the request received any data.

**Comment by arthursp** [comment]
So it don't cut the process :S
