### ISSUE TITLE
How to define a processing behavior that will be called on every job?

### ISSUE THREAD

**Issue by mmilkov** [agenda/agenda#523]
Hello guys. I am very interested to use agenda but I have a design problem and I don't know is it possible agenda to be used in this case.

Is it possible to make only one agenda.define that will be called from every job with every name?

I have a situations that I have many jobs. One job has many tasks. For example Job 1 has 4 tasks: 1. Check my email for new emails, 2. Re-send the new emails to other email, 3. Send push notification, 4. Delete the new emails from the first email. Job 2 has 3 tasks: 1. Check my local folder for new files, 2. Parse the new files, 3. Make an API call to somewhere with the parsed information. There can be very very very different variations that anybody can make. 

All I am trying to do is to define only one agenda.define with the whole logic in it, with the whole processing of the tasks. What I am doing right now is that I am sending an array of tasks in data object of the job and process every task with a forEach. And I need every Job to call that agenda.define that I want to create. 

Also can I create two jobs with the same name and different timings? For example I have 2 users with the same job name? When I try to create a job with the same name, it's just updating the old one.

Thank you for your time!

**Comment by simison** [comment]
I have similar setup, something along these lines:

I define three tasks:
- check unread messages
- send email
- send push notification

Then I schedule `check unread messages` to be recurring: `agenda.every('5 minutes', 'check unread messages');`.

If that logic in that task finds any unread messages, for each message it schedules two new jobs which run right away when worker is free:
```js
agenda.now('send email', jobDataForEmail, callback);
agenda.now('send push notification', jobDataForPushNotification, callback);
```

You can check my exact implementation from https://github.com/Trustroots/trustroots/blob/master/config/lib/worker.js

**Comment by simison** [comment]
Of course it gets a bit trickier if your tasks need to happen in exact order, but you didn't mention that so I'm assuming they can run in parallel.

**Comment by mmilkov** [comment]
@simison That's not my case but thank you. I find a way to do it with
```
const job = agenda.create('job', {
        name: req.body.name,
        tasks: req.body.tasks
      })
 job.repeatEvery(schedule.time).save((err) => {
        if (err) {
          throw new Error('For some reason, the job is not created!')
        } else {
          res.json({
            success: true,
            message: 'New job created!'
          })
        }
      })
```
