### ISSUE TITLE
ECONNRESET mongodb crash

### ISSUE THREAD

**Issue by andylhansen** [agenda/agenda#525]
Since I've started using agenda, my app has started crashing with this error:

> node_modules\mongodb\lib\utils.js:123
>     process.nextTick(function() { throw err; });
>                                   ^
> Error: read ECONNRESET
>     at _errnoException (util.js:1041:11)
>     at TCP.onread (net.js:606:25)
> error Command failed with exit code 1.

I am using mongoose, and I haven't experienced this error until I added in agenda.

I am setting up agenda like this:

```
const agenda = new Agenda();

mongoose.connection.once('open', () => {
  agenda.mongo(mongoose.connection.collection('agendaJobs').conn.db);
});
```

It usually runs fine for a few minutes, then suddenly crashes.

Any ideas why this would be occurring?

**Comment by addysunn** [comment]
Hi, I am facing the same issue. How did you resolve this?

**Comment by Shiroh1ge** [comment]
Having the same issue, happens randomly. I'm also using an existing connection.

**Comment by OmgImAlexis** [comment]
What version of Agenda are you running?

**Comment by andylhansen** [comment]
I am using version 1.0.3

**Comment by davesmithbis** [comment]
Same issue here.

Seems to work fine with just 1 process and no concurrency - anything more than that and i consistently get this error and the entire MongoDB instance drops too.

**Comment by andylhansen** [comment]
I have created a pull request that seeks to fix this issue.
#561

**Comment by Getitdan** [comment]
Still happens. Can somebody help?
My MongoDB is on a remote host, and this error seems to happen when I have a temporary network issue. It kills my process, and I hope it could handle the failure without doing it.

**Comment by OmgImAlexis** [comment]
Please update to `agenda@2.0.0` and if the issue persists please comment here and I'll reopen it.
