### ISSUE TITLE
Running serverless

### ISSUE THREAD

**Issue by mcaldas** [agenda/agenda#530]
I know agenda is meant to work on "real" server, but nowadays "serverless" architectures are trending.. 
So my question is if there is a way to use agenda in a serverless environment, where "functions" are only allowed to run for a short time.
Thanks!

**Comment by w01fgang** [comment]
In the serverless environment, you can use scheduler of the platform you use.
AWS, Azure, Webtasks and etc., all of them have a cron like scheduler.

**Comment by giuseppecastaldo** [comment]
> I know agenda is meant to work on "real" server, but nowadays "serverless" architectures are trending.. So my question is if there is a way to use agenda in a serverless environment, where "functions" are only allowed to run for a short time. Thanks!

#1581
