### ISSUE TITLE
MongoDB connection is not recoverable (jest, mongoose connection)

### ISSUE THREAD

**Issue by v1adko** [agenda/agenda#531]
**Version**: 1.0.0
**OS**: MacOS Sierra (10.12.6)
**Stack**: [Gist](https://gist.github.com/v1adko/217e1bba4880516ed305184b73dd6eb0)

Hello everyone. I'm having an issue and it may be a **bug**.

I'm doing integration testing with [jest](https://github.com/facebook/jest), and before each test suite I start a server and after all tests have passed I shut it down. In that process `connection.close()` is called an after that I get a `MongoDB connection is not recoverable` error and my tests exit with code 1 (fail). I would like to tell agenda not to attempt reconnecting while testing. Or maybe there's another way to fix this?

I've tried following the instruction [from here](https://github.com/agenda/agenda#recovering-lost-mongo-connections-auto_reconnect), but neither combination of the parameters made it go away.

Maybe this will help clear things out.

I'm initializing agenda with an existing mongoose connection in a such way (I am sure that it is established before agenda inits).
```javascript
const agenda = new Agenda({
 db: {
    collection: 'crons'
  },
  processEvery:  '0.2 seconds',
  mongo: mongoose.connection
});
```

And I init mongoose connection like this:
```javascript
const mongoOptions = {
  useMongoClient: true,
  autoReconnect: false,
  reconnectTries: 0
}
...
mongoose
      .connect(uri, mongoOptions)
      .then((connection) => {
         ...
      })
...
```
Omitting either or both `autoReconnect` and `reconnectTries` does not help.
Am I missing something or is it a bug?

**Comment by v1adko** [comment]
@simison Hi, sorry to ping you like that. Maybe you can give me a heads up? If it's not a bug, then I'll move to stackoverflow :) I think there's definitely some confusion in docs about that thrown error, and the conditions surrounding it.

**Comment by v1adko** [comment]
OK, looks like I've figured it out. Logically after all tests have passed and I shut down the server we'd want agenda to stop too (when the connection closes). 

Solved it by adding a conditional listener
```javascript
if (process.env.NODE_ENV === 'test') {
    mongoose.connection.once('close', () => agenda.stop());
}
```

Not sure if it's the best way to do this, but it's a good workaround.
Closing this issue.

**Comment by simison** [comment]
@v1adko thanks for the ping! I've been a bit puzzled by this same issue myself as well and I'd love to figure out how to make testing Agenda stuff less error prone.

I have an [issue tracking the same problem](https://github.com/Trustroots/trustroots/issues/438) at our project.

I'd also like to have a proper close method for exactly this purpose, [see my PR](https://github.com/agenda/agenda/pull/450).

**Comment by v1adko** [comment]
Thanks for the answer. You can look how I approached this in my case. Because the connection gets reused and closed from elsewhere, listening on that event indicates when to shutdown agenda (and thus not enqueuing and locking jobs on no open connections). 

Don't like that I had to add a different logical path based on environment, not good code, but for now that's the only way I could make it work for me. But I guess that in production it's better if it throws, right? There would be other errors screaming that connection went down of course, but the more the better :)

Testing time based events is not trivial, not only agenda's issue, and having a whole another level of database complexity makes it even harder.
I use [timekeeper](https://www.npmjs.com/package/timekeeper) for my integration tests to ensure that jobs got called, but that's about it - works quite well.
The problems are with some edge cases like this one with the error.
