### ISSUE TITLE
NSP Security Update

### ISSUE THREAD

**Issue by KevinHaisol** [agenda/agenda#536]
It looks like there is a denial of service  vulnerability in agenda@1.0.0 Can you update the debug@0.7.4 package to >= 3.1.0 or know when this will be fixed?

![image](https://user-images.githubusercontent.com/25829792/31357429-eabe8ffa-acfe-11e7-91cb-45ab43d19485.png)

**Comment by OmgImAlexis** [comment]
Please update to `v1.0.1`.

**Comment by KevinHaisol** [comment]
Looks like the issue could be in date.js  I'll reach out to them for the fix.
