### ISSUE TITLE
is it possible to register new events or create functions for job?

### ISSUE THREAD

**Issue by lacivert** [agenda/agenda#538]
Simply I need to do something just before cancel the job. As the job is still alive and not completed yet, I want to cancel it but there is something more I need to do just before the stop. can I define some kind of a new event or a new function to do that in the definiton of the job?

```
agenda.define('very important job', function(job, done){
  // open a stream
  job.on("cancel", function(){
    //close stream
  });
  // close stream
});
```

**Comment by michelem09** [comment]
In the `define` you are processing the job, so simply call the `done()` before doing anything else if you want to "skip" it.
Then in the `success/fail` function delete it if skipped.

**Comment by lacivert** [comment]
Thank you and sorry that I couldn't get how to do that exactly. I am not trying to skip anything but I want to do something like a '_finally_' part of a _try-catch_ block. 'close stream' should be called before either the **completion** or **cancellation** of the job.

Can you show me that to me please? Thanks

**Comment by michelem09** [comment]
There's no cancellation once a job is in define processing method (is started). Call "close stream" before the done() or please give me more code to understand your needs.

**Comment by lacivert** [comment]
```
agenda.define('listen to incoming emails', function(job, done){
            var credentials = job.attrs.data;
            var mailListener = new MailListener(credentials);

            mailListener.start(); // start listening

            // stop listening
            //mailListener.stop();
});

// .. some any other code, now start listening mails:

agenda.now('listen to incoming emails', {username: 'mail@example.com', password: 'secret'});

// .. some any other place, call stop to listening!

agenda.jobs({name: 'listen to incoming emails'}, function(err, jobs) {
            var job = jobs[0];
            job.remove(function(err) {
                if(!err) console.log('Successfully stop??');
            });
});
```

The job should not be completed unless programmatically call it stop somehow. When it gets the stop sign (like interrupt), job should stop the mailListener by calling `mailListener.stop();`

**Comment by michelem09** [comment]
I think your approach is wrong, Agenda is a "one-shot" job processing, it can't handle a job "forever" and then stop it, it's not its job (no pun intended).

**Comment by lacivert** [comment]
Thank you very much. Is there any other idea for 'listen to mails until a time' in the agenda style?

**Comment by michelem09** [comment]
I think instead of _listening_ to an email account you should _read_ an email account.
Define a job to do a one-shot function to read an email account and let it repeat X times/day (don't know what you have to do with it).
This could be done easily  with Agenda.

**Comment by simison** [comment]
Do you need this for production or for development?

For development I've been using http://danfarrelly.nyc/MailDev/ to catch emails during testing.

For production I recommend using some relay service, which could send you events over HTTP when you get emails. Handling emails (and mail servers) manually is PITA... Personally I quite like Sparkpost for this stuff: https://developers.sparkpost.com/api/relay-webhooks.html

**Comment by lacivert** [comment]
@michelem09 & @simison  Thank you very much for the answers.

@simison , for both. I checked MailDev but it looks like a server more than a client. And yes, all the receiving email stuff is PITA 😄 I am going to check the link. Thanks again

**Comment by simison** [comment]
@lacivert yeah, Maildev a server/client/UI, handy for testing and definitely not meant for production. ;-)

**Comment by michelem09** [comment]
I think @simison suggestion (Sparkpost) is the best one, use an http webhook each time you receive an email, better then polling the email account continually.
Closing this, but feel free to add comments.
