### ISSUE TITLE
Agenda -> date.js@0.3.1 -> debug@0.7.4

### ISSUE THREAD

**Issue by KevinHaisol** [agenda/agenda#539]
FYI:
I submitted a bug request for the npm-package your using date.js@0.3.1 https://github.com/matthewmueller/date/issues/84 but I haven't heard back on the library updating the debug@0.7.4 library and it doesn't look like there has been any activity on that library for over 6 months.  

Not sure if you can contact them as well, or perhaps update to a different date npm library, but running a security scan on the Agenda package reveals a vulnerability until the date.js package gets fixed or replaced.

![image](https://user-images.githubusercontent.com/25829792/31617917-bcbb1c1e-b24d-11e7-8512-d5f0c562227f.png)

**Comment by OmgImAlexis** [comment]
[The last update was literally in the last few days](https://github.com/agenda/agenda/commits/master)..?

I'll check the deps today and bump them all we only just bumped everything because of another security issue a week or two ago.

**Comment by OmgImAlexis** [comment]
Closed in https://github.com/agenda/agenda/commit/65159172b34b9a1344814619c117474bcc323f8d

**Comment by KevinHaisol** [comment]
Cool, thanks
