### ISSUE TITLE
Is there a way to provide data to a done() job ?

### ISSUE THREAD

**Issue by jfroffice** [agenda/agenda#545]
I would like to be able to see data provided by a job done for the same reason why a job might be failed.

**Comment by ronenteva** [comment]
Sure, simply edit the `job.attrs.data` field

**Comment by jfroffice** [comment]
👍

**Comment by jfroffice** [comment]
I am getting this warning using ESLint
https://eslint.org/docs/rules/no-param-reassign

I think it is justified so why not add a method on a job to properly assign data to attrs?

**Comment by OmgImAlexis** [comment]
@jfroffice what code are you using to get that error?

**Comment by jfroffice** [comment]
`job.attrs.data = { foo: , bar: }`
