### ISSUE TITLE
High CPU usage from MongoDB

### ISSUE THREAD

**Issue by rafaelamorim** [agenda/agenda#551]
Hey guys, how's going?
First of all, i'd like to thank all collaborators for this amazing piece of work! 🥇 

I'm experiencing a very high cpu usage from mongodb. And this server/db is dedicated to agenda jobs only.
This got to be something related to indexes with unique jobs. But i tried to create those indexes and all still the same :(
So maybe i'm might have created those indexes wrongly...

I have two properties as unique keys: `{ 'data.sequence': sequence, 'data.user': user }`
What would be the correct mongodb command to correctly create proper indexes for this?

Could you guys give me some thoughts on this? README.md warns about unique indexes but there is no clue at all how to build those properly...

Ps.: this is how i'm creating my jobs:
```
agenda
      .create('trigger', [my job data])
      .unique({ 'data.sequence': sequence, 'data.user': user })
      .schedule([my schedule time])
      .save();
```

Best regards 👍

**Comment by rafaelamorim** [comment]
Contributors, some help here, please?
Best! :)

@rschmukler @simison @OmgImAlexis

**Comment by dvlsg** [comment]
I think it just depends on which fields you are using (and possibly what data is in them).

In your case, it looks like you'll want a [compound index](https://docs.mongodb.com/v3.4/core/index-compound/) on `data.sequence` and `data.user`.

**Comment by rafaelamorim** [comment]
@dvlsg thanks for your answer 👍 😃 
but we did that (back then) and nothing changed 😒 

actually we decided to drop agenda and migrate everything to bull, and now everything runs fast and smooth! 🥇 

it's too bad that an awesome project like this is abandoned 😞 

best regards!

**Comment by dylanjha** [comment]
@rafaelamorim I've been running into a some issues that I haven't been able to overcome, particularly around managing large amounts of jobs across multiple processes (#412) . I haven't seen bull before, are you happy with it?

**Comment by rafaelamorim** [comment]
@dylanjha migrate to bull ASAP!
Agenda became a nightmare (worst than Kue) for us here. And, as soon as we migrated to bull, our lives are back to normal! hahaha

!AGENDA CREATORS: keep in mind that Agenda is a great project, but its lack of support and contributors turned this into a: "remember that time that our whole system crashed down for days because of that library?". But i indeed appreciate what you guys have done here, and were very useful for a long time! Thanks!

**Comment by rafaelamorim** [comment]
I've reopened this issue, so others can be aware of what happened.

**Comment by simison** [comment]
@rafaelamorim I'm sorry you encountered high CPU but there isn't really much actionable info here to start working on. :-/

Just to note here that [bull](https://www.npmjs.com/package/bull) (backed on Redis) is a very different tool from Agenda (backed on MongoDB), but I'm happy to hear it worked well for your use case and needs. :-) It does also look like a very decent project so you should be on good hands! :thumbsup:

**Comment by simison** [comment]
Closing as a bit old support request at this point — feel free to re-open!

**Comment by smranta** [comment]
To anyone seeing High CPU issues with agenda, here'a a tip - 
Setting priority on jobs spikes CPU big time. Do not use priority if you have lots of jobs.

I had around 30k active jobs and they use to run perfectly. I created a handful of jobs with priority set, and CPU spiked big time. Because of varying priority, sort by priority in findAndModify in mongo seems to be taxing big.
