### ISSUE TITLE
how to modify the to be running job

### ISSUE THREAD

**Issue by CodingJun** [agenda/agenda#552]
Ok, recently i was troubled by some problems. How i change the to be running job, it means when the job has locked and loaded, i want  to modify it? thanks.

**Comment by AlexandruSimandi** [comment]
@CodingJun can you please tell me how you did it?

**Comment by CodingJun** [comment]
@AlexandruSimandi oh, I have been solved it, and there is nothing.

**Comment by AlexandruSimandi** [comment]
nevermind...
