### ISSUE TITLE
Question: Causes of 'Queue' Status

### ISSUE THREAD

**Issue by VincentNewkirk** [agenda/agenda#566]
When a job enters 'queued' status, as reflected by AgenDash GUI, I was told that this is because 'done' isn't being called on a job and therefore not freeing up a worker. When there are no available workers then jobs will start entering 'queued' status. 

I was wondering if there are any other reasons that a job might enter 'queued' status. We make sure to call 'done' on a job even on errors so that it doesn't tie up the worker, but every once in a while we experience all of our jobs getting 'queued'.

**Comment by joeframbach** [comment]
Do the jobs stay "queued" indefinitely? Agenda will check for queued jobs every five seconds by default, or set by the `processEvery` option. Have you set that option?

**Comment by VincentNewkirk** [comment]
yes, we have set ```processEvery('10 seconds')```
However, our jobs stay in 'queued' status indefinitely until we restart the server.

**Comment by wingsbob** [comment]
A job will stay queued if the worker which has en-queued it has too long a queue, or is taking too long to process jobs.

How many agenda instances are processing jobs, what are the concurrency & lock limits, and how long (roughly) does the job(s) take to process?

**Comment by simison** [comment]
Feel free to re-open if this is still an issue.
