### ISSUE TITLE
Job defaults to zero priority

### ISSUE THREAD

**Issue by lanzosuarez** [agenda/agenda#569]
This is my code. The saved document should have a priority of 10 right? But it defaults to zero
```
module.exports = agenda => {
  agenda.define(
    UPDATE_BOOKING_STATUS_WITH_ONBOARD_DATE_24H_FROM_NOW,
    {
      priority: "high",
      concurrency: 10
    },
    (job, done) => {
      BOOKING_JOB_NAMES.UPDATE_BOOKING_STATUS_WITH_ONBOARD_DATE_24H_FROM_NOW(
        done
      );
    }
  );
};
```

**Comment by lanzosuarez** [comment]
and btw this is the document that is being saved

![image](https://user-images.githubusercontent.com/18522203/35479365-7594fcf8-0430-11e8-9a18-7fbe8b0958a7.png)

**Comment by simison** [comment]
Feel free to re-open if new info surfaces. :-)
