### ISSUE TITLE
Call done() on failed jobs?

### ISSUE THREAD

**Issue by senser1** [agenda/agenda#572]
I'm not quite sure if I need to call done() on async jobs in the case of failure, i.e.:

```
try {
    await ...
    done();
} catch (error) {
    job.fail(error).save();
    done(); // -> is this done call required?
    throw new Error(error);
}
```

**Comment by yktv4** [comment]
@senser1 hey, you need to pass the `error` to `done` call as the first argument like that:

```javascript
done(error);
```

This marks your job as failed, populates its `failedAt`, `failReason` and `failCount` fields. The final code should look like this:

```javascript
try {
    await ...
    done();
} catch (error) {
    done(error);
}
```

**Comment by senser1** [comment]
@amhenk, @yktv4 thanks. Will update my code and post back here!

**Comment by princjef** [comment]
For reference, agenda actually calls `job.fail(err)` internally when you call `done(err)` and saves it for you, so you don't need your `job.fail(error).save()` once you switch to doing `done(err)`. The code is here if you're curious: https://github.com/agenda/agenda/blob/master/lib/job/run.js#L21

And yes you do still need to call done whenever you have an asynchronous job. Without it, agenda won't know that you're finished processing the job and it will never clear it out of the concurrency/lock limits so that another job can replace it

**Comment by dandv** [comment]
@princjef: Is Agenda supposed to also catch errors thrown from async jobs, or must the user `catch` them and call `done(error)`?

The documentation for [events](https://github.com/agenda/agenda#job-queue-events) reads

> fail - called when a job throws an error

That works for sync jobs, but not for async jobs. The snippet below triggers "Unhandled promise rejection" errors:

```js
agenda.define('sync job', { }, job => {
  throw new Error('sync job failed!');  // this *is* caught by the `fail` event
});

agenda.define('ASYNC job', { }, async (job, done) => {
  const error = new Error('ASYNC job failed!');
  done(error);  // triggers the `fail` event
  throw error;  // not caught, triggers `Unhandled promise rejection`
});


(async function() {
  agenda.processEvery('1 second');
  await agenda.start();

  await agenda.every('2 seconds', 'sync job', { }, { });
  await agenda.every('2 seconds', 'ASYNC job', { }, { });

  agenda.on('fail', (err, job) => {
    console.log(`Job failed with error: ${err.message}`);
  });
})();
```

**Comment by princjef** [comment]
@dandv it unfortunately doesn't catch these types of failures at the moment. Support has been added in #653 but it hasn't been merged yet.

**Comment by wootwoot1234** [comment]
@princjef I'm hoping your pull request is merged soon but in the meantime, do you know if this is the proper way to handle errors in `async` jobs?

My understanding is that `throw error;` doesn't work right now, you need to call `done(error);` right?

    agenda.define("update", async (job, done) => {
        try {
            // Do some stuff
            done();
        } catch (error) {
            done(error);
        }
    });

**Comment by princjef** [comment]
@wootwoot1234 yeah your understanding is correct. Any place where you may end up throwing in an `async` job handler function should be wrapped in a try/catch with a call to `done(error)` in the catch

**Comment by imsergiobernal** [comment]
Types says that done does not accept any parameter such as an Error object.
