### ISSUE TITLE
Can you stop a job processor from requesting new jobs?

### ISSUE THREAD

**Issue by Noah-Huppert** [agenda/agenda#574]
I would like to relaunch job processors safely. Without killing a job mid way through.  

Does Agenda provide a feature that would help relaunch job processors? Perhaps by stopping a processor from working on any new jobs?

**Comment by wingsbob** [comment]
Hey

My experience is that the handler needs to have a mechanism for "stopping" which can be triggered first, and will simply call `done()` without doing any work while waiting for running jobs to finish. The jobs I was working are on a 5s interval, so essentially getting skipped occasionally isn't too much of an issue.

If you need jobs to definitely be worked on on schedule, it might be an idea to try calling `agenda.maxConcurrency(0)` before trying to wind down the job processor.

Once running jobs are all finished, you can call `agenda.stop`, which will release all locks and stop locking/running jobs, but I believe this isn't entirely foolproof.

Hopefully that made some sense 😄
