### ISSUE TITLE
How to repeat job every N days at HH:MM time for a given timezone?

### ISSUE THREAD

**Issue by neemah** [agenda/agenda#576]
Hello there!

I want to provide calendar-like functionality and i thought this will work:

```js
...
const jobInterval = `${repeatDays} days at ${time}`;

job.repeatEvery(jobInterval, { timezone });
job.save(..)
```

But it does not work, job is created once and with no next run at.

Thanks in advance

**Comment by simison** [comment]
The best way to cover these would be to use cron syntax. Feel free to re-open if that doesn't solve this (though I know this is a quite old issue already now).

Agenda uses https://github.com/agenda/human-interval for human readable interval syntax so any PRs to improve this syntax should go there.
