### ISSUE TITLE
[Question] How to release a job instance when job crashed or got timeout

### ISSUE THREAD

**Issue by treecy** [agenda/agenda#578]
I found the only way to remove a running job instance from `_runningJobs` queue is to call `done()`.
But if the job got timeout or crashed and the `done()` didn't get called, this job instance will stay in 
memory forever, which means it won't be removed from `_runningJobs` queue.

Is this behaviour  supposed to be like this? And the only way to resolve it is to check 
`startedAt` in the handler manually?

Dose the only use of `lockedAt`is to retry the job?

**Comment by Seandor** [comment]
You should have the error handling function when you define a job. If the job got timeout, it should fail and  call the done function in the error handling part.

**Comment by wingsbob** [comment]
The lock will be released after the lockLifetime, which defaults to 10 minutes. `lockedAt` is used to calculate when that time has passed, but it's much better to ensure you catch any errors which occur within the job handler, and pass the error to `done(err)`.

Agenda will record the failure in the job, increment the failure count and release the lock.

I'm kinda curious how you've got a job which "times out" though 😄

**Comment by tcstory** [comment]
is there anyway to catch a timeout error?
because when a timeout occurs, i wanna to check the job, dont' want to retry the job.
