### ISSUE TITLE
TypeError: Cannot read property 'updateMany' of undefined  

### ISSUE THREAD

**Issue by pogodich** [agenda/agenda#586]
TypeError: Cannot read property 'updateMany' of undefined
    at module.exports.Agenda._unlockJobs (/node_modules/agenda/lib/agenda.js:474:20)

on lifting  server

**Comment by simison** [comment]
This will need more details:
- Mongo version
- Agenda version

Could you all run Agenda with `DEBUG="agenda:*"` to see additional details about the error?
