### ISSUE TITLE
[QUESTION] How do you make Agenda not lock scheduled jobs on servers restarts?

### ISSUE THREAD

**Issue by vladikus10** [agenda/agenda#590]
How do you make Agenda not lock scheduled jobs in the MongoDB if the server crashes or restarts? 
I want Agenda to execute any job that is passed its `nextPunAt` after restarting the server. However, instead it just locks the job and the only way I can unlock it is to set the `lockedAt` to `null`.

**Comment by vladikus10** [comment]
So it seems to happen only with very short scheduled, like scheduling something within 3-8 seconds.

**Comment by Zjcompt** [comment]
Set the lockLiftime on the job to the length of the repeatInterval. This will always insure that Agenda drops the lock at the next Interval time.

```
agenda.define('something that runs fast', {lockLifetime: 1000}, function(job, done) {});
agenda.every('1 second', 'something that runs fast');
```

 Note that this could cause issues with the job being run twice on two servers. For example if the lockLiftime is 5 secs, the interval is 5 secs, and server 1 is taking 10 secs to process it. It will become unlocked and it could be running on server 2.
