### ISSUE TITLE
Is only Mongo supported? Any plans for other key-values stores e.g. couchbase?

### ISSUE THREAD

**Issue by t0lkman** [agenda/agenda#592]
Is only Mongo supported? Any plans for other key-values stores e.g. couchbase?

**Comment by shenghu** [comment]
@rschmukler we have a consideration to converge databases, e.g. only to use cassandra. And we have been using Agenda for some time, which looks pretty good. I just want to ask if it is possible for Agenda to support cassandra?

**Comment by elyas-bhy** [comment]
See #18

**Comment by t0lkman** [comment]
closing due to possible duplicate #18
