### ISSUE TITLE
How to schedule multiple jobs for one job processor? Best practice?

### ISSUE THREAD

**Issue by duurland** [agenda/agenda#595]
**Edit: Problem solved. Turns out I didn't read the docs close enough. 
job.create() and job.repeatEvery() was what I was looking for.**

Hello, 

This library is all new to me and I'm still testing the water.

I'm in a situation where I'd like to schedule and run the same function for multiple data sets.

My first thought was to just loop through my data and register the jobs in Agenda.
```
const urls = [
  'http://example.com/1',
  'http://example.com/2',
  'http://example.com/3',
  'http://example.com/4',
  'http://example.com/5',
]

const JOB_NAME = 'ping example url';

agenda.define(JOB_NAME, function(job, done){
  // Some logics here..
  console.log(`[PING]: ${job.attrs.data.url}`)
  done()
});

agenda.on('ready', function() {
  urls.forEach(url => agenda.every('5 seconds', JOB_NAME, {url}))
  agenda.start()
});

// outputs
// [PING]: http://example.com/5
// [PING]: http://example.com/5
// [PING]: http://example.com/5
// [PING]: http://example.com/5
// [PING]: http://example.com/5
```
Turns out that wasn't possible, I assume whenever a new job with the same name and/or function is registered it overwrites the previous one? Did I miss something in the docs?

My second thought was to loop through both the function definition and job registration.
```
const urls = [
  'http://example.com/1',
  'http://example.com/2',
  'http://example.com/3',
  'http://example.com/4',
  'http://example.com/5',
]

const JOB_PREFIX = 'ping example url';

const JOB_FUNCTION = function(job, done){
  console.log(`[PING]: ${job.attrs.data.url}`)
  done()
};

agenda.on('ready', function() {
  urls.forEach(url => {
    const JOB_NAME = `${JOB_PREFIX} (${url})`;
    agenda.define(JOB_NAME, JOB_FUNCTION);
    agenda.every('5 seconds', JOB_NAME, {url})
  })
  agenda.start()
});
```
While this works, it seems counterproductive to define the same function for every data set, as my real application has way more than 5 entries and 1 function, which was used in the examples above.

What's the best way to go about this? Any input is highly appreciated!

Regards

**Comment by ldsmike88** [comment]
I implemented something similar to this:
```
const urls = [
  'http://example.com/1',
  'http://example.com/2',
  'http://example.com/3',
  'http://example.com/4',
  'http://example.com/5',
]

const JOB_FUNCTION = function(job, done){
  console.log(`[PING]: ${job.attrs.data.url}`)
  done()
};

agenda.define('ping example url', JOB_FUNCTION);

urls.forEach(url => {
  agenda.create('ping example url', { url }).repeatEvery('5 seconds').save();
});

agenda.start();
```

But just make sure you only execute the create function once for each url or you will get multiples of the same job.
