### ISSUE TITLE
[question / feature request] undefine. Remove definition of job.

### ISSUE THREAD

**Issue by elyran** [agenda/agenda#599]
Hi,

How can I remove a definition of job?
I'm looking for a `undefine()` method.

How can I do this?

The use case is simple:
I need to listen to a certain event once.

**Comment by wingsbob** [comment]
Job definitions are only held in memory, so if you stop the instance with that definition and remove all references to it, then it's gone?

If you absolutely want to just delete it, then it'll be held in `agenda._definitions[jobName]`
