### ISSUE TITLE
Job > skipImmediate Option doesn't work

### ISSUE THREAD

**Issue by cespejo93** [agenda/agenda#601]
When I install agenda from NPM the skipImmediate option on job/repeat-every isn't there.

my package.json

![captura de pantalla 2018-05-09 a las 19 30 42](https://user-images.githubusercontent.com/18526378/39829678-7c783128-53bf-11e8-92c1-c9183421637c.png)

job/repeat-every.js

![captura de pantalla 2018-05-09 a las 19 29 41](https://user-images.githubusercontent.com/18526378/39829638-5e01d334-53bf-11e8-8522-8c5fe3a53925.png)

And if I'm not wrong that is already merged in master and should be like this

![captura de pantalla 2018-05-09 a las 19 32 12](https://user-images.githubusercontent.com/18526378/39829750-b2af98bc-53bf-11e8-9f79-2715e0354698.png)

**Comment by simison** [comment]
Howdy! Correct, this change isn't published yet.

We'll update here once it goes out!

**Comment by cespejo93** [comment]
Hi again :D right now the skipInmediate option is in the documentation but the version remains the same and therefore does not work. For when is the update planned?

**Comment by simison** [comment]
Howdy!

It's planned on going out with v2.0.0 which should go out soon, this week hopefully. 

Sorry for the wait. :-)

**Comment by Flo-Slv** [comment]
Hello! Is there any news about skipImmediate option? Thanks

**Comment by cespejo93** [comment]
still waiting for lib update 😢

**Comment by simison** [comment]
Hello everyone!

Agenda v2.0.0 was just published to enjoy together with `skipImmediate` option. Sorry it took a while, but this release had a ton (it's a big rewrite).
