### ISSUE TITLE
Agenda.now is not a function error

### ISSUE THREAD

**Issue by kamdickens** [agenda/agenda#602]
I am testing out automating an email to be sent to me everytime my app restarts, and I am getting a `agenda.now is not a function` error when trying to launch the application.

My app.js is as follows:
```
var agenda = require('./worker.js');
agenda.now('new version email');
```

worker.js:
`require('./lib/agenda.js');`

./lib/agenda.js:
```
var Agenda = require('agenda');

var connectionString = "mongodb://" + process.env.MONGODB_USER + ":" +
  process.env.MONGODB_PASSWORD + "@" +
  process.env.DATABASE_SERVICE_NAME + ':' +
  process.env.MONGODB_PORT + '/' +
  process.env.MONGODB_DATABASE;

 var agenda = new Agenda({db: {address: connectionString}});

 var jobTypes = process.env.JOB_TYPES ? process.env.JOB_TYPES.split(',') : [];

 jobTypes.forEach(function(type){
 	require('./jobs/' + type)(agenda);
 });

 if (jobTypes.length) {
 	agenda.on('ready', function() {
 		//Schedule specific jobs
 		agenda.every('one day', 'inactivate users')	//Run job every day
 		agenda.processEvery('five minutes')
 		agenda.start();
 	})
 }

 module.exports = agenda;
```

This seems to reflect the example project structure, so I'm confused as to why this isn't working. Any ideas?

EDIT: I just tried swapping agenda.now for agenda.schedule and am getting the same error

**Comment by kamdickens** [comment]
I should add I am using v1.0.3

**Comment by CNaismith** [comment]
@kamdickens 

Are you exporting your agenda object in worker.js? Otherwise you won't have any access to the object in app.js

**Comment by kamdickens** [comment]
Manged to get it to work.

If I call agenda.now in my app.js it won't work ( I get the above property of undefined error). But if I call it from other routes, it works.

If anyone can explain why that would be fab, but seem to have got it working now

**Comment by radvansky-tomas** [comment]
Same here, example worker.js is wrong. Could you provide updated docs?

**Comment by radvansky-tomas** [comment]
ok it should be

`const agenda = require('./agenda/agenda');
module.exports = agenda;`

**Comment by radvansky-tomas** [comment]
But still how then reference agenda in your express app...because if I do require worker.js it will run agenda again...as another instance

**Comment by shitalvaluepitch** [comment]
call agenda just before using it
that is above
agenda.now('registration email',{.....})
