### ISSUE TITLE
skipImmediate does not work with agenda.every syntax

### ISSUE THREAD

**Issue by karthikiyengar** [agenda/agenda#610]
Using master.

The following works as expected
```
const test = agenda.create("test_repeat", { data: "test" })
test.repeatEvery("1 month", { skipImmediate: true }).save()
```

Although, the following doesn't
```
const job = await agenda.every(
      "1 month",
      "test_repeat",
      { data: "test" },
      { skipImmediate: true },
    )
```

Looks like an issue in relaying the options to the underlying `repeatEvery`

**Comment by simison** [comment]
PRs most welcome for this one!

**Comment by simison** [comment]
https://github.com/agenda/agenda/pull/861 fixed this. If anyone would like to check if docs need updating, that would be ace!
