### ISSUE TITLE
How to run jobs in series ?

### ISSUE THREAD

**Issue by pravin-d** [agenda/agenda#617]
I have a bunch of jobs, each job does some manipulation to a mongo collection. This activity is async as we all know. When I start a job and it does a call to mongodb, the next gets called. As each job is unique, can have different number of async calls within it and possibly end up manipulating the same collection I would like to run the jobs in series.
As in I want to agenda to wait for each job to be finished before starting another. How to implement the same ?

**Comment by wingsbob** [comment]
So, you have some jobs (lets call them A, B and C).

You create job A at some point, and want that to run to completion, then for job B to run on the same data, followed by job C?

I guess you could have A schedule B when it finishes, and B schedule C when it finishes, though personally I'd probably just make a single job which does all of these things 😄
