### ISSUE TITLE
Job fires right after it is registered and on restarts

### ISSUE THREAD

**Issue by fsamir** [agenda/agenda#627]
Hi,

recently I upgraded Agenda from a very old version to v1.0.3 and when I create a new job, regardless of the time it is supposed to run, it always runs right after registration. Any scheduled job will also run when the application restarts.

Can someone point me the potential places that my code could no longer be compatible with the latest version?

Here is how I am registering jobs:
```
        var jobData = {
            pumpId: 1
        };

        var expression = 'at 10:30';
        var job = this.agenda.schedule(expression, JOB_NAME, jobData);
```

Thanks

**Comment by wingsbob** [comment]
Hey @fsamir 

I've had a look through the code, and played around trying to reproduce: https://github.com/wingsbob/agenda-schedule-bug

I'm not able to observe the issue you describe 😞 

Could you provide any additional information to help me track down what's going on? Ideally, could you provide a code sample which demonstrates this?

**Comment by fsamir** [comment]
Hey @wingsbob 
I think I found what I was doing wrong. I was building the `expression` without padding hour and minute and eded up with some like these:
`at 10:9`, `at 9:32` 

I add the padding zero and it now works: `at 10:09`, `at 09:32` 

There isn't a good chance those weren't working even before the upgrade and I only noticed it now.

Thanks
