### ISSUE TITLE
Support for mongo-compatible databases such as NeDB

### ISSUE THREAD

**Issue by jay-jlm** [agenda/agenda#628]
Any plans to support this feature?
I figure that for some uses linking to a "real" database would be overkill, so a file-based one such as [Nedb](https://github.com/louischatriot/nedb) would could be a more convenient solution.

**Comment by PabloReszczynski** [comment]
I had a look on Agenda implementation and mongo is very intertwined in the code, so changing it to another db, even if it shares the same interface is a tough job.

**Comment by simison** [comment]
No current plans.

I think Agenda works best as a _MongoDB_ job scheduler. 

There are some great alternatives out there for databases like Redis, so it doesn't make necessarily sense to reinvent the wheel. Adding additional databases would add quite a lot of maintenance overhead.

**Comment by simison** [comment]
Closing and recorded this wish at https://github.com/agenda/agenda/issues/18#issuecomment-406516161
