### ISSUE TITLE
Feature: Preserve history for each time job runs (for reoccurring jobs)

### ISSUE THREAD

**Issue by fzondlo** [agenda/agenda#645]
Thinking of making a PR for this if it's something the you guys would be interested in merging.

**TLDR:**
Add configuration to allow users to enable job history. Once enabled, the success or failure of each job would be stored in the job object persisted in mongo. Would then open a PR in agenda dash to allow for easy viewing of the history through the UI.

**Modification to the object stored in mongo**
From:
```js
{
  "_id": ObjectId("5b3a4cb63c0e9b0236686b58"),
  "name": "jobName",
  "type": "single",
  "data": null,
  "priority": 0,
  "nextRunAt": ISODate("2018-07-05T20:21:00.758Z"),
  "repeatInterval": "0 */2 * * *",
  "repeatTimezone": null,
  "lastModifiedBy": null,
  "lockedAt": ISODate("2018-07-05T20:20:28.753Z"),
  "lastRunAt": ISODate("2018-07-05T20:20:28.758Z"),
  "lastFinishedAt": ISODate("2018-07-05T20:18:46.799Z")
}
```
To:
```js
{
  "_id": ObjectId("5b3a4cb63c0e9b0236686b58"),
  "name": "jobName",
  "type": "single",
  "data": null,
  "priority": 0,
  "nextRunAt": ISODate("2018-07-05T20:21:00.758Z"),
  "repeatInterval": "0 */2 * * *",
  "repeatTimezone": null,
  "lastModifiedBy": null,
  "lockedAt": ISODate("2018-07-05T20:20:28.753Z"),
  "lastRunAt": ISODate("2018-07-05T20:20:28.758Z"),
  "lastFinishedAt": ISODate("2018-07-05T20:18:46.799Z")
  "previousRuns": [
     { 
       "startedAt": ISODate("2018-06-05T20:20:28.758Z"),
       "finishedAt": ISODate("2018-06-05T20:18:46.799Z")
     },
     { 
       "startedAt": ISODate("2018-05-05T20:20:28.758Z"),
       "finishedAt": ISODate("2018-05-05T20:18:46.799Z")
     },
  ]
}
```

To enable this I envision something like:

```js
const agenda = new Agenda({db: {address: mongoConnectionString}, saveHistory: true});
```

Have also thought about having a "maxHistories" flag, eg:

```js
const agenda = new Agenda({db: {address: mongoConnectionString}, saveHistory: true, maxHistories: 60});
```

As a phase 2 if there is interest.

Thanks for your consideration!

**Comment by rconstantine** [comment]
Some kind of history would be great.

**Comment by jloveridge** [comment]
History should definitely be in a separate collection. If you have a job that runs frequently it is conceivable that you would surpass the 16MB document limit for MongoDB. Unbounded data is an anti-pattern.

If this were to be implemented I would personally want to be able to configure it either for the entire agenda instance or for a specific job definition.

Perhaps something like:
```js 
const agenda = new Agenda({db: {address: mongoConnectionString}, historyCollection: 'agendahistory'});
```

Or for a per, job history:
```
const agenda = new Agenda({db: {address: mongoConnectionString}});
agenda.define('job with history', {historyCollection: 'historicalresults'}, (job) => {
});
```

**Comment by simison** [comment]
I'd say Agenda shouldn't do its own logging, especially within the recurring job itself for reasons already mentioned.

Would defining your own logging in each job do the job better? You could then use something else than MongoDB for it, too.

Another consideration is to run a job that cleans out finished jobs from the DB and transfers them to a different collection.

Hope this helps!
