### ISSUE TITLE
Suggestion: Add support for findOne/limit/sort rather than just find with the Agenda.Jobs() function

### ISSUE THREAD

**Issue by edwin-jones** [agenda/agenda#649]
Currently I'm trying to find and modify the most recent version of a job _(all with the same name but different data)_ by looking for the most recent `lastRunAt` value. The `agenda.jobs()` function will return **all** jobs that match and doesn't allow sorting or limiting.

Could we add a function that lets you pass in a limit and sort query rather than just a find query please? It would be really helpful because at the moment I have to use `agenda._collection` to call `find()` myself which breaks the elegance of the library and the abstraction of the data layer. 

I am happy to take a stab this myself if you are open to random PRs. Thanks!

**Comment by simison** [comment]
We'd love to see a PR for this. :-) Feel free to join our Slack channel (link in the readme) if you need any assistance!

**Comment by edwin-jones** [comment]
I made a PR for this a while ago - #665.

**Comment by SammyHam** [comment]
It'll be a lovely to have this PR validated :)
