### ISSUE TITLE
Update docs for `agenda.jobs()`

### ISSUE THREAD

**Issue by uriya2** [agenda/agenda#651]
hi, 

I know I can do the following:
`
agenda.jobs({name: 'printAnalyticsReport'}, (err, jobs) => {
  // Work with jobs});
`
but how to retrieve a value (such as the jobs list, jobs.length..) from the callback? for example:
`const jobsLength = agenda.jobs({name: 'hello'}, (err, jobs) => {return jobs.length});`
Is it even possible?

Thanks

**Comment by edwin-jones** [comment]
Version 2.0 of agenda uses promises, so you could just do:
```js
let jobs = await agenda.jobs({name: 'printAnalyticsReport'});
let jobCount = jobs.length;
```

**Comment by tcstory** [comment]
but the readme  still use the callback style, pls fix it

**Comment by simison** [comment]
Docs: https://github.com/agenda/agenda/tree/0840588935edfb79c49b8f47f3d76083d7836f8d#managing-jobs

**Comment by sampathBlam** [comment]
@simison : The docs for `agenda.jobs()` seems to have been updated with the new promises syntax (https://github.com/agenda/agenda/tree/master#jobsmongodb-native-query-mongodb-native-sort-mongodb-native-limit). Can this issue be closed?

**Comment by simison** [comment]
Sure, thanks for the heads up!
