### ISSUE TITLE
mongodb in dependencies not matching 3.1.1

### ISSUE THREAD

**Issue by faller** [agenda/agenda#659]
https://github.com/agenda/agenda/blob/1e6e4a608eb316368abbb6803690ce6b4b0aedd6/package.json#L45

~3.1 is not matching 3.1.1 in Yarn，3.1.0 sucks https://github.com/mongodb/node-mongodb-native/pull/1778

**Comment by OmgImAlexis** [comment]
`3.1.1` isn't been tagged as latest. You'll need to open an issue on their end.

**Comment by simison** [comment]
Seems resolved: https://github.com/mongodb/node-mongodb-native/pull/1778#issuecomment-406579630
