### ISSUE TITLE
Limiting rate on given jobs for API calls

### ISSUE THREAD

**Issue by marcoschwartz** [agenda/agenda#668]
Hello,

For my Node.js application I need to run jobs that are calling APIs that I have a maximum call rate (for example one call every 5 seconds maximum). On the other hand, I also need to execute other jobs that can be run in parallel and that don't need to be rate limited. Is there a way to do that with agenda? Thanks!

**Comment by wingsbob** [comment]
Hey

When you define a job, you can set the concurrency level for that job in the options. Just bear in mind that that limit will only apply to a single instance of agenda, so if you're scaling horizontally, or using multiple instances, each will have their own concurrency limit.

Hope that helps 😄

**Comment by dandv** [comment]
@marcoschwartz: did you manage to solve this?

I've also just added an example that illustrates concurrenct in #794.

Closing for now, feel free to chime in.
