### ISSUE TITLE
Schedule and time relative

### ISSUE THREAD

**Issue by clementvp** [agenda/agenda#671]
I'm in Europe (Paris time zone so, now it's +2)

I use momentJs to format my date.

If I want my job executing today, in 10 minutes

```
var date = moment().add(10,'m').format()
agenda.schedule(date, 'hello world')
```

But the job is fire right instantly and not in 10 minutes after.

same thing if I write manually the date

```
agenda.schedule('2018-07-30T15:55:05+02:00', 'hello world')
```

the job is fire instantly.

Very very annoying!

But if i write 
```
agenda.schedule('in 10 minutes', 'hello world')
```
That's work. 
I don't want to write the interval time, i want to use a Date.

**Comment by edwin-jones** [comment]
Sounds like the default timezone is off somehow. Here's a few questions to break it down:

1) What system are you running on? (container, remote host, VM, local desktop?)
1) What is the output of moment().format() on your system?
1) What is the time zone of that system? Is it set to UTC? (I'd wager that may be the problem)

**Comment by clementvp** [comment]
Ok thank you for the quick reply.
The documentation lack of precision about scheduling, one example with both options string and Date must be good.

I found a workaround with this syntax

```
agenda.schedule('2018-07-30 at 15h55', 'hello world')
```
The time is my local time, and it's work.
