### ISSUE TITLE
the version 2.0.0 not even getting initialised

### ISSUE THREAD

**Issue by hemantforever007** [agenda/agenda#684]
The app is crashing as soon as i am writing the require statement for agenda.

**Comment by simison** [comment]
Hello! This isn't very useful as is, could you post some more details, please?

https://github.com/agenda/agenda#debugging-issues

**Comment by hemantforever007** [comment]
Okay, I will walk you thru the process.
1. I install a brand new express app.
2. Installed other modules as required.
3. Among them, also installed agenda jobs using "npm install agenda".
4.I tried running the helloworld program, it worked.
5. As soon as i add
                 const Agenda = require('agenda');
, the code crashes, poping out some error.

![screenshot from 2018-08-30 14-54-13](https://user-images.githubusercontent.com/4299298/44843246-7a665000-ac65-11e8-92eb-f2a822d6e70c.png)
![screenshot from 2018-08-30 14-54-13](https://user-images.githubusercontent.com/4299298/44843257-83efb800-ac65-11e8-8c0c-598f78b52a88.png)

**Comment by simison** [comment]
What's the Node.js version you're on?

```
node --version
```

Agenda requires at least 8

**Comment by hemantforever007** [comment]
v6.14.3

**Comment by simison** [comment]
😉

**Comment by hemantforever007** [comment]
Thank you for telling that but i couldn't find this dependence written anywhere.
But thanks. I used an earlier version and it worked. agenda version - 1.0.3;
:+1:

**Comment by simison** [comment]
Thanks, fair point! I just added the version requirement to `package.json` :thumbsup:
