### ISSUE TITLE
Avoid race condition between multiple instances of node-scheduler

### ISSUE THREAD

**Issue by jegankan** [agenda/agenda#685]
I am using node-scheduler for my project. The purpose of the schedule job is to process the certain records(with specific status) in mongo db. I am facing an issue. I run my project in multiple nodes(or more than one instance), which tends to trigger the scheduler at the same time and both the instances succeed in processing the same record at the same time. Looking out for information like how to run only one instances of scheduler though multiple instances of my project runs. Can agenda resolve this issue ? Pleaes guide

**Comment by simison** [comment]
Yep! Agenda is designed so that you can process jobs from multiple workers.

**Comment by vcumapathi** [comment]
@jegankan can you post your solution?
