### ISSUE TITLE
Passing both a callback and data to agenda.now() at the same time throws an error

### ISSUE THREAD

**Issue by AmrKafina** [agenda/agenda#712]
I'm trying to schedule a job to run with `agenda.now()` while passing some data to `jobs.attrs.data`:

    agenda.now('myJob', { data: data }, (error, jobSaved) => {
        if (error) {
            console.error("Error saving job: ", error);
            res.send(error);
        } else {
            console.log("The job was correctly saved!");
            res.sendStatus(200);
        }
    };

But this throws an error:
`Error: This function does not accept a callback function. 3/2`

If I run this with only the data or only the callback, it runs correctly, but passing them both throws the error.

I'm using the exact structure in `agenda.schedule()` and `agenda.every()` with the same data and callback, and everything's running fine. It's just the `now()` function. 

Am I missing something?

**Comment by noamnelke** [comment]
It [looks](https://github.com/agenda/agenda/blob/master/lib/agenda/now.js) like agenda got a rewrite with promises and the documentation wasn't updated. Callbacks are no longer accepted.

https://github.com/agenda/agenda/commit/b9ecca90916abc88c95d5f229a3fa21c7e356504#r30854923

**Comment by AmrKafina** [comment]
That was it, thanks a lot!

**Comment by joantune** [comment]
indeed - it's time to change this:

https://github.com/agenda/agenda#nowname-data-cb

**Comment by pedruino** [comment]
> indeed - it's time to change this:
> 
> https://github.com/agenda/agenda#nowname-data-cb

I agree. https://github.com/agenda/agenda/pull/831

**Comment by simison** [comment]
Docs updated 👍
