### ISSUE TITLE
Repeat every hour on the 30 min mark?

### ISSUE THREAD

**Issue by wootwoot1234** [agenda/agenda#716]
I'm trying to figure out how to schedule a task that runs once an hour on the 30 min mark.  

```
agenda.every("1 hour at 30 minutes", "check for failed messages");
```

doesn't work.  Any ideas?

**Comment by arkraft** [comment]
There is another issue which suggests that you cannot use cron in `every`: #540 
Another solution would be, to create a manual job and pass it a start time:

```javascript
agenda.create("check for failed messages")
    .schedule(moment().startOf("hour").add(30, "minutes"))
    .repeatEvery("hour", {runImmediate: false})
    .save();
```

This will schedule the first run at 30 minutes of the current hour and be repeated every hour.

**Comment by wootwoot1234** [comment]
Thanks, @arkraft.  I'm not using commas and I think that's the issue with #540.

Your code is also a good solution.  Thanks!  I think these are the two only solutions for this so I'm going to close this issue.
