### ISSUE TITLE
how do i run multiple jobs at same time

### ISSUE THREAD

**Issue by karimkhamwani** [agenda/agenda#727]
for now i've this.
    await agenda.start();
    await agenda.every('1 minute', 'send notification to expiring connections');
    await agenda.every('1 minute', 'delete expired connections');

functions execute but mess with timings?

**Comment by dandv** [comment]
Do you actually want to run the `delete expired connections` job only after `send notification` is done? In that case, the best approach is to create one job that calls the methods for both sending notifications, and deleting expired connections.

See also this [example to better understand concurrency in Agenda](https://github.com/agenda/agenda/pull/795).
