### ISSUE TITLE
Rerunning jobs after server shutdown

### ISSUE THREAD

**Issue by ghost** [agenda/agenda#74]
Hey guys, Love the library. Thank you.

I just had a question about agenda and how it saves jobs. 

does saving a job mean that onces the node server is shutdown and restarted, it will continue to process the jobs saved in the database? if not, the what is the alternate solution?

I have tried saving jobs, but after restarting my node script, it does not run my old jobs. Here is my script

```
var express = require('express')
var app = express()
var server = require('http').Server(app)
var io = require('socket.io')(server)


var Agenda = require('Agenda')
var agenda = new Agenda({ db: { address: 'localhost:27017/jobs' } })
agenda.start() // start agenda

io.on('connection', function (socket) {

    socket.on('createJob', function (data, callback) {
        var jobName = data.name;

        // create the job
        agenda.define(jobName, function (job, done) {

            // do stuff
            getReport();
            sendEmail();

            // save the job
            job.save(function (err) {
                if (!err) {
                    console.log("Saved");
                    done();
                }
            })

        })

        agenda.every('3 minutes', jobName, { data: 'random' });

    })

})

// start server
server.listen(3000, function () {
    console.log('Server started');
})
```

**Comment by Osmandiyaka** [comment]
I am facing the same issue but in my case i am using dynamic job creation. here is my use case. i am billing businesses and each business has a different billing date.For each business, the billing should repeat after every x month(which is also different for each business). at the moment this is how  am creating and stating jobs

`module.exports = async (agenda, jobName) => {
    agenda.define(jobName, (job, done) => {
        console.log('runing job with name ' + jobName);
        const { category } = job.attrs.data;
        createBill(category, done);
    });

}`
jobName will be pass from the calling code.

and this is how i start the job

` const every = `${category.billingCycle} ${category.billingCycleUnit}`;
    const billingJob = agenda.create(category.name, { category: category });
    const cycleStart = new Date(category.cycleStart);
    const now = new Date();
    const startBillingAt = (now.getTime() >= cycleStart.getTime()) ? now : cycleStart;
    billingJob.schedule(startBillingAt);
    billingJob.repeatAt(every);
    billingJob.save();`

However when the server restart the job does not start again. Hope someone can help. thanks

**Comment by raunaqkapoor** [comment]
@Osmandiyaka were you able to figure it out? I am stuck with the same issue and I am creating jobs dynamically.

**Comment by varungujarathi9** [comment]
@raunaqkapoor can you try this

- Read the job names from the MongoDB and then follow this #https://github.com/agenda/agenda/issues/74#issuecomment-51800700
(i.e. define the job function before start())

**Comment by DevanshB10** [comment]
@raunaqkapoor did you find any work around on this?

**Comment by raunaqkapoor** [comment]
> @raunaqkapoor did you find any work around on this?

@DevanshB10 can't recall for the life of me! Was 4 years back and I don't have access to that repo any longer. Sorry! Maybe try [this](https://github.com/agenda/agenda/issues/74#issuecomment-1100903082)
