### ISSUE TITLE
Executtion in fixed time or with command

### ISSUE THREAD

**Issue by amiiy** [agenda/agenda#743]
Hi. I have a couple of jobs which is creating in the daytime in my back-end. can I create this jobs with no specific execution time? my mean, the back-end only create its needed jobs which should be done since tomorrow, and as default, we have a separate process which will run all jobs at 12 pm.
if i say `await Agenda.create('someJob',{userId:12313212})` when this job will be executed? 
how can we do not provide exact execution time instead execution came with a simple command or in fixed time?

**Comment by dandv** [comment]
Now sure I understand your English accurately, but if you run `agenda.create('someJob', ...)` then `agenda.save()`, the job will be saved to the database and not yet executed. It will only be executed if you call other methods on the job, such as `schedule`, `repeatEvery`, `repeatAt` or `now`.

If you call `agenda.now('someJob')`, Agenda will execute the job at that moment (what I guess you mean by "fixed time").
