### ISSUE TITLE
how to schedule job for specific day and time i.e job should run on friday at 9:00 am

### ISSUE THREAD

**Issue by karimkhamwani** [agenda/agenda#745]

**Comment by StanSarr** [comment]
@karimkhamwani  
```
job.schedule('friday at 9:00 am');
job.save();
```

**Comment by dandv** [comment]
@karimkhamwani: this is documented outright:

https://github.com/agenda/agenda#schedulewhen-name-data-cb - for a one-time job

If you want to repeat the job every Friday at 9am - https://github.com/agenda/agenda#repeatattime

**Comment by kbiits** [comment]
> @karimkhamwani: this is documented outright:
> 
> https://github.com/agenda/agenda#schedulewhen-name-data-cb - for a one-time job
> 
> If you want to repeat the job every Friday at 9am - https://github.com/agenda/agenda#repeatattime

I'm sorry i know this issue was closed, but can you help me how to repeat the job every friday at 9am ?
I try this but it's not work

```javascript
job.schedule('friday at 9:00 am');
job.repeatAt("9:00am")
job.save();
```

and when I check the database and nextRunAt field not computed correctly

**Comment by karimkhamwani** [comment]
await agenda.every('00 00 09 * * 5', 'send notification to users who havent active on friday');
