### ISSUE TITLE
Is it possible to schedule and repeat a job?

### ISSUE THREAD

**Issue by adamsoffer** [agenda/agenda#758]
How would you go about scheduling a job to run once a week at 7:00 am? I see a method for scheduling jobs in weekly intervals using `repeatEvery` but I'm unsure how to make sure it runs at a specific time as well.

**Comment by adamsoffer** [comment]
Would this work?
```js
await agenda
    .create('email')
    .repeatEvery('week', { skipImmediate: true })
    .repeatAt('7:00am')
    .save()
```

**Comment by nemozny** [comment]
Sure, job.repeatEvery('0 7 * * *') should do it.

**Comment by adamsoffer** [comment]
Thanks @nemozny. In your example, will the job begin 7 days after being created? Or will it always start on Monday? I need it to begin 7 days after creation. I'm basically looking for a start date. It seems there have been a couple PRs created over the last couple years supporting this feature but for some reason they've never been merged.

**Comment by adamsoffer** [comment]
Sorry if I wasn't clear. I'm wondering if it's possible to schedule a job to run to run at a specific time in the future and have it repeat in intervals henceforth.

**Comment by adamsoffer** [comment]
Something along the lines of this:
```
job.repeatEvery('0 7 * * 1', {
  startDate: new Date('some future date')
});
```

**Comment by adamsoffer** [comment]
@nemozny Based on open issues and PRs related to this use case I get the impression it's a fairly common scenario. I checked out the Bull api to see if it supports it and in fact it does. Here are all the repeat options you can pass to a job using `Bull`:
```
interface RepeatOpts{
 cron?: string; // Cron string
 tz?: string, // Timezone
 startDate?: Date | string | number; // Start date when the repeat job should start repeating (only with cron).
 endDate?: Date | string | number; // End date when the repeat job should stop repeating.
 limit?: number; // Number of times the job should repeat at max.
 every?: number; // Repeat every millis (cron setting cannot be used together with this setting.)
 count?: number; // The start value for the repeat iteration count.
}
```

Notice the `startDate` option.

**Comment by dandv** [comment]
> I'm wondering if it's possible to schedule a job to run to run at a specific time in the future and have it repeat in intervals henceforth.

Yes:

```js
const job = agenda.create('say', { message: 'foo' });
job.schedule('in 5 seconds').repeatEvery('2 seconds');
job.save();
```

Output:
```
01:22:50 Agenda started
01:22:55 foo
01:22:57 foo
01:22:59 foo
01:23:01 foo
...
```

@nemozny:

> I think this is quite a simple and unlikely scenario

I think that scheduling a start time and a repeat frequency is a very common scenario. That's how jobs like "send morning news email" need to work.

**Comment by adamsoffer** [comment]
Thanks @dandv 🙂

**Comment by shresthabijay** [comment]
> > I'm wondering if it's possible to schedule a job to run to run at a specific time in the future and have it repeat in intervals henceforth.
> 
> Yes:
> 
> ```js
> const job = agenda.create('say', { message: 'foo' });
> job.schedule('in 5 seconds').repeatEvery('2 seconds');
> job.save();
> ```
> 
> Output:
> 
> ```
> 01:22:50 Agenda started
> 01:22:55 foo
> 01:22:57 foo
> 01:22:59 foo
> 01:23:01 foo
> ...
> ```
> 
> @nemozny:
> 
> > I think this is quite a simple and unlikely scenario
> 
> I think that scheduling a start time and a repeat frequency is a very common scenario. That's how jobs like "send morning news email" need to work.

`repeatEvery` re-calculates `nextRunAt`. So `schedule` should be called after `repeatEvery`. This worked for me.

``` javascript
const job = agenda.create('say', { message: 'foo' });
job.repeatEvery('2 seconds').schedule('in 5 seconds').;
job.save();
```
