### ISSUE TITLE
Is there a way to save the job results?

### ISSUE THREAD

**Issue by johnlop** [agenda/agenda#759]
Ideally I would want to save a list of all jobs instances that have run and the result.
Is there a way to do that with Agenda?

**Comment by rconstantine** [comment]
You can do anything at all in the job processors. So you could either add a collection (is that what mongdb tables are called?) to mongodb and store them there, or log to a file, or save in another database. I'll probably do one of the database options.

**Comment by johnlop** [comment]
Yes sure, that's what I'll do. I was just wondering if Agenda could do it automatically.
Thanks.
