### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [agenda/agenda#763]
https://travis-ci.org/agenda/agenda/jobs/468820997

**Comment by dandv** [comment]
[Failing](https://github.com/agenda/agenda/issues/738#issuecomment-458824920) [maintenance](https://github.com/agenda/agenda/issues/441#issuecomment-458811389), [rather](https://github.com/agenda/agenda/issues/718#issuecomment-458838540) :(

Pity this is the only job scheduling package backed by Mongo.

**Comment by santiq** [comment]
Hello! 

There is an open PR that could be related to this #701

**Comment by simison** [comment]
CI should now be much more stable since https://github.com/agenda/agenda/pull/852
