### ISSUE TITLE
"Please note that this must be a collection." - what is "this"?

### ISSUE THREAD

**Issue by dandv** [agenda/agenda#765]
https://github.com/agenda/agenda#mongomongoclientinstance:

> Use an existing mongodb-native MongoClient instance. This can help consolidate connections to a database. You can instead use .database to have agenda handle connecting for you.

> **Please note that this must be a collection.** Also, you will want to run the following afterwards to ensure the database has the proper indexes:

What exactly must be a collection?

**Comment by imhazige** [comment]
Same question!
