### ISSUE TITLE
 set delay for each run of concurrency

### ISSUE THREAD

**Issue by it-fm** [agenda/agenda#780]
Hello, it is possible to adjust the delay and define the interval of execution of each concurrency

**Comment by dandv** [comment]
The interval of execution between two consecutive runs of a job is specified in the `repeatEvery` parameter. Can you clarify what you mean?

Also, take a look at the [new example](https://github.com/agenda/agenda/pull/794) we're adding to the repo - maybe that helps better understand how concurrency works. See also [this doc PR](https://github.com/agenda/agenda/pull/794) that explains concurrency in more detail. (hopefully will be merged soon - ping @OmgImAlexis, @simison).
