### ISSUE TITLE
run only one recurring job at a moment

### ISSUE THREAD

**Issue by mohitzim** [agenda/agenda#781]
We can create different type of job using Agenda. I am using recurring job which is running at every 30 seconds. So every 30 seconds, a job is running. Sometimes a job is taking more than 30 seconds to run, but Agenda runs a scheduled job at 30 seconds (eventhough previous job is already running)

Following is the code :
```
const agenda = new Agenda({db: {address: db_address}, maxConcurrency: 1});

agenda.define('somejob', async (job, done) => {
  console.log('agenda job started..');
  somejob();
  done();
});
   
(async function() {
  await agenda.start();
  await agenda.every('30 seconds', 'somejob');
})();
```
Can we restrict agenda that if same type of job is running then dont run scheduled job ?

I tried with **maxConcurrency** and **defaultConcurrency** but didnt help. Can anyone please suggest solution ?

Thanks & Regards

**Comment by dandv** [comment]
Actually Agenda does run only one recurring job at a moment! See the new [doc on `concurrency`](https://github.com/agenda/agenda/pull/795/files#diff-04c6e90faac2675aa89e2176d2eec7d8R286).

What I think happens in your case is that the job takes longer than the `lockLifetime` (default 10 minutes), so agenda assumes it might have crashed or timed out. See in the README,

> Typically you shouldn't have a job that runs for 10 minutes, so this is really insurance should the job queue crash before the job is unlocked.

To tell Agenda that your job is still running, call [touch()](https://github.com/agenda/agenda#touch) from the job processor.

If you still have problems, please try to reproduce based on the [example](https://github.com/agenda/agenda/pull/794) I've just added, and re-open the issue.
