### ISSUE TITLE
scheduleJob runs multiple times

### ISSUE THREAD

**Issue by AydinE** [agenda/agenda#782]
I am having an issue with scheduleJob. I am trying to schedule it for a specific time in the future using:

`this.scheduleJob("sendTestMail", moment(new Date()).add(1, "minutes").toDate());`

This schedules it nicely and makes a MongoDB entry for the scheduled job. it runs once at the expected time (1 minute from now) and it updates the entry in the database to reflect the lastRunAt properly and sets nextRunAt to null as you can see below.

`_id: 5c890d530330e202d64a80c8`
`name: "sendTestMail"`
`data: null`
`type: "normal"`
`priority: 0`
`nextRunAt: null`
`lastModifiedBy: null`
`lockedAt: 2019-03-13 14:12:50.774`
`lastRunAt: 2019-03-13 14:12:50.779`

However for some unexplained reason it somehow fires the job again 10 minutes later. and sends out the mail again it keeps repeating it every 10 minutes until I stop the application. There are no other jobs but this 1 job and it gets scheduled at the start of the application. I clear the Database every time before I restart.

More info:

-  express (4.16.4)
- agenda (2.0.2)

**Comment by otelnov** [comment]
it is locked and 10 min is a defaultLockLifetime. Check your **define** method, if it is async - be sure you are calling done();
```
agenda.define('sendTestMail', (job, done) => {
  // send email logic
  done(); // !!!!!
});
```

**Comment by AydinE** [comment]
Thanks, that fixed it

**Comment by DevanshB10** [comment]
```
{
  "_id": {
    "$oid": "65d21a62b0672011458b40f9"
  },
  "name": "a52ea4aa10e4ecc8bfae408d90a74d36665ce7e661d35efe380e2828d43177b9",
  "data": null,
  "priority": 0,
  "shouldSaveResult": false,
  "type": "normal",
  "nextRunAt": null,
  "lastModifiedBy": null,
  "lockedAt": {
    "$date": "2024-02-18T15:15:57.428Z"
  },
  "lastRunAt": {
    "$date": "2024-02-18T15:15:57.546Z"
  }
}

```
I scheduled this job for a specific time to run once. But this executed 3 times, even after achieving nextRunAt: null

Can anyone help, why does this happen?
