### ISSUE TITLE
Jobs are getting locked before even running

### ISSUE THREAD

**Issue by madhavkaneriya** [agenda/agenda#823]
Job definition:
```
agenda.define('delay', function (job, done){
//do something
done();
job.remove();
})
```

Job scheduling:
`await agenda.schedule("2019-06-11 06:21:22.000Z", 'delay', someData);
`

Job created in mongoDB:
```
{
    "name" : "delay",
    "type" : "normal",
    "priority" : 0,
    "nextRunAt" : ISODate("2019-06-11T06:21:22.000Z"),
    "lastModifiedBy" : null,
    "lockedAt" : ISODate("2019-06-11T06:22:51.621Z")
}
```
So sometimes it executes the job but most of the time it just locks it few seconds/micro-seconds before the scheduled time and never executes it.

And after "defaultLockLifetime" (10 mins) it updates the "lockedAt" field but doesn't run the job.
 
How can I fix this?

**Comment by amangeot** [comment]
Hello @madhavkaneriya,
have you found a fix?

I've similar issues with jobs being scheduled, not executed, though when I restart the server, it runs all pending jobs.

**Comment by madhavkaneriya** [comment]
Yes, I was able to fix it @amangeot.
In my case done() and job.remove() functions were not getting called due to a mistake I made in my code.
Because of that jobs were getting queued internally and not running.
Hence closing the issue.

**Comment by amangeot** [comment]
Do we have to call job.remove() for following jobs to be executed?

**Comment by madhavkaneriya** [comment]
No, job.remove() has to be called only if you want to remove jobs from DB otherwise done() is enough.
