### ISSUE TITLE
run a job at same time of multiple timezones.

### ISSUE THREAD

**Issue by AhmadRaza786** [agenda/agenda#832]
I have to run a job daily at 5:00 AM in different timezones. 
e.g. A job `Send Notifications to expiring orders` need to b run at 5:00 AM daily according to LOS Angeles and Dubai Timezone.

I found a way to run a job at a specific single timezone. like
```
agenda.every('00 05 * * *', 'Send Notifications to expiring orders', null, {
      timezone: 'Asia/Dubai',
    });
```
I need to add another timezone with it. How can i do this ?

**Comment by sfny** [comment]
The simple approach is to create 2 jobs, one for each time zone. Agenda is built on cron, so the time you select to send notifications can either be single specific time or a specific interval ( example: every 62 hours ). Cron does not support multiple specific times of day, creating 1 job per time zone seems like a good option and has the added benefit of simpler tracking for your notifications.

**Comment by sfny** [comment]
So I'm wrong, cron services **can** use multiple times of day (like:  *2,4 * * *)  but I don't see a good way to handle time day light savings within a single job. Lmk if you found a good solution!

**Comment by nemozny** [comment]
I suggest using moment-timezone and re-creating the jobs each day. That's what I do.

**Comment by MichielDeMey** [comment]
> I suggest using moment-timezone and re-creating the jobs each day. That's what I do.

This is the right way to do it. 🙂
