### ISSUE TITLE
Remove old jobs from the DB

### ISSUE THREAD

**Issue by julianpoma** [agenda/agenda#835]
I did some searching but couldn't find a definitive answer.

I was thinking of creating a job that will remove finished jobs older than 30/60 days, based on some criteria (lastFinishedAt older than 30/60 days, nextRunAt not defined, failCount not defined). I would like to know if this is safe and won't cause troubles with the execution of agenda. I am aware of the `.purge()` option, but that's not what I am looking for.

The idea is to avoid having a collection with thousands of entries.

Have anyone done this before?

**Comment by dcsan** [comment]
https://www.npmjs.com/package/agenda#cancelmongodb-native-query-cb

isn't that what cancel allows you to do? just pass a param for the criteria in the DB?

**Comment by nemozny** [comment]
How could you possibly have thousands of jobs? The purpose of a job is to create a repeating task and scheduling it to be repeatedly executed. The jobs stays the same, there are no other entries.

**Comment by julianpoma** [comment]
@nemozny Maybe I have jobs to send an email or notification at some future time to a user ? Those jobs are different, since they have their own attrs (user email, user phone number, etc)

**Comment by dcsan** [comment]
but wouldn't you create a job like `sendDailyEmails` and then look through the users table to find who to send it to? 

or you prefer to use the job queue to serialize some data to use on the job instance?

**Comment by nemozny** [comment]
@julianpoma , I agree with @dcsan . I used to do the things the difficult way, before I started using DB more. I suggest you create 1 job "sendDailyEmails", as suggested, schedule it to run every minute. In the job you just look into some DB table, pick entries where the "sendTimestamp" is lower than the current timestamp, send those emails and delete the DB entry.
Simple, flexible, efficient.

**Comment by dcsan** [comment]
basically this is just using the job queue as a glorified `setTimeout` .. but it does seem simpler to me.
the only problem is if data might change in other tables and you need to snapshot a point in time. I have done things where you actually serialize all the code you're calling too, and just 'invoke' the job with it's data... but its a bit too much magic.

**Comment by bagayalu** [comment]
How did you solve it later, brother  ？ I have the same problem now, and the qps is very low

**Comment by julianpoma** [comment]
@bagayalu tbh I don't quite remember. I think that I just made another job to run once a day, that would query the collection of jobs and just delete them using the Mongoose driver.
