### ISSUE TITLE
repeat job, how to let the task only execute one time.

### ISSUE THREAD

**Issue by Serlight** [agenda/agenda#84]
Hi, 

i do like below:

var job = agenda.schedule('at noon', 'do something')
job.repeatEvery('12 hours');

At the begin , "job" will be executed 2 times. how can i let the task only execute one time.

**Comment by michelem09** [comment]
I'm closing this, feel free to reopen if needed.

**Comment by MrTechCenter** [comment]
I've followed @bestan 's suggestion above and formatted my sendNotifications.js job file as follows:

`let send = require('../models/notify');
let pullCompare = require('./pullCompare');


module.exports = function (agenda) {

    //Define name of job, functions of job, handle errors:
    agenda.define('sendNotifications', function (job, done) {
        console.log(pullCompare.changedCodecs);
        if (pullCompare.changedCodecs != null) {
            send.notifyUsers(pullCompare.changedCodecs);
            done();
        } else {
            console.log('No systems to send notifications for.');
            done();
        }
    });
    //Define when job should execute:
    agenda.on('ready', function () {
        var testJob = agenda.create('sendNotifications').schedule('in 15 seconds');
        //testJob.schedule('in 15 seconds');
        testJob.repeatEvery('5 seconds');
        testJob.save();
    });
}`

It DOES wait 15 seconds to run the job the first time, and continues to run one instance of the job every 5 seconds after that, however the very FIRST time the job is ran, it runs two instances of the job. In my code above, the "notifyUsers" function only has a single, unconditional console.log statement in it, so the program is running like this:

1.) Program starts
2.) Waits 15 seconds to run job
3.) Prints console.log in "notifyUsers" twice
4.) Waits 5 seconds
5.) Prints console.log in "notifyUsers" once
6.) Repeats steps 4-5 until program is exited

How can I fix this behavior so it's only running one instance of the job each time, including the first time? I can see two instances of the same job name in the MongoDB after the program starts and creates them, the only differences being the ObjectID (obviously) and the nextRunAt, where one of them is just two milliseconds ahead of the other.

**Comment by MrTechCenter** [comment]
I figured it out, had to add a dummy attribute "jobNo" and assign it an arbitrary value (I assigned it 1) and then add "testJob.unique({jobNo: 1})" after "testJob.repeatEvery('5 seconds')" and it only creates one job so it only executes the console.log in "notifyUsers" once on the first run and each interval after that now.

**Comment by sourov009** [comment]
Before saving the job calls `job.computeNextRunAt()` to ensure job runs only once.
