### ISSUE TITLE
multiple dynos on heroku

### ISSUE THREAD

**Issue by vduquette** [agenda/agenda#85]
I have three dynos running on heroku so my repeatEvery('1 day') job is running three times. Any way to prevent this?

**Comment by A-jacovchak** [comment]
@vduquette, I'm experiencing the same problem, and I am using cron.
How did you set up your cron job to run on only one dyno?

**Comment by A-jacovchak** [comment]
@vduquette, I'm experiencing the same problem, and I am using cron.
How did you set up your cron job to run on only one dyno?
