### ISSUE TITLE
Agenda job computes new nextRunAt to be current nextRunAt

### ISSUE THREAD

**Issue by ukcrpb6** [agenda/agenda#858]
## Expected Behaviour

nextRunAt should not be the current nextRunAt but the next interval ahead of the current nextRunAt

## Current Behaviour

Agenda job computes new nextRunAt to be current nextRunAt.

for example, 

![Screenshot 2019-09-18 at 16 41 39](https://user-images.githubusercontent.com/612798/65169426-6642eb80-da3e-11e9-8530-c163d52ea816.png)

In the above the new lastRunAt for a job running at 2019-09-16T15:30:00Z is computed to be 2019-09-16T15:29:59.999Z leading to the computation of nextRunAt to be 2019-09-16T15:30:00Z which doesn't trigger the check here

```javascript      
if (nextDate.valueOf() === lastRun.valueOf()) {
        // Handle cronTime giving back the same date for the next run time
        nextDate = cronTime._getNextDateFrom(dateForTimezone(new Date(lastRun.valueOf() + 1000)));
}
```

thus causing the job to run twice.

## Possible Solution

One possible solution is that when the run task computes the lastRunAt here:

https://github.com/agenda/agenda/blob/51058b5d27bcd8f6fd8de2863d96c10b0eabc23f/lib/job/run.js#L16

It checks that that the computed values is greater than the job's nextRunAt (currently unmodified so should be the expected run time for the currently executing job.

**Comment by koresar** [comment]
The fix is merged. Expected to be published with the next release.
