### ISSUE TITLE
Cleanly closing the database connection

### ISSUE THREAD

**Issue by mjgs** [agenda/agenda#875]
I have mocha tests that hang because the db connection never gets closed.

I tried agenda.stop() which I can see from the debug output is being run, but I can also see using wtfnode that there are db connections still open.

I also tried adding a agenda.db_close function:

```
Agenda.prototype.db_close = function(cb) {
  console.log('CLOSING DB CONNECTION');
  this._db.close(cb);
}
```

Which gets rid of the test hang, but the auto_reconnect kicks in and causes a 'server instance pool was destroyed' error. Setting autoReconnect:false in options had no effect.

How do I close the db connection cleanly?

**Comment by mjgs** [comment]
This ended up being a structural problem with my app. I refactored by creating a createMongoClient and scheduler utility modules which I run in series before startup. They provide create, get close/stop functions. I also run these in the test bootstrap before/after. 

The scheduler stop function calls agenda.stop() inside an immediately invoked async function. Now the tests no longer hang.

**Comment by simison** [comment]
Related; adding close method https://github.com/agenda/agenda/pull/450

Thanks for updating here that it was structural issue.
