### ISSUE TITLE
Causes exception if jobQueue is empty

### ISSUE THREAD

**Issue by AndreyB86** [agenda/agenda#885]
https://github.com/agenda/agenda/blob/b8579dcf7c69f763d0d3abaf44ed1e40128da0d5/lib/utils/process-jobs.js#L228

![image](https://user-images.githubusercontent.com/49086041/69859667-a2e45c00-12a5-11ea-96fa-5871cc97f372.png)

**Comment by Scorpil** [comment]
I have the same problem. #886 should fix it.

**Comment by AndreyB86** [comment]
Yeah, I think so. It's exactly the same issue

**Comment by koresar** [comment]
Fixed with v.2.3.0
https://github.com/agenda/agenda/blob/master/History.md#230--2019-12-16
