### ISSUE TITLE
TimeoutOverflowWarning

### ISSUE THREAD

**Issue by FreeDevStan** [agenda/agenda#888]
* **Node.js Version**: v12.13.1.
* **OS**: Microsoft Windows 10 Pro, Version: 10.0.18362 Build 18362
* **NPM packages**:

        "agenda": "^2.0.2",
        "appmetrics-dash": "^5.0.0",
        "avro-schema-registry": "^1.5.1",
        "avsc": "^5.4.16",
        "await-to-js": "^2.1.1",
        "bluebird": "^3.5.3",
        "body-parser": "^1.18.3",
        "dd-trace": "^0.12.1",
        "debug": "^4.1.0",
        "express": "^4.16.4",
        "express-server-status": "^1.0.3",
        "express-status-monitor": "^1.2.6",
        "json-2-csv": "^3.5.2",
        "kafkajs": "^1.11.0",
        "lodash": "^4.17.11",
        "moment": "^2.24.0",
        "mongodb": "^3.1.8",
        "mongoose": "^5.3.3",
        "mongoose-auto-increment": "^5.0.1",
        "qs": "6.9.0",
        "request": "^2.88.0",
        "request-promise": "^4.2.2",
        "sha256": "^0.2.0",
        "slack-node": "^0.1.8",
        "socket.io": "^2.2.0"

I was running only agenda jobs. Almost all jobs are syncing data from other API's and saving all data to MongoDB. Sometimes after some time when I start the project, I get this error: 

(node:26128) TimeoutOverflowWarning: 2591699977 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
at new Timeout (internal/timers.js:156:15)
at setTimeout (timers.js:142:19)
at jobProcessing (C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\lib\utils\process-jobs.js:258:7)
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\lib\utils\process-jobs.js:217:9
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\lib\agenda\find-and-lock-next-job.js:81:7
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\utils.js:414:17
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\utils.js:401:11
at ClientSession.endSession (C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\mongodb-core\lib\sessions.js:129:41)
at executeCallback (C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\utils.js:397:17)
at handleCallback (C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\utils.js:128:55)
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\operations\collection_ops.js:558:12
at handleCallback (C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\utils.js:128:55)
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\agenda\node_modules\mongodb\lib\operations\db_ops.js:516:5
at C:\Users\mailb\OneDrive\Desktop\DST\custom-market\node_modules\mongodb-core\lib\connection\pool.js:532:18
at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by MichielDeMey** [comment]
Looks like you are trying to schedule jobs too far into the future which overflows a 32-bit integer.
Make sure you sanitize your data before attempting to schedule the jobs straight from an API.

Also check if you can and/or are running a 64-bit version of Node.js.

**Comment by marceloavf** [comment]
I'm having this problem but using every method from agenda like this:

agenda.js
```
const Agenda = require('agenda');
const agendash = require('agendash2');
const config = require('./config/config');

const agenda = new Agenda({ db: { address: config.mongoose.url, collection: 'agenda' } });

require('./jobs/scraping')(agenda);

agenda.on('ready', async () => {
  await agenda.every('30 1 5 * *', 'XX', null, {
    timezone: 'America/Sao_Paulo',
  });

  await agenda.every('00 3 5 * *', 'XXXX', null, {
    timezone: 'America/Sao_Paulo',
  });

  await agenda.every('30 4 * * *', 'XXXXXX', null, {
    timezone: 'America/Sao_Paulo',
  });

  await agenda.every('00 6 * * *', 'XXXXXXXX', null, {
    timezone: 'America/Sao_Paulo',
  });
});

module.exports = { agendash: agendash(agenda), agenda };
```

jobs/scraping.js
```
module.exports = (agenda) => {
  agenda.define('XX', { concurrency: 1, priority: 'highest' }, async () => {
    await init1();
  });
  agenda.define('XXXX', { concurrency: 1, priority: 'high' }, async () => {
    await init2();
  });
  agenda.define('XXXXXX', { concurrency: 1, priority: 'normal' }, async () => {
    await init3();
  });
  agenda.define('XXXXXXXX', { concurrency: 1, priority: 'low' }, async () => {
    await init4();
  });
};
```

When it happens, logs become too high that uses all disk space ☹
