### ISSUE TITLE
Question on recurring maintenance job

### ISSUE THREAD

**Issue by jgallen23** [agenda/agenda#89]
I have a job that I want to run every night at midnight.  So, I planned on creating a cron-style job when the server starts.  But, if for some reason, the server crashes and restarts, the code to create that job will get called again and I'll now have two tasks running at midnight.  Is there a good way to check to see if the job is already in the queue or is there a better place to put recurring, maintenance type jobs?

Another similar question, is if I'm using the cluster module on my server, won't the job create code get called for every child that the cluster module spins up.

I'm sure I'm just missing something, because these seem like they would be common use cases.

**Comment by michelem09** [comment]
I'm closing this, feel free to reopen if needed.
