### ISSUE TITLE
Health checks

### ISSUE THREAD

**Issue by pedrodevoto** [agenda/agenda#891]
Hi everyone. 

This is just an open question regarding best practices to check the correct functioning of agenda. Do any of you have some procedure? We'd need to check agenda's health in our workers health check endpoint. 

What do you guys recommend?

**Comment by MichielDeMey** [comment]
There are a few way you can facilitate this, depending on how you've setup your health checks.

You can create a `healthCheck` job that runs every N minutes.

Then in your healthcheck endpoint query for the last successful run of that job using [a query](https://github.com/agenda/agenda#jobsmongodb-native-query-mongodb-native-sort-mongodb-native-limit-mongodb-native-skip). Then simply check if the timestamp of the success run is within acceptable limits.

**Comment by wootwoot1234** [comment]
@pedrodevoto did you solve this?  I have been using this query but it's very resource-intensive and I'm looking for an alternative.  I just want to know if everything is running well.

This code is an expressjs endpoint that can be called from a service like uptime robot.  It tells you how many queued jobs there are.  

WARNING: I don't' recommend you use this because it's a very expensive query.  I'm posting this in the hopes that someone has a better way to check how many queued jobs there.


    app.get(
        "/jobStatus/:quantity?",
        wrapAsync(async (req, res, next) => {
            logger.trace("/queuedJobs");
            let {quantity} = req.params;
            quantity = parseInt(quantity, 10);
            if (isNaN(quantity)) {
                quantity = 1000;
            }
            const results = await Job.aggregate([
                {
                    $project: {
                        _id: 0,
                        name: "$name",
                        nextRunAt: {$ifNull: ["$nextRunAt", 0]},
                        lastFinishedAt: {$ifNull: ["$lastFinishedAt", 0]}
                    }
                },
                {
                    $project: {
                        name: "$name",
                        queued: {
                            $cond: [
                                {
                                    $and: [
                                        "$nextRunAt",
                                        {$gte: [new Date(), "$nextRunAt"]},
                                        {$gte: ["$nextRunAt", "$lastFinishedAt"]}
                                    ]
                                },
                                1,
                                0
                            ]
                        }
                    }
                },
                {
                    $group: {
                        _id: "$name",
                        displayName: {$first: "$name"},
                        queued: {$sum: "$queued"}
                    }
                }
            ]);

            const totals = {}; 
            const states = ["queued"];
            states.forEach(state => {
                totals[state] = 0;
            });
            results.forEach(job => {
                states.forEach(state => {
                    totals[state] += job[state];
                });
            });

            let statusCode = 200;
            if (totals.queued > quantity) {
                statusCode = 500;
            }

            res.status(statusCode).json(totals);
        })
    );

**Comment by wootwoot1234** [comment]
Per @MichielDeMey suggestion.  I settled on this which is much faster.  It doesn't tell me if there are some jobs that aren't getting run, for example, if I was to forget to define a job and it queued without running it wouldn't tell me.  That's because I already have other jobs running, this will continue to run without throwing a flag.  My previous check would alert me if I got too many jobs in the queue.

    app.get(
        "/jobStatus/:quantity?",
        wrapAsync(async (req, res, next) => {
            logger.trace("/queuedJobs");
            let {quantity} = req.params;
            quantity = parseInt(quantity, 10);
            if (isNaN(quantity)) {
                quantity = 1000;
            }

            const completedJobsCount = await Job.find({
                lastFinishedAt: {$gte: moment().subtract(5, "minutes")}
            }).countDocuments();

            let statusCode = 200;
            if (completedJobsCount < quantity) {
                statusCode = 500;
            }

            res.status(statusCode).json(completedJobsCount);
        })
    );
