### ISSUE TITLE
Agenda.jobs() is missing skip capability to be able to do paging

### ISSUE THREAD

**Issue by cjolif** [agenda/agenda#897]
Agenda.jobs() provides the ability to set the MongoDB limit parameter but not the skip one. This prevents one using this API to do paging on the list of jobs.

ref: https://github.com/agenda/agenda#jobsmongodb-native-query-mongodb-native-sort-mongodb-native-limit

**Comment by cjolif** [comment]
I issued a PR for this, anyone interested in reviewing it?

**Comment by MichielDeMey** [comment]
Should be fixed with your PR. 👍

**Comment by cjolif** [comment]
Thanks a lot for merging
