### ISSUE TITLE
repeatEvery with skipImmediate: false in 2.3.0 not working

### ISSUE THREAD

**Issue by hitpotato** [agenda/agenda#911]
Seems like not working for 2.2.0 above. It won't run a job immediately even you set it to false

**Comment by Ademo13** [comment]
I'm noticing the same thing. And I'm trying to determine at what root level of the project I can pass "skipImmediate: true" so as to make it the default from now on. Any clarity on this would be much appreciated.

**Comment by MichielDeMey** [comment]
Odd, it should have been fixed in `v2.2.0` in https://github.com/agenda/agenda/pull/861/
