### ISSUE TITLE
Can I schedule a task to run on Saturday

### ISSUE THREAD

**Issue by sojohnnysaid** [agenda/agenda#927]
agenda.scheduleOnce('this saturday')?

something like that? This is just a test I was doing and it works but i'm worried if I do it for Saturday it will run every saturday. Any ideas?

```javascript
const Agenda = require('agenda');

const connectionString = process.env.MONGODB_URI

const agenda = new Agenda({
	db: {address: connectionString, options: { useUnifiedTopology: true, autoReconnect: false, reconnectTries: false, reconnectInterval: false }, collection: 'lobby matches'},
	processEvery: '3 seconds'
});

agenda.define('send lobby invites', {priority: 'high', concurrency: 10}, (job, done) => {
	const {name} = job.attrs.data;
	console.log( `Hi ${name}, the lobby invites have been sent!` )
	agenda.cancel( { name: 'send lobby invites' }).then((value) => {
	  console.log( value )
	})
	done()
});

remindMe = async (name) => {
	await agenda.start();
	await agenda.schedule('in 5 seconds', 'send lobby invites', {name: name});
}

console.log(remindMe('John Smith'))

agenda.on('success:send lobby invites', job => {
  console.log(`Sent invites successfully ${job.attrs.data.name}!`);
});
```

**Comment by MichielDeMey** [comment]
If you look at the documentation, you'll see `schedule(when, name, [data])` where `when` can be a `Date`.

So you can use any library you want to determine what the timestamp should be for "next saturday" (e.g. [moment.js](https://momentjs.com/)) and simply pass that to the `schedule` function. 🙂

Internally, Agenda uses [date.js](https://github.com/datejs/Datejs) to parse the string to a date/time, so best check their documentation for the string parsing.
