### ISSUE TITLE
Try to enqueue 70K jobs and gets stuck

### ISSUE THREAD

**Issue by tinhochu** [agenda/agenda#929]
Hey guys. Not sure if I'm doing correctly. 

But I'm enqueuing over 70K jobs on a for of loop.

But never got processed. 
I checked the log and it's like it gets stuck and creates more jobs. Not sure if you can help me with that.

**Comment by MichielDeMey** [comment]
Can you give us some more information?
Debug logs and perhaps a code sample would be useful.
