### ISSUE TITLE
DeprecationWarnings: autoReconnect, reconnectTries, reconnectInterval

### ISSUE THREAD

**Issue by ekegodigital** [agenda/agenda#939]
I'm using the Docker Image mongo:3.6 and switched the "useUnifiedTopology" parameter to true as advised. If I do so I get the following deprecation warnings:

> (node:51) DeprecationWarning: The option autoReconnect is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
> (node:51) DeprecationWarning: The option reconnectTries is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6
> (node:51) DeprecationWarning: The option reconnectInterval is incompatible with the unified topology, please read more by visiting http://bit.ly/2D8WfT6

An easy fix would be, to not set those three, if "useUnifiedTopology" is handed over as option to the database.js

**Comment by ekegodigital** [comment]
[database.js.txt](https://github.com/agenda/agenda/files/4236063/database.js.txt)

This will work, let me know if you need a PR.

**Comment by ekegodigital** [comment]
[database.js.txt](https://github.com/agenda/agenda/files/4236067/database.js.txt)

This will work, let me know if you want a PR.

**Comment by ekegodigital** [comment]
[database.js.txt](https://github.com/agenda/agenda/files/4236080/database.js.txt)

This works, let me know if you want a PR.

**Comment by HuddleHouse** [comment]
I was having the same problem, but your database.js file works! Thanks @ekegodigital

**Comment by MichielDeMey** [comment]
Fixed with https://github.com/agenda/agenda/pull/948
