### ISSUE TITLE
Getting error for adding 7 digit subexpression

### ISSUE THREAD

**Issue by PankajGadia16** [agenda/agenda#953]
Trying to add expression "* * * 1 12 ? *" in the first argument of agenda.every function.

The task executed 1 time at the same moment and agenda failed giving this:

{
    "_id" : ObjectId("5e54bda9afbd72004211f709"),
    "name" : "testing",
    "type" : "single",
    "data" : {
       "name": "pankaj"
    },
    "failCount" : 1,
    "failReason" : "failed to calculate nextRunAt due to invalid repeat interval",
    "failedAt" : ISODate("2020-02-25T06:24:41.912Z"),
    "lastFinishedAt" : ISODate("2020-02-25T06:24:41.912Z"),
    "lastModifiedBy" : null,
    "nextRunAt" : null,
    "priority" : 0,
    "repeatInterval" : "* * * 1 12 ? *",
    "repeatTimezone" : null
}

Not sure what is the reason for this error because the expression is valid (also validated at http://www.cronmaker.com/)
Let me know If I am missing on something.

**Comment by MichielDeMey** [comment]
Agenda uses [cron.js](https://github.com/kelektiv/node-cron) for the underlying parsing or CRON expressions.

I quickly inputted your expression `* * * 1 12 ? *` in the library and it returns an invalid expression error.
This means they might not support the "second" field. In addition, it looks like they cannot parse the non-standard `?` character.

To move this issue forward, you'll want to move this discussion to the cron.js repository.
