### ISSUE TITLE
Scheduled task executes immediately

### ISSUE THREAD

**Issue by canastro** [agenda/agenda#97]
What am I doing wrong? I'm simply trying to schedule a task in a future date passing a javascript date, but the task is being executed immediately.

My sample code: 
- http://pastebin.com/Qn9Qzw4z

My final goal is to have a task to be scheduled to a given Javascript date and to repeat every two seconds...

**Comment by nwkeeley** [comment]
@canastro I second this..... code seems to work fine for me.

Nates-MBP:agenda $ node agenda.js
task scheduled to: Sat Jan 24 2015 12:02:05 GMT-0500 (EST)
task executed at: Sat Jan 24 2015 12:02:05 GMT-0500 (EST)

**Comment by nwkeeley** [comment]
@canastro I second @bestan comment seems to run fine.

Nates-MBP:agenda $ node foo.js
task scheduled to: Sat Jan 24 2015 12:02:05 GMT-0500 (EST)
task executed at: Sat Jan 24 2015 12:02:05 GMT-0500 (EST)

**Comment by rschmukler** [comment]
@canastro can you ensure that you're running the latest version of the module? There was an issue fixed in a previous version that should resolve this.

**Comment by michelem09** [comment]
I'm closing this, feel free to reopen if needed.
